### ISSUE TITLE
Improve Model/Controller separation

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#100]
Models are intended to represent stored data.  Controllers are intended to represent program logic; the manipulation that's done to stored data.

Django tries to [claim](https://docs.djangoproject.com/en/dev/faq/general/#django-appears-to-be-a-mvc-framework-but-you-call-the-controller-the-view-and-the-view-the-template-how-come-you-don-t-use-the-standard-names) that Views are the new Controllers; or at least that Controllers, in the MVC sense, aren't really a part of their MTV design.  We tried that strategy at first, but ultimately found that what we really want is MTVC; "all of the above".  So we've been adding Controllers recently, and pulling control logic out of views and models into which it had previously been inelegantly smooshed.

We should keep doing this.  Elegant abstraction barriers and all that.

**Comment by benjaminjkraft** [comment]
I think these days we are not really moving in this direction and I don't know that I have a desire to; I'm generally more of a fan of fat models.
