### ISSUE TITLE
Two-phase student reg: hard to remove a priority class

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1015]
From Alex Cole at MIT:
"After you save a 1st choice class, it is hard to remove it. If I return to the edit first choice class page, it shows no class selected. Then when I save that, the class remains. The only way to remove it is to go to the edit page, add the class again, and then hit the x to remove it. I think that we just want the class to be pre-selected."

**Comment by luac** [comment]
Is this still an issue? Is there already an issue for "fix what use_priority does"?

**Comment by luac** [comment]
It looks like the root problem of this might have been fixed in 75e859fda.
