### ISSUE TITLE
HTML Validate QSDs

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1027]
If an inline QSD contains improper HTML (such as forgetting to close a tag), sometimes the rest of the page is improperly rendered. When a QSD gets edited, we should run it through an HTML validator, and prevent the save from occuring / inform the user if certain errors are detected.

**Comment by willgearty** [comment]
This is indirectly fixed by #2665. The GUI package uses beautify.js or something like that to correct the source code when the user switches from source code mode to rich text mode.
