### ISSUE TITLE
TwoPhase assumes Lunch category exists

### ISSUE THREAD

**Issue by luathenalena** [learning-unlimited/ESP-Website#1081]
It crashes if it doesn't, see: https://github.com/learning-unlimited/ESP-Website/blob/667e9cf/esp/esp/program/modules/handlers/studentregtwophase.py#L143

The only purpose of this line is to filter out the Lunch class so that students can't select it, but it should be fine not to have a lunch category in the first place for a program that doesn't have lunch, so this is a bug.

This line of code may go away anyway when #770 is fixed, so we may not have to fix this directly.

**Comment by willgearty** [comment]
Fixed by https://github.com/learning-unlimited/ESP-Website/pull/2088.
