### ISSUE TITLE
Extra Costs Doesn't Show Option Costs

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1120]
When there are multiple options for a line item, the cost is listed as "varies".

The page should perhaps be rearchitected so that instead of having three columns ("Buy", "Item", "Cost Each"), it has two-columns ("Buy" and "Item"), and the cost of each item or each option is listed as part of the field label.

**Comment by milescalabresi** [comment]
Options should also be able to accept a default/uniform cost. For instance, if there are different lunch options (say, pizza toppings), but the cost is the same, it's not only confusing, but also wrong to say that the cost "varies" with the options.

**Comment by willgearty** [comment]
Fixed by #1528.
