### ISSUE TITLE
Two phase lottery: approved but unscheduled classes show up

### ISSUE THREAD

**Issue by luanthe** [learning-unlimited/ESP-Website#1125]
The lottery interface should show scheduled classes only.

**Comment by willgearty** [comment]
I think we'd want to change the returned list of sections here:
https://github.com/learning-unlimited/ESP-Website/blob/a0a1e50fbee39598313869d917f43ffd889cc30b/esp/esp/program/modules/handlers/jsondatamodule.py#L182
and maybe here:
https://github.com/learning-unlimited/ESP-Website/blob/a0a1e50fbee39598313869d917f43ffd889cc30b/esp/esp/program/modules/handlers/jsondatamodule.py#L367

**Comment by willgearty** [comment]
Probably want to make sure those json calls aren't used anywhere else, first, though.
