### ISSUE TITLE
Changing the name of a classroom breaks things in AJAX scheduler

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1130]
We changed the names of some classrooms after scheduling was done, and then loaded the AJAX scheduler. Result: the classrooms showed up under their old names, with correct availability but no classes scheduled in them. It was fixed by flushing the cache.

**Comment by luac** [comment]
It looks like this might not be an issue with the new scheduler.

**Comment by benjaminjkraft** [comment]
Seems like this is not an issue in the new scheduler, but #2385 is.
