### ISSUE TITLE
Link to LU feature request page on /manage/programs

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#1149]
Requested by Jacob (MIT) a long time ago:

It would be really helpful to put under /manage/programs/ a link to the LU feature request page, because (a) I always forget where it is, and (b) the only link I know of is on the LU wiki, and not everyone has an account.

**Comment by laraao** [comment]
Will add the following link `https://wiki.learningu.org/How_to_use_the_website#Feature_Requests` to the end of `Here are some tips:` section of the manage/programs page.
