### ISSUE TITLE
Condense multi-hour classes on student schedules

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#1151]
Requested from Stanford a long time ago:

If a class lasts over multiple timeslots, just condense those timeslots into one block on the student schedules.  This causes confusion for a lot of students every Splash.

Note: This is not as simple as it sounds since we currently have the same interface for showing lottery preferences, which can overlap multiple sections in one timeslot.  We also write "Continued" for the latter hours of a multi-hour class, which may be sufficient.

**Comment by mgersh** [comment]
Duplicate of part of #50
