### ISSUE TITLE
Encourage use of Markdown in QSD (vs. HTML)

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#1152]
Idea from Jacob (MIT) a long time ago:

Lots of people don't use Markdown for QSD, and this annoys me. Right now:
- if you edit QSD inline, there's no indication that you can use Markdown
- if you go to .edit.html, there's a short link to the Markdown help page but that's it

I propose:
- editing the "click here to edit the text" text to somehow encourage the use of Markdown, and
- on .edit.html, instead of just linking to the Markdown website, have a quick guide to common commands (like the Reddit "formatting help" link)

**Comment by szhu** [comment]
Previews would be nice. GitHub and Stackoverflow do a good job of this.

Syntax highlighting and formatting in Markdown mode might be nice too. [dillinger.io](http://dillinger.io/) is a good example.

**Comment by willgearty** [comment]
I'm going to consider this fixed by #2665 (we've moved to the dark side of HTML, but it now includes lots of user-friendly features and a nice preview even if you use HTML).
