### ISSUE TITLE
Two phase student reg: stars sometimes don't load

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#1179]
Stanford has reported that several students (Spring 2014) didn't see their interested classes show up as starred in phase 2 after completing phase 1.  This is much preferable to a failure in saving the preferences (which seems less likely although we can't rule out), but still very confusing.  It may be an occasional Javascript error during the initialization process that we just haven't tracked down yet.

**Comment by willgearty** [comment]
Has anyone heard of students encountering this error since 2014?

**Comment by mariolsen0112358** [comment]
We get occasional emails, but we just tell them not to use Internet Explorer and that seems to fix the issue

**Comment by willgearty** [comment]
Yeah, the last time I recall this problem, directing them to use firefox or chrome also fixed it.
Should we try to fix whatever is causing the problem, or is fixing compatibility with IE just not worth the trouble?

**Comment by mariolsen0112358** [comment]
Unless it's a really easy fix, I wouldn't bother, especially because Explorer has been replaced by Edge and it seems like Edge plays better with the website (just from a lack of recent complaints rather than actual testing)

**Comment by willgearty** [comment]
Let's go ahead and close this then!
