### ISSUE TITLE
Shirt statistics missing when fitted shirt option is removed

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#1194]
The program dashboard shows the number of shirts in each size requested by teachers.  However, if you set the "teacherinfo_shirt_type_selection" Tag to False in order to remove the distinction between "plain" and "fitted" shirts, the dashboard shows all zeros.  This should be an easy fix, probably in the Program.getShirtInfo() function at esp/esp/program/models/**init**.py:1025.

Princeton ran into this bug two years in a row.

**Comment by kkbrum** [comment]
Pull request #2524 fixes this (and the checks passed after fixing some whitespace)?  Is there something else that needs to be done here?

**Comment by willgearty** [comment]
We don't close issues until pull requests get merged, just a workflow thing :)
And if you put "Fixes #XYZ" in the description of a pull request, the issue will actually get closed automatically when the PR gets merged.
