### ISSUE TITLE
Consolidate Comm Panel e-mails

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#120]
Perhaps optionally, consolidate multiple e-mails to one for people who have the same e-mail address for multiple accounts.

This would, of course, be trickier if the e-mail contains custom text; for example, the person's name, their schedule, etc., which might be different across the different accounts.

**Comment by bhorowitz** [comment]
Is this still desired by UChicago (or any other) Splash?

**Comment by benjaminjkraft** [comment]
I think in principle this would be nice, but in practice doing it right would be hard enough that it's probably not worth it.
