### ISSUE TITLE
Limited scope student-accessible onsite class changes

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1208]
(This is an idea for discussion. It has not been requested yet, and we should not build this yet. This is for tracking implementation ideas, and eventually tracking implementation if it is requested.)

Right now, students can only change classes during a program by visiting onsite class changes and asking a volunteer to change their schedule. But it is often hard to get enough volunteers to fully staff onsite, and there are often crowds of students that are too big for the number of volunteers or even for the size of the room. If a class is canceled, it might take a while for a student to get from the class to onsite, then there may be few classes left by that point, it is hard to use the scrolling list to find classes, and then the student might be very late once they finally get into a class.

With the growing popularity of smartphones, the existence of a student class changes module could help alleviate some of these problems. One reason this hasn't been implemented yet is because the existence of such a system would be unfair to those who do not have such devices, including underserved students. However, it was proposed by Stanford Splash volunteers that such a system could also help smartphone-less students, since they would be better helped by a less crowded onsite. Additionally, if the system were limited in scope, it wouldn't give smartphone users a very large advantage.

Here are some ideas for a limited scope student class changes. None of these ideas are mutually exclusive, they can be mixed.
- Only allow students to switch their own classes for the current or upcoming blocks (or just the current block).
- Only allow students to switch their own classes once per timeblock.
- Only allow students to switch into a new class when their current class has been canceled.
- Class cancellation emails can include a link to student class changes.
- Class cancellation emails can include a list of open classes during that timeblock, and allow students to switch classes with the click of a link.
- Even if the lottery isn't being used, allow students to star classes during registration, and allow students to filter by starred classes when looking for classes to switch into.
- The module needs to work well and be tested on small mobile devices.

For all of the "only allow students to..." ideas, the students can get around those restrictions by visiting onsite class changes in person.

**Comment by willgearty** [comment]
This concept has been included in #2507 .
