### ISSUE TITLE
Printable: list of classes by teacher

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1220]
It would be useful to have a printable for a list of classes, sorted by teacher.

**Comment by willgearty** [comment]
This should be pretty easy using `classesbyFOO`: https://github.com/learning-unlimited/ESP-Website/blob/b584f15da900eac1f07400af33123077631d4e4e/esp/esp/program/modules/handlers/programprintables.py#L313
