### ISSUE TITLE
Merge server setup scripts

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1284]
There are currently three scripts in ```esp/useful_scripts/server_setup```. It would be great if we could merge them into one, so that the functionality does not continue to diverge.

```dev_server_setup.sh``` is kept most up-to-date, and should be the basis of the merged script (though it might need a rename, to reflect the all-purpose nature of the final script).

```new_site.sh``` lags behind ```dev_server_setup.sh``` in some of its newer functionality, but might have some production-specific functionality that should be reviewed and possibly merged over. ```dev_server_setup.sh``` already has a ```--prod``` flag which can be used to trigger parts of the script that are only to be used for new production sites.

```dev_server_setup_mac.sh``` is out-of-date. We need to figure out what set of packages need to be installed on Mac dev-servers, and move those requirements into ```packages_mac.txt``` and ```requirements_mac.txt``` files. Maybe there will also be some setup steps that are different on a Mac. Figuring out which steps / dependencies are needed can be done by automatically figuring out the OS-type when the script runs. Or we can add a new --mac flag. We don't need to replicate everything in two files.

This would potentially be replaced by #965 or #1142, but could be a low effort improvement to the setup infastructure in the meantime.

**Comment by btidor** [comment]
After #1529, there are only two scripts now (our fabfile, and `new_site.sh`). Further discussion should move to #965.
