### ISSUE TITLE
Production server setup needs to handle dbmail

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1285]
When setting up a production site, the ```dbmail_cron.py``` script needs to be added to ```/etc/crontab```, and the site needs to be added to the ```exim4``` configuration. This is not currently handled by the setup script, and needs to be done manually. When this manual step is forgotten, the new site is misconfigured, and cannot send or receive mail. This should be done automatically by the server setup script, when installing a production environment.

Related to #965, #1142, and #1284.

**Comment by benjaminjkraft** [comment]
Fixed by #1529 and #1963.
