### ISSUE TITLE
Update local_settings.py.default

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1286]
When we manually ```update local_settings.py```, we sometimes forget to update ```local_settings.py.default```, so that future site installs also get to take advantage of the new setting. We should look through the ```local_settings.py``` files of the current chapter sites and dev servers, and see if there is anything worth adding.

One example of something I know we have to do: add the ```SECURE_PROXY_SSL_HEADER``` setting, so that ```request.is_secure()``` works on newer sites. Though, in this particular case, it's also arguable that we could maybe move that to ```django_settings.py```. In either case, this setting needs to be added to the repository.

Requires #1287. Or, without #1287, the template in the server setup script should also be updated.

**Comment by benjaminjkraft** [comment]
Fixed and/or made moot by #1529.
