### ISSUE TITLE
Use local_settings.py.default in dev server setup.

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1287]
@luac and I were talking about this: right now, the dev server setup script asks for a bunch of configuration options, and then generates a `local_settings.py` from a hardcoded template and those options.  We should definitely be using the `local_settings.py.default` in some way, since we generally forget to update the dev server setup script.  Probably the easiest thing is just to not bother doing the whole configuration thing, and just have the script copy `local_settings.py.default` to `local_settings.py`, and tell the user to go update it, and it can have some comments telling them what the variables that they're filling in mean, and useful defaults for the ones that most people don't care to change.

**Comment by pricem** [comment]
From discussion on #1529: I think the current goal is to centralize all of the settings.py components in one file which would be used by different setup mechanisms.  This would require handling some differences in requirements between the production setup (new_site.sh), the development setup (Vagrant), and the Travis setup, and any other variants I'm forgetting.

**Comment by benjaminjkraft** [comment]
This specific issue is fixed and/or made moot by #1529.  I'll open a new one to more generally merge the various `local_settings` templates we still have.
