### ISSUE TITLE
Update Apache conf template

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1288]
When setting up a new production site, the server setup script will use a template to create an Apache conf for the site.

This template has become out-of-date with what we actually use with the live sites. We should look through the apache ```*.conf``` file for the current chapter sites, and make necessary updates.

Two examples of things I know we have to do:
- Make the ```VirtualHost```s listen on port ```81```.
- Add the redirect from http to https.

We could also consider moving the template to its own file, outside of the server setup bash script.

**Comment by btidor** [comment]
This seems to have been fixed by #1529, unless it fell out of date yet again.

**Comment by benjaminjkraft** [comment]
It fell out of date again, and is updated again in #1963.
