### ISSUE TITLE
Some directories created with incorrect permissions

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1289]
When I set up Berkeley's site, there were initially permissions errors for some directories. This was observed with ```esp/public/media/images/theme``` and ```/tmp/esptmp__calESP```.

These directories, and any others created by the website, should be owned by and/or be modifiable by the ```www-data``` user and group.

**Comment by benjaminjkraft** [comment]
Fixed by #1963.
