### ISSUE TITLE
StudentRegistration model and Mailman

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#129]
Make StudentRegistration model functions perform same mailing list operations as ClassSection.[un]preregister_student().

Probably, all the mailing list operations that are currently scattered throughout the code should simply be consolidated into event listeners that watch for changes to the StudentRegistration model, and mirror the changes onto mailing lists.

**Comment by benjaminjkraft** [comment]
Closing in favor of #1260.
