### ISSUE TITLE
Custom Form links (e.g. Program links) don't work

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#1337]
On https://yale.learningu.org/teach/Splash/2014_Fall/extraform, the custom form (customform -- just to get this as a keyword in here) renders correctly and lets the user fill it out, but does not submit the answer. When the user clicks "submit," there is a "whoops server error:"
DatabaseError
Exception Value:  
column customforms_response_52.link_Program_id does not exist.

We have looked carefully, and both the form and the program appear to be correctly created and tagged.

**Comment by milescalabresi** [comment]
Bumping this following more discussion with the Chapter Board. As a broader issue, custom forms are incredibly buggy, don't accept edits (or importing forms from old programs) reliably. However, multiple chapters have expressed interest in using them if they were easier to work with. For that reason, I think improving their ease of use and reliability should be a priority on the next stable release. I think fixing it is above my skill level, but I'd be happy to collaborate and can give specific requests and details if anyone's interested in working on this.

**Comment by mgersh** [comment]
I did some work on custom forms for Django 1.8, and separately saw MIT running into some of the issues with editing and other general bugginess. In my opinion, the ideal solution here would be a full rewrite, although I'm not sure any of us has time and energy to do that. I'm going to go make a new issue with a more general title and say more things there.

**Comment by willgearty** [comment]
I was able to submit this custom form without error, so I'm assuming this is fixed. @milescalabresi can open this if he knows anything about how it was resolved or if it's happened again.
