### ISSUE TITLE
Previews of other classes on teacherreg page don't update

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1344]
I submitted my class with a placeholder description. Later, I went back and edited it. After editing and going back to the teacher reg page, when I clicked on the heading to preview classes (the one that has everyone else's classes as well), the placeholder description was still there. I checked that it's not browser caching.

**Comment by joeleg** [comment]
After investigating this, I don't believe this is a bug, but likely related to a stale record on the server side cache.

**Comment by mgersh** [comment]
Yes, I agree with you that it's related to server-side caching. Since almost all of the caching in our website is based on expiring the cache when the data changes, not on timeouts, stale data is a bug.
