### ISSUE TITLE
Delete button on list of flags

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1356]
It would be useful to have a little "x" next to the flag name, to quickly delete (or resolve -- see #1349) the flag.

**Comment by willgearty** [comment]
I believe this is implemented in /classsearch and /manageclass. Should it be anywhere else?

**Comment by benjaminjkraft** [comment]
Not quite!  In those views you have to open up the flag and click "Remove" -- the idea here is to add a little "x" when we're just showing the flag name, so you can remove it more easily.

**Comment by willgearty** [comment]
Oh, well that should be fairly simple to implement, then!
