### ISSUE TITLE
All teacher, student names in manage pages should hyperlink to user view

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1374]
For example, lists of teachers in the dashboard, manage class pages, class flags pages, and scheduling checks. Or students in the credit card viewpay module.

Requested by Stanford.

**Comment by willgearty** [comment]
Links added to viewpay in https://github.com/learning-unlimited/ESP-Website/pull/2979

**Comment by willgearty** [comment]
Teachers also already have links on the manage class page
