### ISSUE TITLE
Prevent people from registering for walk-in seminars

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#138]
Some chapters have the notion of a "Walk-In Seminar".  It shows up in the catalog, but you don't register for it; you just show up if you're interested.  We should support this properly, and display it in a consistent and useful way throughout the UI.

**Comment by bhorowitz** [comment]
Is this till desireable? I'm uncertain how walkins currently are displayed on catalogs.

**Comment by benjaminjkraft** [comment]
Broadly we do support this now -- so any places where we don't are bugs and any ways in which we could make that support cleaner in the codebase are possible refactoring ideas.
