### ISSUE TITLE
Sorting classes in the scheduler

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1387]
Several MIT admins requested the ability to sort classes in the ajax scheduler.  Possible sorting methods include:
- by teacher
- by teacher "hosedness" (e.g. number of available class-hours minus number of unscheduled class-hours)
- by size

**Comment by willgearty** [comment]
We already have options to sort by teacher and capacity. We already have teacher availability, but we could add teacher "hosedness". Open to any other suggestions!
