### ISSUE TITLE
Show "room request" in scheduler

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1388]
The "room request" field is not displayed in the scheduler tooltips, even though it is quite relevant.

**Comment by willgearty** [comment]
Just need to add it here:
https://github.com/learning-unlimited/ESP-Website/blob/1628bc2422b5954ac3555c7e007e277fcd74afa6/esp/public/media/scripts/ajaxschedulingmodule/ESP/SectionInfoPanel.js#L107-L113

and here:
https://github.com/learning-unlimited/ESP-Website/blob/9147b7912921642812fa3fc4bfdbca35eaac9665/esp/public/media/scripts/ajaxschedulingmodule/ESP/Cell.js#L134-L139
