### ISSUE TITLE
Scheduler stores classrooms by name rather than ID

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1391]
This means that if a classroom is renamed, you can't schedule anything into it until refreshing the scheduler.

**Comment by willgearty** [comment]
Is this related to #1130?

**Comment by benjaminjkraft** [comment]
It looks like this is still true in the new scheduler, although I'm not totally sure.

**Comment by willgearty** [comment]
I attempted to fix this, but then realized that "classrooms" don't really have IDs. Classrooms as they are designed in the database are a set of resources, each of which has a unique ID (and a unique resource group ID). Therefore, I think this will be a bit bigger change than I was anticipating given how ingrained classrooms names are in the code.

**Comment by willgearty** [comment]
Actually, looking at the code for assigning rooms to classes, it looks like we only really need to know one of the IDs of any of the resources for a classroom:
https://github.com/learning-unlimited/ESP-Website/blob/cbba79cec28f0a8bdb5054236295750fff4adc37/esp/esp/program/models/class_.py#L677-L679
