### ISSUE TITLE
If moving a class fails, it gets unscheduled

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1396]
Arguably the better behavior is to put it back where it was (i.e. cancel the whole operation) rather than unscheduling it.  That is, "move a class from A to B" should be a transaction which either succeeds or fails, rather than two operations, "unschedule the class from A" and "schedule it in B", one of which could fail.

**Comment by willgearty** [comment]
Looks like this was fixed with the new scheduler. I just tested moving a scheduled section to a spot that I had manually scheduled another section in using `/manageclass` and the failure put the class back in its old spot.
