### ISSUE TITLE
Button to refresh scheduling data in the scheduler

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1397]
Right now the only way is to refresh the entire page, which is quite slow, and means you lose where you are.

**Comment by willgearty** [comment]
Looks like it would be pretty easy to just manually update the data based on the AJAX logs using the function here:
https://github.com/learning-unlimited/ESP-Website/blob/87c525aecaeb580f00a868c548b52018452623c5/esp/public/media/scripts/ajaxschedulingmodule/ESP/ChangelogFetcher.js#L28-L36

However, a) the scheduler already does that every 5 seconds, and b) it won't capture any changes that are done outside of the scheduler (e.g. manually scheduling a class on its manage page).

So really what we want to do here is to make a new call to `ajax_sections_details` to get the updated data from the database, then somehow update everything in-place, which seems like a much bigger task, especially for someone with limited experience with the scheduler code (e.g. me).

**Comment by willgearty** [comment]
Also, looking at the date on this issue, it looks like this was posted before @ruthie added the auto-refreshing functionality (~Dec 2014) as part of the new scheduler? So maybe this has already been fixed (at least to the extent of the original intent of @benjaminjkraft).

**Comment by willgearty** [comment]
After thinking about this again, I'm pretty sure at this point that any "refresh" button in the UI would basically do the exact same thing as just clicking the browser's "refresh" button. I'm gonna mark this as closed for now.
