### ISSUE TITLE
Lunch constraints require a cache flush to show up in the scheduler

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1399]
The scheduler doesn't notice the update otherwise.

**Comment by willgearty** [comment]
The problem is because the `cached_module_view` has no dependencies:
https://github.com/learning-unlimited/ESP-Website/blob/cdf3663db8ebdbb198686a406c5ec7b2e8d1452c/esp/esp/program/modules/handlers/jsondatamodule.py#L171-L179
