### ISSUE TITLE
Scheduler should be able to override constraints

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1401]
Right now only the manageclass page can override any constraints (e.g. lunch, double-scheduling teachers).

**Comment by willgearty** [comment]
OK, I think there's three things we would need to do to make this happen:

1. Add a checkbox to the filters/sections interface that enables/disables the override
2. When checking for the available timeslots for a class, check the status of that checkbox (or update some js variable when we check/uncheck it like with the filters) and if the override is enabled, just return all of the timeslots:
https://github.com/learning-unlimited/ESP-Website/blob/e5198eb53b618b85a2e5419c99fe2ee7ee1ec784/esp/public/media/scripts/ajaxschedulingmodule/ESP/Sections.js#L262
3. Do the same thing when submitting the schedule request to the server, so we tell the server whether or not to worry about constraints:
https://github.com/learning-unlimited/ESP-Website/blob/e5198eb53b618b85a2e5419c99fe2ee7ee1ec784/esp/public/media/scripts/ajaxschedulingmodule/ESP/ApiClient.js#L58
then use that to determine whether to run `cannotSchedule` here:
https://github.com/learning-unlimited/ESP-Website/blob/e5198eb53b618b85a2e5419c99fe2ee7ee1ec784/esp/esp/program/modules/handlers/ajaxschedulingmodule.py#L120
