### ISSUE TITLE
Find availability of a set of teachers

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1402]
Check availability will show you the availability of a single teacher; the schedule will show you the _remaining_ availability of the teachers of a class.  It would be nice to have something in one interface or the other to show you data like check availability, but intersected over the teachers of a class.

**Comment by luac** [comment]
Is this still needed, since the scheduler shows unavailable blocks differently from currently-teaching blocks?

**Comment by willgearty** [comment]
Fixed by #2714.
