### ISSUE TITLE
iPhone/Android app

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#142]
For students, it could display the catalog during the day, as well as canceled classes, etc.  It could even let them change classes online, though MIT ESP (the only group known to have been ased about this so far) thinks that it would be unfair to the large fraction of students who don't currently have smartphones; much faster for them to change classes, better odds of getting in.

For admins, it could be an online instant searchable admin binder.

**Comment by bhorowitz** [comment]
A mobile version of the website would also be great since many high school students (particularly in  under-resourced areas) nowadays might not have regular access to computers but do have a smartphone.

**Comment by kkbrum** [comment]
@willgearty  has implemented web apps (simple website pages that look nice on the phone) for students & teachers to use onsite that have relevant things for them (including catalog & class changes for students). See #2507 and #2866 for more details. 

An admin version has not been implemented, but there is an issue for it here #2672 and I've added a comment about the admin binder requests.
