### ISSUE TITLE
/manage///selectList doesn't work with zip code filters

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1434]
I'm not sure what the issue is here, or if it's in fact broader than this, but when I search for students in grades 6-12 within 50 miles of 01002 in the comm panel, I get ~1200 users, and fewer for smaller radii.  When I do the same search in the "select list of users" version, I get ~14000 users, independently of the radius I choose.

**Comment by willgearty** [comment]
This appears to now be fixed.
