### ISSUE TITLE
Show a "you're done!" in the two-phase lottery

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1437]
There's no indication that you're done, and your submissions have been saved.  A notification of some sort might be useful, although when to put it could be a difficult question.

**Comment by willgearty** [comment]
Perhaps something like #1166 would be more appropriate? That way we don't have to worry about when to show the notification?

**Comment by benjaminjkraft** [comment]
I think this has advantages too -- it lets us do things like indicate how many selections we expect people to make, so that they don't select 2 classes and click confirm and think they're done.  I think we could do both, or think harder about what we're really trying to do.

**Comment by willgearty** [comment]
Ah, then maybe #382 is relevant?

**Comment by benjaminjkraft** [comment]
Yep, that could also work!  I'm going to leave this open though so the implementer can decide what they think makes the most sense.
