### ISSUE TITLE
Deadlines page shows permissions open when they aren't

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1454]
Right now MIT has a bunch of deadlines opening in a day.  The deadlines page shows them as "Open", although with the correct times (Nov. 4 6pm to Nov. 15 2am).  I'm assuming it is only checking that they end in the future, not that they start in the past, but I haven't investigated further.  I believe this is only a display issue, but it is a very confusing one.

**Comment by joeleg** [comment]
To be sure, would this be referring to Deadline Management e.g: /manage/Splash/2013/deadlines/ ?

I am wondering if anyone could please supply some reproduction steps. I am unable to reproduce the bug and past  deadlines appear to be closed.

**Comment by benjaminjkraft** [comment]
Yeah, that's the page.  I will see if I can reproduce at some point.

**Comment by benjaminjkraft** [comment]
You just have to create a deadline which starts in the future, and either has no end date or ends in the future.  Then save it, and it will show as open, even though it's not yet open.
