### ISSUE TITLE
UI for flushing individual cached functions

### ISSUE THREAD

**Issue by luac** [learning-unlimited/ESP-Website#1462]
It is possible to flush an individual cached function in the shell (`f.delete_all()`) or even individual sets of arguments to the function (`f.delete_key_set({'self': foo})`).

We may want to expose this functionality to admins, possibly from the `/cache/view_all` page. Even if non-developers won't know how to use it by themselves, it may be useful to be able to provide instructions to "hit this button if you see this issue" in the case of a known caching bug that can't be fixed right away.

**Comment by benjaminjkraft** [comment]
Added in #1606.
