### ISSUE TITLE
Text Message for Cancelled Classes

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#147]
The top of manageclass page recently got an addition of a set of boxes for canceling classes. You can type a message to students in the boxes, then click the "Cancel class" button, and all enrolled students would be e-mailed that message about their class cancellation. 

I suggest that we add a checkbox that says, "Check here to notify all students via text message". And perhaps an extra box, since the text message will probably need to be shorter than the e-mail. Either that, or the text message can be auto-generated (something like: "X1234 (hh:00-nn:00) has just been canceled. Come to class changes at any time to add a new class."), with the text configurable in a Tag. Or auto-populate the box with the default message, and allow someone to change it before sending.

This is related to Issue #29. However, I am suggesting being able to send text messages via the manageclass pages when a class is canceled, which is distinct from being able to send text messages via the Comm Panel at any time.

**Comment by willgearty** [comment]
Fixed by #2404.
