### ISSUE TITLE
Survey is open to students who didn't register

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1474]
Right now anyone with a student account can fill out the survey for any program, whether or not they registered/attended/etc.  I'm not sure what the right behavior is, but it's probably not that.

**Comment by willgearty** [comment]
If we use "registered" students, wouldn't #1450 be an issue?

**Comment by benjaminjkraft** [comment]
Doesn't need to be -- we can just avoid ever using user profiles in surveys, as we'd only need `Record`s to implement this.

**Comment by willgearty** [comment]
That shouldn't be a problem if we are only checking if students attended, but we'd probably want to use `Student Registration`s or `Student Subject Interest`s to check if students registered, right?
