### ISSUE TITLE
Migration to clean up contactinfos

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1520]
@benjaminjkraft says: "Also, now that [#1290] is hopefully fixed, it's possible it would be worth running a migration to clean up contactinfos that are identical to more recent ones for the same program. There are amost a million in the esp.mit.edu DB, often dozens for a single user/program, and this may be a nontrivial constant factor on some of the terrible RegistrationProfile queries, which I hypothesize are a lot of studentreg load."

**Comment by willgearty** [comment]
I think this was fixed by #3131?
