### ISSUE TITLE
User search should not be case-sensitive on usernames

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1533]
This has led to difficulties in finding users if they remember their username but not the capitalization.

**Comment by tsutton** [comment]
Looks like the find_user function never looks for partial matches on usernames, only exact matches on username, then exact matches on email address, then proceeds to only check against first and last names.

Is it worth sticking partial-match-against-username in the search process somewhere?

**Comment by benjaminjkraft** [comment]
It might be useful, but it should probably be below checking first and last names.

**Comment by benjaminjkraft** [comment]
We should also check insensitively against email addresses (see #1789).
