### ISSUE TITLE
Simpler page for viewing (not modifying) the class schedule

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1543]
This is something we often want during a program -- to look up the location or time of a class, for instance.  We currently use the ajax scheduler but it's not really designed for that and we could probably make a faster page if we didn't need to be able to modify.

**Comment by kkbrum** [comment]
I think that the "room schedules" printable is sufficient for this, or there are some other printables as well that can accomplish this
