### ISSUE TITLE
Onsite grid: sort classes

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1544]
An MIT admin wrote:

> Is there a methodology for how classes for class changes are sorted? It would be nice to have all the open classes on top, then maybe walk-ins, and then full classes. And maybe to sort by category within each to be able to make it easier to tell students which ones are still open.

@sweettea notes an advantage of numerical order, which is what it currently does:

> Numerical order (so it's easy to know exactly where to find class 8900 in the list), on the assumption that the student knows the number of the class they want; but another sort might be better, indeed.

This could also be user-configurable to some extent.

**Comment by luac** [comment]
The filtering options allow you to include or exclude classes that are full, walk-ins, or by category. Are these options enough (do they need to be made more obvious?) or would sorting be more useful? I'm worried that having too many knobs may clutter the interface.

**Comment by willgearty** [comment]
I like the idea of at least being able to sort by how full a class is or category.

Also, for the record, the sorting is now based on length of sections (# of blocks):
https://github.com/learning-unlimited/ESP-Website/blob/466d6b724a79f86c3a86e97047d663ae32ca9137/esp/public/media/scripts/onsite/ajax_status.js#L1191-L1195

This helps to minimize the empty space in the table.
