### ISSUE TITLE
Allow students to drop classes onsite by themselves online

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1545]
An MIT admin wrote:

> Random interesting and arguably awful idea: make it possible for students to go online and drop classes at any point during the weekend (but they still would need to come to class changes to add anything new). This could somewhat alleviate the problem of students not being able to add seemingly full classes that end up having a low attendance, and teachers could at least check their roster a couple minutes before class and have a slightly more accurate sense if how many students to expect.

This would avoid some of the fairness issues of allowing students to add classes online, but could also cause problems if students mess up.

**Comment by willgearty** [comment]
This is implemented in #2507.
