### ISSUE TITLE
Catalog sort is weird if there are two categories with the same symbol

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1576]
It should sort by symbol then the full category name, or something else like that.  Workaround is to manually set the `catalog_sort_fields` tag.  Reported by @jerrywu64.

**Comment by jerrywu64** [comment]
The default sorting looks like it's in ~line 238 or so in esp/programs/models/class_.py, in particular the list definition of order_args. At MIT at least, the catalog_sort_fields tag already existed and overrides this sorting.
