### ISSUE TITLE
Class flags go away completely when hidden

### ISSUE THREAD

**Issue by jerrywu64** [learning-unlimited/ESP-Website#1580]
On the manage and edit pages for a class, clicking on the title (the colored bar) of the flag will hide it, and in particular it will collapse to nothing with no way to unhide it (although it comes back if you refresh). Also it's nonobvious that you can click to hide in the first place.

**Comment by benjaminjkraft** [comment]
This is only true of newly added flags.  Existing ones still appear where they first appeared (as blocks below the class title).
