### ISSUE TITLE
Scheduling checks red/green bars

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1583]
This is mostly a note to myself, suggested by @gkanwar.  It would be cool if the scheduling checks page loaded things in the background, and then if the scheduling check had no content (i.e. everything was correct) it would turn the bar green, or something like that.

**Comment by nrjean** [comment]
Note that this issue is partially implemented - current behavior is to change color based on load status (green for loaded, yellow for loading, red for failed) Future implementation to include color based on loaded content
