### ISSUE TITLE
Make a teacherreg big board

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1587]
Similar to the existing student one.  Possible stats:
- classes registered
- classes approved
- classes with X flag (probably not for all flags, maybe for all flags of which there are at least 10 or something)
- classes requesting X resource (maybe not for all resources)

We are now timestamping classes (#2013), so we can have a pretty graph.  (We may still want to backfill existing classes from email, which would also be useful for seeing if we have enough classes at some point during teacherreg.)

This might involve abstracting some of the studentreg big board functionality to save code duplication.

**Comment by willgearty** [comment]
Any progress on this?

**Comment by benjaminjkraft** [comment]
I haven't really been working on it; if someone else wants to grab the ticket feel free.

**Comment by willgearty** [comment]
Fixed by #2396.
