### ISSUE TITLE
Teacher availability search includes student accounts in results

### ISSUE THREAD

**Issue by jerrywu64** [learning-unlimited/ESP-Website#1593]
This is the thing you can access in all modules -> check teacher availability where you search for a teacher. If someone has both a teacher account and a student account, it'll show both and you'll be confused. Not sure if other types of accounts will also show up.

**Comment by mgersh** [comment]
Similarly, student check-in (the non-barcode one) also shows teachers, which can be confusing for programs that do student and teacher check-in in the same room.

**Comment by willgearty** [comment]
It looks like both of these modules use `AjaxForeignKeyNewformField`:
https://github.com/learning-unlimited/ESP-Website/blob/82d1e03c6322166f724b732893d94b54106584ae/esp/esp/program/modules/forms/onsite.py#L26-L27
and
https://github.com/learning-unlimited/ESP-Website/blob/82d1e03c6322166f724b732893d94b54106584ae/esp/esp/program/modules/handlers/checkavailabilitymodule.py#L71
https://github.com/learning-unlimited/ESP-Website/blob/c42712632733061d4ee23092829c60049eac2ccf/esp/esp/users/forms/generic_search_form.py#L5-L7

The student checkin form queries on registration profile users, and the teacher availability form queries on all ESPUsers. Both of these use the default ajax function to autocomplete the form, in this case `ESPUser.ajax_autocomplete()`:
https://github.com/learning-unlimited/ESP-Website/blob/c42712632733061d4ee23092829c60049eac2ccf/esp/esp/users/models/__init__.py#L183

There's probably two options to resolve this:

1. Use a different original model to query on. For example, for the teacher availability form, we could use `TeacherInfo.user.field`, and for the student checkin form, we could use `StudentInfo.user.field`. I'm pretty sure that will then only query users that have teacherinfos or studentinfos, respectively.
2. Make a new ajax function that filters the users to only users within a particular group (in this case, teachers or students). One function could be `ajax_autocomplete_teachers`, the other `ajax_autocomplete_students`, for example. Then make sure to include this as an argument to `AjaxForeignKeyNewformField`.

**Comment by willgearty** [comment]
Well, #1 doesn't actually work. It uses then entire model field, even if it's specified via another model.
