### ISSUE TITLE
manage.py update should touch esp.wsgi

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1599]
It's a quick enough thing to do, that I think we should do it to save some steps, even though it's not always necessary on dev servers.  (Although due to some quirks of our setup it actually occasionally still is necessary to touch `esp.wsgi` even on a dev server.)

**Comment by willgearty** [comment]
My implementation in #3021 wasn't working on the live server (but did seem to work on dev servers), so I'm reopening this for now.

**Comment by willgearty** [comment]
Still not able to get something that works on the live server. The problem I'm running into is that we always run `sudo -u www-data python esp/manage.py update` on the live server, which then causes any `os.system()` call that I put in the update function to only have www-data permissions, which often doesn't include write permissions for esp.wsgi
