### ISSUE TITLE
Put course number in subject line of all emails to all students or all teachers of a class

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#1600]
Whenever an email is sent to all students or teachers of a class (using the xxx-students@ or xxx-teachers@ alias), and a copy is sent to the admin email of the program, put the class number in the subject line.  Among other things, this makes it easier to figure out which emails are/are not getting sent (given the email issues we've had in the past) when a teacher asks wondering whether their students received an email they sent.

**Comment by willgearty** [comment]
Another reason this could be valuable is that, when students send emails to teacher lists, we also get a copy in our admin email. If these emails contain questions, we may inadvertently reply to them thinking they are directly to us, rather than realizing we are just bcc'd on the email.

**Comment by willgearty** [comment]
I think we'd want to add a property (e.g. `self.cls = cls.emailcode`) in each of the handlers (e.g. https://github.com/learning-unlimited/ESP-Website/blob/32ed5e9816c99cdbe5f8555765e25b3d40cd2697/esp/esp/dbmail/receivers/classlist.py), then call that property (if it exists) like we do for the subject prefix:
https://github.com/learning-unlimited/ESP-Website/blob/5e97858138fa6a6a39c8ee0fce60b5753535beae/esp/mailgates/mailgate.py#L90-L94
