### ISSUE TITLE
esint.sty not included in in-line latex generation

### ISSUE THREAD

**Issue by bhorowitz** [learning-unlimited/ESP-Website#1607]
Website throws math generation error when attempting to render latex from esint.sty due to not importing package. Package contains lots of integrals of general use (surface integrals, etc.) and should be included if possible.

**Comment by bhorowitz** [comment]
I supposedly put in a pull request for the extra few letters... I might have done it wrong cause it is the first time I ever tried to submit a pull request to someone else repository.

**Comment by benjaminjkraft** [comment]
Fixed by #1608.
