### ISSUE TITLE
Onsite main page shows modules that aren't enabled

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1616]
It seems to be static, so it can link to things that don't exist (such as the grid).

**Comment by luac** [comment]
Alternatively, maybe module views that aren't enabled should display a message to admins that says to enable the relevant module.

**Comment by benjaminjkraft** [comment]
Ooh, ++.  That might also make it possible to make module view routing more static, since whether the module is enabled would change what is displayed, but not what module gets the call.

**Comment by willgearty** [comment]
It looks like only the grid and the scrolling class list are static, everything else is populated based on the onsite modules that are enabled;
https://github.com/learning-unlimited/ESP-Website/blob/cdf3663db8ebdbb198686a406c5ec7b2e8d1452c/esp/templates/program/modules/onsitecore/mainpage.html#L24-L36

**Comment by willgearty** [comment]
One potential fix for this is to override the default `makeLink` method with a custom one for [onsiteclasslist.py](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/modules/handlers/onsiteclasslist.py)
