### ISSUE TITLE
Class changes grid: option to toggle whether to set Attended records

### ISSUE THREAD

**Issue by luanths** [learning-unlimited/ESP-Website#1628]
Currently, the onsite class changes interface automatically marks students as attended, reasoning being that if they're at onsite class changes, they have to have attended the program.

But sometimes, the onsite interfaces are used before the program (e.g. to remove students from classes when they cancel their registration), and this is the wrong thing to do.

Bonus: some time-based way to set the default for this setting, so that it defaults to false before the program but true during the program, so that admins don't have to know to set it manually.

**Comment by jmoldow** [comment]
This feature would be good for non-grid class changes as well.
