### ISSUE TITLE
Add a way to clear a student's schedule

### ISSUE THREAD

**Issue by luac** [learning-unlimited/ESP-Website#1639]
Either a page for students to do it themselves, or a button for admins to do it.

Alternatively, maybe a deadline setting to let students drop classes up until the program.

**Comment by jmoldow** [comment]
Doesn't the cancel registration button allow students / morphed admins to do this?

The deadline for dropping individual classes sounds like a good idea.

**Comment by luac** [comment]
This is a duplicate of #640.
