### ISSUE TITLE
Onsite grid disagrees with other notions of when a class is full

### ISSUE THREAD

**Issue by luanths** [learning-unlimited/ESP-Website#1640]
This is particularly the case when using the class cap multiplier setting, in which case the student-facing catalog reports higher class capacities than the onsite class change grid.

Supposedly, the reason the onsite grid doesn't use the class cap multiplier is that onsite has a better idea of whether a class is full based on the number of students that actually checked in. However, the grid still uses the number enrolled rather than the number checked in to determine if a class is full. We could change this so that it uses the checked-in number, but that number is not necessarily accurate because it depends on students being checked in as attended on the website.

Another option would be to do something in between, such as using `capacity + (capacity - attended) * (multiplier - 1)` as the real class capacity (i.e. use the multiplier, but only for the spots that aren't taken by a confirmed attended student).

A third option is to disable the class cap multiplier while a program is in progress (I'm not sure if there is a good way to define "in progress"; maybe with deadlines?)

Whichever solution to this problem should address discrepancies between the onsite grid, the various other onsite interfaces (like the open class lists), and the student-facing catalog, so that students don't see that a class is open in the catalog and then get disappointed when it is considered full at onsite class changes.

**Comment by luac** [comment]
#834 is an instance of this.

**Comment by luac** [comment]
Notes:
- section.capacity is the canonical number that is displayed in the catalog.
- The onsite grid manually calculates each section's capacity from the class's size_max and the room's size. It doesn't apply the multiplier and it doesn't apply section.max_class_capacity if that exists.
- The onsite open class list uses section.isFull to determine whether to show a class, which agrees with the catalog.

**Comment by luac** [comment]
Suggestion: make the onsite grid agree with everything else, and (if desired) add an option to change what everything else displays based on the number of attended students.

**Comment by willgearty** [comment]
Fixed by https://github.com/learning-unlimited/ESP-Website/pull/2998
