### ISSUE TITLE
Easier way for admins to access StudentInfo and TeacherInfo

### ISSUE THREAD

**Issue by luanths** [learning-unlimited/ESP-Website#1643]
Requested at MIT Spark wrap-up: "Should have easier access to StudentInfo and TeacherInfo, maybe from user page and also from the ESP User page on the admin Panel"

**Comment by jmoldow** [comment]
I don't understand this. Isn't all the StudentInfo and TeacherInfo already available in the user search page? What else is there to do?

I don't think we can / should put it on the ESP User page of the admin panel.
