### ISSUE TITLE
Nametags: fit names on one line

### ISSUE THREAD

**Issue by luanthe** [learning-unlimited/ESP-Website#1645]
Requested at MIT Spark wrap-up: "Should maybe have an option for nametag generation to shrink names so that they fit on one line (it generally looks weird when they wrap)"

**Comment by willgearty** [comment]
Are there any built-in latex ways to do this?

**Comment by benjaminjkraft** [comment]
Nametags don't use LaTeX currently, as I recall.

**Comment by willgearty** [comment]
Oh, must have gotten mixed up with schedules, my bad.
So then something like this might work: http://stackoverflow.com/questions/18229230/dynamically-changing-the-size-of-font-size-based-on-text-length-using-css-and-ht
