### ISSUE TITLE
Class appear full to teachers before student reg is open

### ISSUE THREAD

**Issue by luac** [learning-unlimited/ESP-Website#1647]
Reported at MIT Spark wrap-up.

**Comment by luac** [comment]
I believe this is specifically when they aren't assigned a room, so are considered to have 0 capacity?

**Comment by benjaminjkraft** [comment]
Yep.

**Comment by luac** [comment]
To me the obvious fix seems to be "don't consider it full if its capacity is 0", is there anything wrong with this?

**Comment by jerrywu64** [comment]
I'm concerned that somewhere there might be a mechanism which specifically
sets capacities to zero to make the class full?

**Comment by luac** [comment]
Hmm, right, I guess the alternative to full would be open, which would mean that students would be able to register for it, which we don't want regardless of why its capacity is zero. So instead we want to display a different message if it's 0/0.

**Comment by jerrywu64** [comment]
Can we just check to see if it's assigned to a room and have a different message if it's not assigned to a room?
