### ISSUE TITLE
Let teachers see how many of their students have checked in

### ISSUE THREAD

**Issue by luanths** [learning-unlimited/ESP-Website#1650]
Requested at MIT Spark: "Not sure whether this would be a good idea or not, but would it be possible to let teachers see how many of their students have checked in (like on the class changes grid) so they have a somewhat better sense of how many students they have."

**Comment by willgearty** [comment]
This is now possible on the teacher attendance page (https://github.com/learning-unlimited/ESP-Website/pull/2868)
