### ISSUE TITLE
Teacher check-in fails on accounts that are Administrators but not Teachers

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1658]
It won't let you check in a teacher who isn't a Teacher. Instead it gives an error message that they're not a teacher for this program. We probably don't want to remove the ability for Administrator accounts to go through teacher reg, so ideally teacher check-in should work for them too to be consistent. Student check-in probably has the same issue.

This was discovered at Northeastern, where some admins had accounts that were only Administrators for some reason.

**Comment by jerrywu64** [comment]
When would we want an admin account to be checked in as a student?

I note that onsitecheckinmodule.rapidcheckin() explicitly checks to make sure the student isn't also a teacher. I don't know the exact rationale for this but I also don't see a reasonable use case in which this would be bad. Presumably if we insist upon testing student check-in, for example, we should use a student non-admin account. Unless there are plans to allow admins to register as students and take classes?

**Comment by mgersh** [comment]
On second thought, yeah, I don't know why we would want to check in a non-student as a student, so that one is probably fine.

**Comment by mgersh** [comment]
Fixed in #1709
