### ISSUE TITLE
Show is_superuser field in ESPUser admin panel

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1675]
The ESPUser admin panel shows most of the fields, including is_active and is_staff, but is missing is_superuser. That field should also be included.

This makes it hard to add/remove administrative permissions. If someone doesn't know about the makeadmin page, and tries to give permissions via the admin panel, they won't know that the user doesn't have is_superuser, and it'll look like the account was successfully given admin privileges, when it is actually missing something important (without is_superuser, you can't see anything on the admin panel). And when removing an admin, with the is_superuser field missing, it's not possible to fully revoke admin privileges, but again this won't be apparent to the user.

**Comment by mgersh** [comment]
Fixed in #1708
