### ISSUE TITLE
Helpful content in quasi-static content on /manage/programs/

### ISSUE THREAD

**Issue by bhorowitz** [learning-unlimited/ESP-Website#1676]
There are many issues that could probably be solved by inclusion of a default entry in the quasi-static content in /manage/programs/. Navigating the admin pages wouldn't generally ever lead one to these pages, so it might make sense to have links available in /manage/programs/

See below:

---

Useful management pages:
- [Manage QSDs](/manage/pages/)
- [Flush cache](/manage/flushcache/)
- [Make admin](/myesp/makeadmin/)
- [Custom forms](/customforms/)
- [LU website guide](https://wiki.learningu.org/How_to_use_the_website)
- [Feature request instructions](https://wiki.learningu.org/How_to_use_the_website#Feature_Requests)

**Comment by willgearty** [comment]
Fixed by #2534.
