### ISSUE TITLE
Text on new registration page is very MIT-specific

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1679]
It's editable QSD, but editing it is tricky since it's not viewable by logged-in users.  See [esp/templates/registration/newuser_phase1.html](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/templates/registration/newuser_phase1.html) line 59.

**Comment by mgersh** [comment]
There's also esp/templates/registration/newuser.html, which is almost the same thing.

**Comment by willgearty** [comment]
Fixed by #2534.
