### ISSUE TITLE
Caching of "Students who attended" in dashboard (JSONDataModule.stats doesn't depend on Record)

### ISSUE THREAD

**Issue by pteromys** [learning-unlimited/ESP-Website#1684]
UChicago admins had a little moment of sadness when the dashboard claimed only 13 students had checked in. Turns out there were 30 at the time, but `JSONDataModule.stats` doesn't update when new `Record`s are created.

To make it less expensive to calculate, we could cache functions like `StudentRegCore.students` and set them up in a tree of `depend_on_cache`s.

**Comment by mgersh** [comment]
Duplicate of lots of things. Keeping #827 and closing the rest.
