### ISSUE TITLE
Per-program onsite print script for shell-averse or non-Linux users

### ISSUE THREAD

**Issue by pteromys** [learning-unlimited/ESP-Website#1685]
It would be cool if one could download a program-specific `poll_schedules.sh` for each program.

This might not actually be worth the maintenance burden. And there remain some other portability issues:

* Syntax of `mktemp` differs slightly between OS X and Linux
* Retrieving printer names on OS X takes more than a few seconds
* Sometimes, everybody is on Windows

**Comment by luac** [comment]
Is there a use case for this that is not covered by the web-based printschedules (https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/modules/handlers/onsiteprintschedules.py#L61)?

**Comment by pteromys** [comment]
No, not that I can see. Our most compelling reason for continuing to have used the shell script version is that it prints postscript instead of bitmaps. (Second most compelling reason is not having to remind volunteers to go fix Firefox afterwards, but this isn't a problem I've actually experienced.)

**Comment by benjaminjkraft** [comment]
Going to open the bitmaps thing as a new issue.
