### ISSUE TITLE
Ajax scheduler breaks on four-digit timeblock id

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1698]
It's caused by a bit of custom SQL in the json data module which assumes that all ids are three digits. MIT's database just hit 1000, and Yale will get there before the end of fall and possibly a lot sooner. See schedule_assignments(), https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/modules/handlers/jsondatamodule.py#L138

The quick fix is adding a fourth '9' in the obvious place, and it works even on programs with a mix of three- and four-digit ids. It's probably a good idea to just do that now for at least MIT and Yale, but really we should find some better way of writing this.

**Comment by benjaminjkraft** [comment]
Looks like converting the `to_char` to a `cast` should probably work.

On Mon, Jun 1, 2015 at 12:54 PM, Miriam Gershenson <notifications@github.com
