### ISSUE TITLE
Automatic unsubscribe link on comm panel emails

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1719]
It would be good to have an unsubscribe/deactivate link at the bottom of all comm panel emails; while we usually put it in manually, we sometimes forget.  Ideally, rather than just linking to /myesp/disableaccount, we would in fact have per-user generated links that would not require logging in, since people have trouble remembering their username and password and such.  This wouldn't work for mailman lists, of course, but it would at least make it a bit easier for people to unsubscribe (and therefore make us less likely to get marked as spam).

**Comment by willgearty** [comment]
+1

**Comment by benjaminjkraft** [comment]
I think there's also a header we can set that will cause some mail clients to automatically unsubscribe people when they click "mark as spam".

**Comment by willgearty** [comment]
http://www.grokcode.com/819/one-click-unsubscribes-for-django-apps/

**Comment by willgearty** [comment]
We could also add an unsubscribe header:
https://github.com/theskumar/django-unsubscribe/blob/master/unsubscribe/mail.py
https://sendgrid.com/blog/list-unsubscribe/

**Comment by milescalabresi** [comment]
This is one of Google/Yahoo's new requirements, so we should try to do this as a hotfix ASAP (but no later than April 1st).

**Comment by willgearty** [comment]
Would just adding a mailto List-Unsubscribe header be sufficient? (see here: https://docs.sendgrid.com/ui/sending-email/list-unsubscribe#email-unsubscribe-mailto) If so, we could just set this header to the chapter's director email address or some other chapter-specific email address. Would certainly be easier than implementing auto-unsubscribe (although I can of course still look into the steps outline here: https://www.grokcode.com/819/one-click-unsubscribes-for-django-apps/).

**Comment by milescalabresi** [comment]
Yes, I think it would be
