### ISSUE TITLE
Customize statement descriptor for credit card charges on Stripe

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#1725]
Currently, our credit card charges show up as "Learning Unlimited" on the credit card statement.  Some people don't recognize this name, and recently we had a disputed credit card payment because of this.

It would be better to customize the descriptor per program (e.g. "Yale Splash") which is something that students and their parents are more likely to recognize.  This can be done as described here:

https://support.stripe.com/questions/when-i-charge-a-customer-what-will-they-see-on-their-card-statements

"If you want to set a per-charge (dynamic) descriptor, you can do so by utilising the statement_descriptor parameter, which is available when creating a charge and on a plan."

**Comment by bhorowitz** [comment]
I think it is just a one-line addition, it is in pull request #1727.
