### ISSUE TITLE
Include bar codes by default on student schedules

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#173]
Stanford asked for this feature, though they may not have known that it's already been implemented and MIT has used it a few times.  I'm not sure anyone will be bothered by having barcodes on the schedules that they aren't using.

It was also requested that the barcodes show up in other places like the confirmation receipt, something that the student prints out.

**Comment by kkbrum** [comment]
Barcodes are on schedules as of #2854. If someone has a current need for barcodes on confirmation receipts they can reopen this issue/make a new one!
