### ISSUE TITLE
Teacher bio more prominent and easy to find

### ISSUE THREAD

**Issue by corinnherrick** [learning-unlimited/ESP-Website#1730]
Teacher bios are a prominent google result for many teachers. It would be nice if it were easier to find.

At minimum, the teacher bio should be available from the [profile page](https://esp.mit.edu/myesp/accountmanage.html) and ideally from the edit profile page as well (since teachers are periodically shown this page when registering classes).

**Comment by mgersh** [comment]
Agreed on accountmanage.html, it should be linked there.

For programs, we have the Teacher Bio Update module, which MIT ESP has always enabled for Splarks. (HSSP stopped using it after 2013, I don't know why.) Half of last Splash's teachers and a third of last Spark's teachers used it. Making it required (per-site or per-program from the admin panel) would make it more obvious.

**Comment by benjaminjkraft** [comment]
I think if we make it required, it may force teachers to write nonzero text
for their bio?  I'm not entirely sure, but we should be careful with that,
or change the required logic to make them just need to see the page.

On Tue, Jul 28, 2015 at 9:42 PM, Miriam Gershenson <notifications@github.com

**Comment by mgersh** [comment]
Ah, yeah, you're right, just submitting it doesn't mark it completed, I had it confused with the custom form modules which do work that way.
