### ISSUE TITLE
Lingering misuses of getGrade

### ISSUE THREAD

**Issue by luanthe** [learning-unlimited/ESP-Website#1747]
Discovered while documenting #1502: several views on the website, including printables, teacher view students, and admin/teacher view apps (for the old student app module) still call `ESPUser.getGrade` without a program argument, which means that you get the student's current grade rather than their grade at the time of the program.

This can be seen if you go to an old program and print schedules, or click "View Students" on an old class.

**Comment by willgearty** [comment]
`ESPUser.getGrade` is used in a lot of templates, so we'll probably need to make a template tag (e.g. `getGradeForProg:prog.id`) that can get the grade for a specific program within a template.
