### ISSUE TITLE
pip install --use-mirrors has been deprecated

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1758]
When Travis runs, ``pip install`` issues this warning:

> DEPRECATION: --use-mirrors has been deprecated and will be removed in the future. Explicit uses of --index-url and/or --extra-index-url is suggested.

Before pip completely removes this flag and Travis upgrades to said version, we should either stop using the flag, or switch to using one of the other suggested flags (which require an explicit mirror server to point to).

**Comment by benjaminjkraft** [comment]
Fixed in #2151, thanks @mgersh!
