### ISSUE TITLE
Migrate to container-based Travis

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1770]
Cf. http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by benjaminjkraft** [comment]
Note that this includes build caching, so we should be able to have tests run a good deal faster.

**Comment by willgearty** [comment]
https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com
and
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by willgearty** [comment]
OK, I think this is all set!
