### ISSUE TITLE
Class search for classes with "any flag" returns all classes, including those with no flags

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1785]
The URL generated is https://esp.mit.edu/manage/Splash/2015/classsearch?query=%7B%22filter%22%3A%22any_flag%22%2C%22negated%22%3Afalse%2C%22values%22%3A%5Bnull%2Cnull%5D%7D

**Comment by benjaminjkraft** [comment]
Looks like this is an issue only when you set neither a created time nor a modified time.  (So a workaround is to always specify "created before now".)
