### ISSUE TITLE
User search and email capitalization

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#1789]
It appears that the user search only does *exact* email matches.
Would there be any way to allow for case differences?
Perhaps make both entirely lowercase and match them?
I've had a few cases where emails from the user list their email address with one capitalization and then their email address on the website is listed with different capitalization.

**Comment by benjaminjkraft** [comment]
Partial duplicate of #1533; I'll add a mention of email addresses there as well since I assume they're easy to fix at the same time.
