### ISSUE TITLE
"Hosed teachers" scheduling check

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1790]
By "hosed teachers", I mean teachers who will be teaching for all or almost all of the times they're available. Somebody asked me today if it's a scheduling check, and I thought that sounded like a good idea. It has a somewhat different purpose from the others but would work well in the same format.

**Comment by jerrywu64** [comment]
What would we actually use this for, aside from amusement +/- recognition? (Or is that the entire purpose (which is admittedly a reasonable purpose)?) I don't think we can actually act on this information.

**Comment by mgersh** [comment]
We sometimes preschedule these teachers and/or email them before to scheduling to ask if they can add more hours.

**Comment by benjaminjkraft** [comment]
Seems like a useful idea to me, and fairly easy to implement.
