### ISSUE TITLE
Lunch constraints form will add lunch blocks, but won't remove

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1798]
Or something like that. I worked around it by manually deleting all the lunch classes and then resubmitting the form with only the lunches I wanted.

**Comment by milescalabresi** [comment]
Yeah, two chapters now have emailed either me or websupport about this. I think there is another (equally convoluted) way to remove them via /admin/, but this should be fixed.

For more details:
> if you uncheck both the lunch blocks on the lunch constraints page and uncheck the boxes and try to save, it says the first field is required. Thus as soon as you use that page at all, the option of having one lunch block that kids don't have to sign up for is eliminated.

**Comment by willgearty** [comment]
Should the form just delete any old constraints and make new ones each time you submit it?
