### ISSUE TITLE
Comm panel "teachers who have taught for a previous program" doesn't work

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1810]
Reported by MIT:

> In the E-mail pane, when I go to select all teachers teaching an approved class, I get a reasonable number -- something like 440.
> 
> When I combine that with "AND NOT teachers who have taught for a previous program," I get something like 230.
> 
> But when I combine that with "AND teachers who have taught for a previous program," I get 0.

**Comment by benjaminjkraft** [comment]
I'm guessing that the issue is with the way we combine Q objects meaning that for "taught for a previous program" you essentially end up filtering for "teachers with a class in this program that isn't in this program", rather than "teachers with a class in this program and a class that isn't in this program".

**Comment by milescalabresi** [comment]
Here is probably a relevant snippet: https://github.com/learning-unlimited/ESP-Website/blob/stable-release-8/esp/esp/program/modules/handlers/teacherclassregmodule.py#L128

**Comment by milescalabresi** [comment]
Related to #1655?

**Comment by benjaminjkraft** [comment]
Slightly different issue, I think.  #1655 it actually generates a query with incorrect logic (i.e. an AND instead of an OR); in this issue the query is logically correct in the sense that it puts the AND/NOT in the right place, but because of the way it resolves related lookups (via combining Q objects, rather than QuerySets, so that they have to go in a single `filter` clause) it's still wrong.

**Comment by benjaminjkraft** [comment]
Oh, I think this *is* an instance of #956.
