### ISSUE TITLE
Add ?next= argument to logout page

### ISSUE THREAD

**Issue by wnavarre** [learning-unlimited/ESP-Website#1822]
Implementation
============

The login page already has this. This URL works, for example: 

 https://esp.mit.edu/myesp/login/?next=/learn/Splash/student.html

Motivation
========

I want to be able to make a link like this: 

\<a href="https://esp.mit.edu/myesp/signout/?next=/myesp/login">Log in as a different user\</a>

**Comment by btidor** [comment]
It looks like this feature was added in GH-766 / 257c8b6, but the parameter is called `redirect`, not `next`.
