### ISSUE TITLE
Single permission to open everything needed for the lottery

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1824]
To allow students to register for the lottery, you need to open a bunch of different deadlines, but you can't just open them all because that would allow students to register directly for classes too.  It would be nice if there were a single permission that would open all the others.  The tricky bit is that different programs may want different things open.

**Comment by mgersh** [comment]
I'm pretty sure "all student deadlines" works just fine, see email.
