### ISSUE TITLE
Scheduling perfectly back-to-back timeblocks messes up the scheduler

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1829]
If you have timeblocks scheduled exactly back-to-back (e.g. 12:00-1:00 and 1:00-2:00) it will cause classes that are the same length as a single timeblock to extend into the next block.  This was reported by @bhorowitz on Berkeley's site a while ago.  No idea if it also applies to ajax-spike, but I'd guess it does.

**Comment by willgearty** [comment]
Fixed by #3381.
