### ISSUE TITLE
Install script work with github forks

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#184]
It'd be nice if the install script could take as an argument the URL of the repository (for example, a github fork of the master repository) to check out.

It'd be even nicer if it offered to create a fork for you.  This might be hard, but at least it could pop open a Web browser to the correct URL and print instructions on what to do.

**Comment by benjaminjkraft** [comment]
I think at this point everyone works from the @learning-unlimited/esp-website repo anyway, and if you want to create a fork it's a single command with [hub](https://github.com/github/hub).
