### ISSUE TITLE
Lottery enrollment doesn't invalidate caches

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1840]
The lottery script bulk-enrolls students. This process apparently doesn't invalidate caches that depend on this data. As one example, the `enrolled_students` `DerivedField` on `ClassSection` remains 0, and requires a cache flush to fix.

**Comment by benjaminjkraft** [comment]
Flushing the cache may not fix this, because it's actually cached in the
DB, I thought.

**Comment by jmoldow** [comment]
I flushed the ``esp.program.models.class_.ClassSection.count_enrolled_students(self)``, and it fixed the problem.

Apparently cache flushes register recalculations of the fields (I'm not sure if this happens immediately, or the next time the fields are accessed). According to ``derivedfield.py``:

>    The intent of this field is to push caching out to the database:
>    It is sometimes useful to run queries that filter against calculated
>    fields or fields that can only be found across an expensive series
>    of joins.  For example, sorting classes by their starting times
>    or by the number of students in them.  These values can often be
>    calculated in SQL by a crazy SQL query; but such queries can be quite
>    expensive.  So, let's create a field that stores these calculated
>    values, and that automatically recalculates them when they
>    change.

...

>    Now, note that I specified an argument "counter_fn".  counter_fn must be
>    a function that is cached using the caching API (esp.cache.argcache).
>    This code is an extension of the caching API: When that API flushes the
>    cache in memcached, this code catches that event and also updates the value
>    stored in the database.

**Comment by luac** [comment]
Yeah, it gets recalculated if you flush it by triggering argcache (which I think includes /manage/flush_cache), but not if you clear memcached manually. If I remember, it recalculates all dependent fields immediately, so you don't want to have a DerivedField that depends on something that could potentially hit a whole bunch of them at once.

**Comment by jmoldow** [comment]
This is a specific instance of #1661.
