### ISSUE TITLE
Images and Theme folders not symlinked with defaults on older sites

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#1841]
As described in the email thread.... The newer sites have symlinked images/ and styles/ to default_images/ and default_styles/, so they get all new/updated files. However, with Yale and some older sites, which were set up when we still used Dropbox, have full copies of esp/public/media/, possibly with modifications, and don't automatically get updated. Looks like we forgot to account for this for at least the last two stable releases.

The easiest things to do would either be change these sites over to using symlinks, or to copy the repository's versions of these files to the custom location. This would work fine for most sites, but I'd be afraid to do it for Stanford and Chicago and any other sites not using generic templates. For those, we should probably just copy over new files, and for modified files, we can either (a) figure out which files haven't been customized, and copy over the correct versions; or (b) not fix anything.

**Comment by jmoldow** [comment]
See also #880.

Though that is something that we'd change in the code and then eventually go out during some stable release, whereas this is something we can fix on the live sites now.

**Comment by milescalabresi** [comment]
Edited discussion from SR10 deployment: a nicer eventual fix would be to put commonly customized/overridden things (logo.png, bubbles.png, favicon.ico, etc.) in a separate folder that does not get clobbered by the theme. That is, have some sort of layering setup, where there is some set of chapter overrides that are stored separately but take precedence over the defaults.

**Comment by willgearty** [comment]
Ugh, just ran into this updating some stuff on Yale's site. What a pain in the butt. I'm hoping we can figure out a solution for SR11.

**Comment by willgearty** [comment]
Sounds like we will be making this happen when we transition to AWS (right, @milescalabresi?)

**Comment by milescalabresi** [comment]
We can. I don't think it would happen by default, so poke appreciated

**Comment by kkbrum** [comment]
Linking the folders on old sites has been completed!
