### ISSUE TITLE
letterhead.pdf should be optional

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1878]
Right now, compilation of any templates that include letter_base.tex (completion_certificate.tex and refund_receipt.tex) will fail, unless the site has uploaded a latex_media/letterhead.pdf file.

If that file doesn't exist, the templates should not include the line

```
\ULCornerWallPaper{1}{% templatetag openbrace %}{{ MEDIA_ROOT }}latex_media/letterhead.pdf}
```

Either that, or a blank letterhead.pdf should be checked into the repo.

**Comment by willgearty** [comment]
A blank letterhead.pdf was added in eb404f5.
