### ISSUE TITLE
Userview: "view profile for [dropdown] program"

### ISSUE THREAD

**Issue by luanthe** [learning-unlimited/ESP-Website#1880]
There is no plan to make userview the One Page to Rule Them All, but if there were, it would be useful to be able to use the sidebar shortcuts for programs other than the one for which the user last updated their profile.

Possible implementation: a dropdown at the top of the page where you can select a program (that the user has a registration profile for), which will reload the page adding a GET parameter that tells it to use the student's last profile for that program.

**Comment by betaveros** [comment]
Do we actually need/want the profile and the program shortcuts to come from the same program? After making the commit above referencing this issue I think those two things are pretty independent, so we could make the page display shortcuts for a different program but still display the same most–up-to-date profile information. Is there a common use case for viewing old profile information?

**Comment by betaveros** [comment]
Also, if we want to fix the original rare case described in #2102 with this, we'll need to come up with a list of programs larger than the list of programs the user has a profile for. Might as well allow all programs?
