### ISSUE TITLE
Lingering "V/Flags/[...]" in addclass_logic

### ISSUE THREAD

**Issue by luac** [learning-unlimited/ESP-Website#1882]
https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/modules/handlers/studentclassregmodule.py#L358

I'm not sure what this is for, but it looks like addclass?prereg_verb=XXX is supposed to have worked in the past. I don't know why or how or if we want it back, but if not, let's delete this code.

**Comment by benjaminjkraft** [comment]
Fixed in #2133.
