### ISSUE TITLE
Volunteer CSV generation fails on non-ASCII names

### ISSUE THREAD

**Issue by luanthe** [learning-unlimited/ESP-Website#1893]
See https://sentry.mit.edu/share/group/392e313135/

**Comment by benjaminjkraft** [comment]
I think that's actually the wrong traceback, incidentally -- that's non-ASCII in QSD URLs because I was trying to be funny.

**Comment by luac** [comment]
Yeah, I realized that and corrected the link.

**Comment by jerrywu64** [comment]
Bump?

**Comment by benjaminjkraft** [comment]
@jerrywu64 If you find the stacktrace these are usually not hard to fix -- just need to `.encode()` instead of `str()` or whatever.  LMK if you have trouble with that and I or others can perhaps help!
