### ISSUE TITLE
Search by parent email

### ISSUE THREAD

**Issue by btidor** [learning-unlimited/ESP-Website#1903]
User search should allow searching for students by a parent's email address.

**Comment by willgearty** [comment]
The commit by @btidor doesn't seem to work as desired (at least on the Stanford site), possibly because parent contact infos aren't being associated with the proper user ids.

**Comment by willgearty** [comment]
In fact, after looking at the code a bit, we never assign a user object to [emergency](https://github.com/learning-unlimited/ESP-Website/blob/9147b7912921642812fa3fc4bfdbca35eaac9665/esp/esp/web/views/myesp.py#L167) or [guardian](https://github.com/learning-unlimited/ESP-Website/blob/9147b7912921642812fa3fc4bfdbca35eaac9665/esp/esp/web/views/myesp.py#L174) contact infos.
