### ISSUE TITLE
Can't see responses to numeric survey questions

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1911]
I went to look at my class reviews for MIT Splash (https://esp.mit.edu/teach/Splash/2015/survey/review), and the page is incorrect. I can see responses to open ended questions for all 3 of my classes, but I can only see the responses to the numeric questions for one of the classes (EDIT: I can only see numeric response questions, for classes that have no responses to numeric questions).

It seems to be a bug in the code, not in the survey itself, because the results are messed up for old Splashes as well, even though I know they used to be correct (e.g. https://esp.mit.edu/teach/Splash/2013/survey/review).

It also seems to be a new bug, because I don't see this problem looking at Stanford Splash (which is on stable-release-6) (https://stanfordesp.org/teach/Splash/2014_Fall/survey/review).

**Comment by mgersh** [comment]
Do your classes that show the responses to the numeric questions have any responses yet? In my case, it's only the classes with no responses where they show up, and from what I've figured out so far that might be for a reason but I want to check.

**Comment by jmoldow** [comment]
For the class that is showing the numeric questions, I currently have no responses (for both the numeric and non-numeric questions).

**Comment by mgersh** [comment]
Okay, I'm pretty sure the problem is in https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/survey/templatetags/survey.py#L110, which does a bunch of importing settings that could easily have broken in 1.8.

**Comment by jmoldow** [comment]
For Splash 2015, the other two classes do have responses.

But for Splash 2013, I have two classes without any responses, but only one of them shows the numeric questions.

**Comment by mgersh** [comment]
For what it's worth, this caused an error rather than missing data on my dev server, and I understand what was causing the error: we have no TEMPLATE_DIRS setting anymore. Trying to replicate what the code is doing in a shell on the server also caused that error. I have no idea why were seeing missing data instead.
