### ISSUE TITLE
Run linters in a separate Travis build

### ISSUE THREAD

**Issue by btidor** [learning-unlimited/ESP-Website#1951]
From @jmoldow on #1948:

> Rather than running [the linter] in the same job as the unit tests, can we run it in a separate job? That way Travis will report separate results for linting and unit tests.
>
> Our Travis CI file could have
>  
>     matrix:
>       include:
>         - env: ENV="flake8"
>         - env: ENV="test"
> And then we could have the script invoke either unit tests or linting, depending on the value. Or, if we were okay with introducing another dependency, we could use tox to do that for us.
> 
> Thoughts on this?

**Comment by benjaminjkraft** [comment]
I think this would also make it easier to tell whether it was tests or lint that failed without clicking through.

**Comment by luac** [comment]
++
