### ISSUE TITLE
manage.py command to clear the cache

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1952]
The "flush cache" page does a bit more than just flush memcache.  When the site is slow and the page won't load, it would be useful to have a way to do this in the shell.  Might help with #1661.

**Comment by willgearty** [comment]
We'd also want to then include the command in the `update` command instead of the memcache flush we're currently doing (as of https://github.com/learning-unlimited/ESP-Website/pull/3021)
