### ISSUE TITLE
Something weird going on with cache_inclusion_tag in Chicago's branch

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#1960]
Chicago's current branch has a failing test, and I suspect it's related to a use of cache_inclusion_tag because none of their other changes seems at all possibly related. For reference, their changes are in this commit: https://github.com/learning-unlimited/ESP-Website/commit/392f37face73abfd7ef567b3daa6538b3fe47d66

The same failure apparently happened in chicago-1.6 (their sr6 branch), so this isn't the cache_inclusion_tag rewrite's fault.

```
FAIL: test_caches_loaded (esp.cache.tests.CacheTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/learning-unlimited/ESP-Website/esp/esp/cache/tests.py", line 114, in test_caches_loaded
    self.assertEqual(queued.pending_lookups, {})
AssertionError: {<function <lambda> at 0x7fd3aba50938>: [<function resolve_depend_on_row at 0x7f [truncated]... != {}
- {<function <lambda> at 0x7fd3aba50938>: [<function resolve_depend_on_row at 0x7fd3ab7ca398>]}
+ {}
```

**Comment by luac** [comment]
Doesn't esp/esp/cache/tests.py not exist anymore?

**Comment by luac** [comment]
I suspect this is just the depend_on_row that got added locally; is that file imported by the cache loader?

**Comment by mgersh** [comment]
sr7 was branched off before the switch to external argcache, so everything is still in esp/cache/ there.

The file is imported in esp/utils/inclusion_tags.py along with all the others, which is imported by the cache loader. The individual inclusion tag wasn't imported, but I fixed that just in case it mattered for anything and it didn't help.

**Comment by luac** [comment]
Oh. It turns out that the cache loader is just wrong (or that test is, take your pick) when there are old-style "lambda: Model" dependencies. It doesn't clear out the pending_lookups dictionary at the end, but the test expects it to be empty.

**Comment by luac** [comment]
I think I meant to have it clear out that dictionary, but I forgot.

**Comment by mgersh** [comment]
Whoops. Didn't notice that was an old-style dependency. That's easy to fix.
