### ISSUE TITLE
Adding support for teaching assistants

### ISSUE THREAD

**Issue by corinnherrick** [learning-unlimited/ESP-Website#1990]
MIT Splash often runs into situations like the following:
1) A class has 10 co-teachers, so we don't know who is ultimately responsible for the class. This is common with classes run by student groups.
2) A co-teacher is added last-minute, too late to go to a teacher training, but when they sign up next time they aren't a first-time teacher so they aren't ever asked to attend a training.

Sometimes directors choose to allow classes to have "TAs" instead of official co-teachers, but every time we've done this it's been a bit of a mess because there isn't any integration with the website so those TAs don't get all of the logistics and thank you emails, and we have to separately account for tshirts and nametags. I think we should have functionality (which should be disabled by default) to allow teachers to add a TA who isn't considered to be a full teacher for the class. Dashboard stats (like tshirt sizes, etc) should be updated and there should be a way to print nametags for TAs who aren't also teaching a class.

**Comment by betaveros** [comment]
This would be even more useful for MIT Splash/Spark than it was in the past because teachers often want to find TAs, or we may want to assign TAs, in order to satisfy the minors policy of there being two people per class.

**Comment by betaveros** [comment]
(However, I should also note that I think the ability to decide which teachers need to attend training (now orientation) based simply on whether they've taught in a similar program before isn't necessarily something we should go to great lengths to preserve. It's not that hard for us to start recording whether teachers have attended an orientation independently of whether they are registered as a teacher of an accepted class.)

**Comment by jerrywu64** [comment]
MIT would also benefit from being able to add coteachers or TAs to sections
individually.
