### ISSUE TITLE
Theme controller can cause duplicate Tags and TemplateOverrides

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#2002]
Duplicate Tags will cause the entire site to error. Duplicate TemplateOverrides will just silently sit there being duplicates, which won't immediately cause problems if they're all the same but could if they're different since an arbitrary one is chosen, and either way it's weird. (In all the cases we've had so far, they've been the same.)

I'm putting these in the same issue because I suspect that it's probably the same underlying bug, but I don't know what conditions cause it. It's only happened on sites running Django 1.8. Duplicate TemplateOverrides only have happened on MIT and dev3, and both happened at the same time on Rice. For Rice, there's an email in serverlog, which is a POST to /themes/setup/, which I suspect is where the problem started or at least is related.

**Comment by mgersh** [comment]
I just saw the duplicate Tag issue on someone else's dev server. She said there's a chance she clicked "Save" twice, so that might be what causes that one. (Still a bug, of course.)

**Comment by willgearty** [comment]
I'm going to close this in the hopes that it has been fixed by https://github.com/learning-unlimited/ESP-Website/pull/3482.
