### ISSUE TITLE
Email Writing in Markdown

### ISSUE THREAD

**Issue by bhorowitz** [learning-unlimited/ESP-Website#2005]
Currently our email interface seems to force admins to write their emails in HTML. Since the website generally uses Markdown in its quasi-static text, it makes sense to allow Markdown in emails as well.

**Comment by bhorowitz** [comment]
If someone gives me some pointers/outline I can play around with this! :)

**Comment by willgearty** [comment]
How about just #2652?

**Comment by willgearty** [comment]
Fixed by https://github.com/learning-unlimited/ESP-Website/pull/2666
