### ISSUE TITLE
/manage///event_signup

### ISSUE THREAD

**Issue by luanths** [learning-unlimited/ESP-Website#2018]
The TeacherEventsModule is both a teach module and a manage module. This means that both of its views are available both under /teach/ and under /manage/. In particular, /manage///event_signup exists, and is the same as the teacher-facing signup page /teach///event_signup, except that the deadline doesn't apply because the tl isn't learn or teach. This seems unintentional.

**Comment by luac** [comment]
Special case of #412.

**Comment by willgearty** [comment]
Fixed by #3463.
