### ISSUE TITLE
ClassSection.preregister_student should fail if the section is not scheduled

### ISSUE THREAD

**Issue by luathenalena** [learning-unlimited/ESP-Website#2022]
Currently, preregister_student is perfectly happy to enroll students in sections that are not scheduled. By inspection, it doesn't seem like anything else in the stack checks for this either, so hypothetically a student might be able to register for such a section by hitting the /addclass view.

We probably want to disallow this, since we don't show those sections in the catalog.

**Comment by willgearty** [comment]
Fixed by #2851.
