### ISSUE TITLE
Link to public view of past comm panel emails

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2057]
It would be nice if we could (optionally enable) viewing a comm panel or built-in mailing list email in the browser.  This could have a number of uses, a few that come to mind:
- Putting a "view this email in a browser" link in HTML emails
- Linking to student logistics emails from the website in case students or parents didn't see them
- Linking to teachers' emails from the catalog, which someone suggested might be a great lightweight way to have some class materials be accessible to other students

**Comment by willgearty** [comment]
This is a great idea!
We store the data for every email, so it shouldn't be too crazy to make a view to see any email based on its ID, right?

For teacher emails, are those actually saved the same way comm panel emails are saved?
