### ISSUE TITLE
T-shirt costs included in financial aid

### ISSUE THREAD

**Issue by jerrywu64** [learning-unlimited/ESP-Website#2070]
If you pre-order a t-shirt (which is an optional fee I think) and you receive 100% financial aid, you will also receive financial aid for the shirt, which is usually not what we want. Of course you could alternatively specify the dollar amount of financial aid to avoid this issue, but it seems like this would be easy to mess up on. Maybe add an option for line item types for whether they should be included as part of finaid?

**Comment by betaveros** [comment]
It turns out there is already a `for_finaid` field on LineItemType, and some code somewhere has set it correctly for recent t-shirt line items on our site; we're just not using it...

**Comment by betaveros** [comment]
Update: I guess I did not correctly understand what `for_finaid` meant to whoever put it there. Right now it's set to True on the `LineItemType`s for financial aid grants and sibling discounts, so you can't actually use it to distinguish between t-shirt orders and program admission fees proper. I'm not sure what it *means*, though, and whether it would break things or cause confusion if we partially repurposed it and set it to True on program admission fees, or whether we should just make a new field (ew migrations)
