### ISSUE TITLE
Tool for diffing template overrides

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2072]
Even if we don't get around to doing something like #692, it would be nice to have a built-in way to display the diff of a template override against the original.  (Or, if that's too complicated, even a quick script to do it would have some value.)  This would make it easier to see what changes chapters have made, and whether they will cause any issues as we update the code.

**Comment by betaveros** [comment]
Since we were just dealing with templates, I think I'm actually interested in this and it looks approachable. Can you show me roughly where I would put such a view in the code, what sort of URL it ought to have, how to make it have the right permissions, etc.?

**Comment by benjaminjkraft** [comment]
That's a good question.  Unfortunately I'm not sure there's really a natural place to put it, because template overrides at the moment can only be viewed in the admin panel.  So you could just make a new view, at say `/manage/templateoverrides/<id>`, and link to it somewhere.  In the code, it would probably go in `esp.utils.views`, and have an `@admin_required` decorator for auth.

**Comment by betaveros** [comment]
Where's the right place to add a URL pattern for this? It's almost ready but I feel like putting it at the bottom of root `urls.py` is a bit noisy:

```python
urlpatterns += patterns('',
                        (r'^manage/templateoverride/(?P<template_id>[0-9]+)', 'esp.utils.views.diff_templateoverride')
                       )
```

**Comment by benjaminjkraft** [comment]
If you want you can add a `utils.urls` and put this in it, or you can just continue adding to the mess.

**Comment by betaveros** [comment]
meh, I think we can move it into `esp.utils.urls` when we have at least two

**Comment by pteromys** [comment]
Funny enough, I had a script on Chicago's instance to find and merge changes: https://gist.github.com/pteromys/c656ad3c761ad682c246

Having the built-in view will be much nicer. So, thanks @betaveros !
