### ISSUE TITLE
Cache needs to be flushed after scheduling classes to see timeslot capacities

### ISSUE THREAD

**Issue by bhorowitz** [learning-unlimited/ESP-Website#2082]
When scheduling classes, the dashboard doesn't show correct time slot capacities unless the cache is flushed. This is a bit annoying when trying to properly balance the time slot capacities.

**Comment by mgersh** [comment]
I recommend using the "Total capacity in each block by grade" scheduling check for this--scheduling checks are now much quicker to refresh than the dashboard. (Although the caching bug is still a bug, of course.)
