### ISSUE TITLE
Teacher survey review: numerical questions should say what their range is

### ISSUE THREAD

**Issue by luanthe** [learning-unlimited/ESP-Website#2083]
The page shows a histogram of responses, but there's no indication of what range they are out of, so it's ambiguous (does "5" mean 5 out of 5? out of 7? out of 10?)

**Comment by willgearty** [comment]
Hmm...I think I see a way to do this. First, we'll need to make the histogram template tag able to use the "Number of ratings" parameter:
https://github.com/learning-unlimited/ESP-Website/blob/c42712632733061d4ee23092829c60049eac2ccf/esp/esp/survey/templatetags/survey.py#L110
If we have a number of ratings, we can just make the dictionary with keys from 1 to `num_ratings` before populating it (and make the initial frequencies 0).
Then we'll need to pass the number of ratings parameter for the numeric question to the template tag, but we can only supply a single argument, so we could do something like the `QueryDict` example in [this stackoverflow answer](https://stackoverflow.com/questions/420703/how-do-i-add-multiple-arguments-to-my-custom-template-filter-in-a-django-templat).
We're already extracting the question parameters:
https://github.com/learning-unlimited/ESP-Website/blob/c42712632733061d4ee23092829c60049eac2ccf/esp/templates/survey/answers.html#L19
So we just do that before we make the histogram, then check that the question has a question_type that `is_numeric` and that `params.number_of_ratings` exists, then include `params.number_of_ratings` in the histogram tag call.
