### ISSUE TITLE
Validate JSON tags on save

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2084]
If a tag needs to have valid JSON data, we may want to try validating that on save.  There are a bunch that, when misconfigured, can break the site in not-entirely-obvious ways.

**Comment by hwatheod** [comment]
What's the right way for a tag to know that it's supposed to have valid JSON data?  Should we prefix all of them with something like json_ ?  For maximum benefit, this would require retrofitting all existing JSON tags with that prefix as well.

**Comment by benjaminjkraft** [comment]
I'd suggest we just have a fixed list, similar to the ones @mgersh added in #1995.

**Comment by willgearty** [comment]
This should be pretty easy now that we can define validators for individual tags. This json regex validator should work for many of them: https://regex101.com/library/tA9pM8, but we might want something more specific for specific tags.
