### ISSUE TITLE
Approving all sections from the status button doesn't work if class is already "Approved but hidden" 

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#2089]
To reproduce:
- Mark a class as "Accepted but hidden" from the manage page for that class
- Go back to the dashboard, it will say "[Approved but hidden]" for the class
- On the dashboard, click "Status" for the class, then "Approve (all sections)"
The display on the dashboard will change to "[Approved]", but it didn't really get approved.  If you refresh the dashboard, it will say "[Approved but hidden]" again.  This isn't a caching issue, since it can be confirmed by looking at the class status directly from the db in shell_plus.

**Comment by benjaminjkraft** [comment]
This is/was intended behavior, but I agree it's a bit confusing -- see discussion on #2090.
