### ISSUE TITLE
Update versions for dependencies

### ISSUE THREAD

**Issue by pteromys** [learning-unlimited/ESP-Website#209]
It'd be nice to know what versions of our dependencies we require. Our INSTALL file provides a few lower bounds, but they're a little out of date. Some observations:

* INSTALL specifies version 1.0.2 for Django. All live sites appear to have been running on Django 1.3 for a while, and 5cf2d228ba66ea38dc4df618e8b1409cc3c878a0, in order to retain compatibility with Django 1.3, breaks compatibility with 1.1 and before. (This is probably only the latest in a series of Django-1.2 and 1.3-isms that have crept into the code after everybody upgraded to 1.3.)

* INSTALL specifies 2.5 for python. The `with` statement is present in python 2.5, but until 2.6 requires a `from __future__ import with_statement`. As all live sites appear to be using python 2.6, the lack of such future imports can slip by unnoticed (as one did in the migration in 5610a3190261b3a3be7c0fda42b4e94d22d4bc40). If we're bumping up the required version to 2.6, the future imports are no longer necessary (and we might as well take them out to avoid confusing new developers as to which version they should be targeting).

**Comment by benjaminjkraft** [comment]
This was fixed long ago, and we recently bumped most dependency versions to latest in a84cf3c4.
