### ISSUE TITLE
Userview behavior when profiles are missing for latest program

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#2102]
If a teacher is teaching classes for a program but has no profile for the program, then the userview for the teacher will show blank (or maybe the latest program in which there was a profile) in the sections that depend on the program, e.g. the "teacher schedule (for program xxxx)" with a "print locally" section.  This means we can't print schedules for that teacher and program from the userview.

Admittedly, it takes a rare combination of events for this to happen. Stanford encountered it when we added an admin A who was otherwise not teaching any classes as a co-teacher onto a class which got cancelled but admin A was able to substitute-teach for.   I'm not sure exactly how it happened but probably this can happen if another admin edits A's availability and then morphs into the original teacher's account and adds admin A as a co-teacher to the class.  Thus admin A was added to a class in a program, but never created a profile for the program.  I was able to reproduce this scenario.

Stanford also encountered similar problems with students, which I don't have the details right now.

**Comment by benjaminjkraft** [comment]
The best fix for this is probably #1880.

**Comment by mgersh** [comment]
The more common reason why this happens (for both teachers and students) is when a user fills out their profile for the program and then later edits their profile from the myesp (non-program-specific) page.

**Comment by benjaminjkraft** [comment]
Hopefully mitigated sufficeintly by #2399; if we still see this a lot feel free to reopen.
