### ISSUE TITLE
Caching bug in Program.getListDescriptions()

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#2115]
It's missing a dependency on Event, which is needed because it depends on the list of volunteer timeblocks. This can cause things to Whoops after you delete a volunteer timeblock.

**Comment by willgearty** [comment]
I don't see any caching for this function:
https://github.com/learning-unlimited/ESP-Website/blob/72cdb7427c744ab042cf1dd75dcbe3af9bcb2b2e/esp/esp/program/models/__init__.py#L450-L461

**Comment by willgearty** [comment]
I tested this (added a new volunteer slot, checked the comm panel, then deleted the new volunteer slot, then checked the comm panel) and was not able to reproduce the issue.
