### ISSUE TITLE
Internal Server Error: /admin/users/gradechangerequest/173/

### ISSUE THREAD

**Issue by btidor** [learning-unlimited/ESP-Website#2118]
https://sentry.mit.edu/esp/esp-website/issues/236/

```
ValueError: save() prohibited to prevent data loss due to unsaved related object 'student_info'.
(12 additional frame(s) were not displayed)
...
  File "esp/users/models/__init__.py", line 2518, in save
    self.requesting_student.set_grade(self.claimed_grade)
  File "esp/users/models/__init__.py", line 975, in set_grade
    self.set_student_grad_year(ESPUser.YOGFromGrade(int(grade)))
  File "esp/users/models/__init__.py", line 965, in set_student_grad_year
    profile.save()
  File "esp/program/models/__init__.py", line 1296, in save
    super(RegistrationProfile, self).save(*args, **kwargs)
  File "django/db/models/base.py", line 685, in save
    "unsaved related object '%s'." % field.name
```

Steps to reproduce:
1. Create a new student account.
2. Visit `/myesp/profile`.
3. Submit a grade change request.
4. Enter some text into the profile (specifically in the YOG field), but don't fill it out completely. Hit Save, and get form validation errors.
5. Switch to an admin account, attempt to approve the grade change request, and get this error.

I initially thought this might be a caching bug, but after flushing the cache, step 5 still fails.

**Comment by willgearty** [comment]
I'm guessing this will be fixed by https://github.com/learning-unlimited/ESP-Website/pull/2867
