### ISSUE TITLE
Add dev setup instructions to contributing docs

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2122]
Probably just in the form of a link to the script, or to another doc if we already have one.

**Comment by mgersh** [comment]
Do you just mean https://github.com/learning-unlimited/ESP-Website/blob/main/docs/dev/vagrant.rst? Or is there something more you want that we don't have?

**Comment by benjaminjkraft** [comment]
Yeah, that's exactly what I mean.
