### ISSUE TITLE
Serve favicon at /favicon.ico

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2128]
I've been trying to set a favicon for the Stanford Splash website.
As far as I am aware, there are two basic ways to go about doing it:

1. Have your desired favicon.ico at /favicon.ico

2. Include something like the following in main.html:
`<link rel="shortcut icon" href="/media/images/favicon.ico" />`

At the moment, I've implemented #2, as #1 is not currently implementable.
I've included that line of code in main.html (after uploading favicon.ico through the filebrowser).
And it seems to work...sometimes.
For example, it doesn't seem to work in my default browser (Chrome Canary), but it does seem to have updated in my non-default browsers (Waterfox, Chrome Beta).
I even downloaded Firefox (fresh install, no previous files/cache) and the favicon is updated there, too.
I've even tried clearing my cache and deleting my previously stored favicons for Chrome Canary, but now I just get the blank favicon icon.
@benjaminjkraft has reported that it works for him in his browser, but other Stanford Splash folks have reported similar unpredictability with their various browsers.
However, when it does work, it works on every page, so there can't be any theme problems, right?

Therefore, I'm wondering the following:

1. Is there any reason why implementation #2 would have such unpredictability?

2. Given this unpredictability, is there the possibility of implementing #1 from above?

Thanks,
Will

**Comment by benjaminjkraft** [comment]
Huh, that's strange.  It shouldn't be a theme problem if it works on every page but only for some people, although it could.

In any case, I think we can implement option 1; we'll just need to add a line to our Apache configs (both the templates in the repo and the live ones on the server).

**Comment by willgearty** [comment]
That'd be awesome, thanks @benjaminjkraft !
