### ISSUE TITLE
Resource choices as classroom furnishings

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2140]
Classroom furnishings should include the option to select resource choices rather than entire resource types (if a resource type has a choice, it is most probable that classrooms do not have all of the choices as furnishings).

Currently, we need to add additional resource types after teacher registration closes in order to facilitate proper scheduling (manual). This process is extremely convoluted.

**Comment by jerrywu64** [comment]
This is now supported with #2311, but the interface needs to be updated for it.

**Comment by willgearty** [comment]
Something I've been working on got me thinking about this again. @jerrywu64 Any thoughts on how to update the resources interface to accommodate this? The largest hurdle would be the fact that you can currently associate multiple resources at a time with a classroom, so you'd need some way to assign a value to each resource that you want to add, while maintaining this current functionality? Perhaps something along the lines of #2432 where you add each resource (like adding choices in that pull request) as you are setting up a classroom, then can specify the value for each one as well?

**Comment by willgearty** [comment]
Would there even be a way to, once you have selected a resource to add from a dropdown, to have another dropdown which gives you the choices for that resource from which you can pick?
