### ISSUE TITLE
Warning systems for unsent emails

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#2164]
Email is a particularly failure-prone system, and probably always will be. We should try to improve monitoring on it.

One specific idea I had: have the comm panel display a warning if there are unsent emails. This would only have caught the recent three-week outage two days earlier, but anything cron-based wouldn't have caught it at all. Or we could even also put it somewhere other than the comm panel to improve the chance that someone will notice, if we can think of somewhere appropriate.

**Comment by willgearty** [comment]
Fixed by https://github.com/learning-unlimited/ESP-Website/pull/2852
