### ISSUE TITLE
Records for "paid for a program" are defunct

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2185]
We don't use the record type "paid for a program" to keep track of credit card (or other payments received in advance) anymore, but they're still viewable at /admin/users/record/?event__exact=paid and I'm told that onsite check-in and registration modules will still create these records. We should probably either change this to keep track of transfers in a way that's easier to search, filter, and sort than transfers, or just remove the record type entirely to avoid confusion (and maybe improve transfer searching tools).

**Comment by willgearty** [comment]
In the process of getting rid of this record, should we backfill transfers for any existing records that will be deleted/deprecated?

**Comment by milescalabresi** [comment]
Yes, if it's not too much work!
