### ISSUE TITLE
Update_deps doesn't attempt to use sudo or chown

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2186]
Per [this comment thread in the deployment of Stable Release 8 to UCSD's site](https://docs.google.com/document/d/18KsZkAiJwUNcJ-0Y0LLsnZLidLuN_UZJZuVQyHIBVRs/edit?disco=AAAAAvMv854).
(Link to the file: https://github.com/learning-unlimited/ESP-Website/blob/main/esp/update_deps.sh)

**Comment by milescalabresi** [comment]
Looks like it. Still no `sudo` in the last lines https://github.com/learning-unlimited/ESP-Website/blob/main/esp/update_deps.sh#L80. It should be an easy fix

**Comment by willgearty** [comment]
I think it's frowned upon to use sudo for pip install (e.g., https://stackoverflow.com/questions/15028648/is-it-acceptable-and-safe-to-run-pip-install-under-sudo).

**Comment by milescalabresi** [comment]
I would agree if we had a virtual environment set up, but the way we do it, we already install it globally, so if we lack permissions, it just won't happen. I'm also fine with setting up a venv but that would be outside the scope of this ticket.

**Comment by willgearty** [comment]
Well, I believe we're installing and upgrading pip within a virtual environment for that part of update_deps.sh. I don't believe this issue came up in the last release, so I'm going to close this for now.
