### ISSUE TITLE
Need to flush the cache after scheduling

### ISSUE THREAD

**Issue by mgersh** [learning-unlimited/ESP-Website#2198]
Yale's catalog had some classes missing after scheduling, and flushing the cache fixed it. We should fix the cache dependency somewhere.

**Comment by milescalabresi** [comment]
I think the dependency is either here https://github.com/learning-unlimited/ESP-Website/blob/stable-release-8/esp/esp/program/templatetags/class_render.py#L122, or at line 35, but I'm not positive.
