### ISSUE TITLE
Send email to any group

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2207]
Especially for programs that create custom groups for students, etc, it would be valuable to be able to email any specific group (perhaps as a dropdown menu in the comm panel). Beyond that, it would be great to be able to email any boolean combination of any number of groups (I'm thinking of an implementation similar to that of /classsearch but for the comm panel).

**Comment by benjaminjkraft** [comment]
@willgearty is #2223 sufficient for this or is there more you'd like?

**Comment by willgearty** [comment]
Well, the current implementation only permits one group filter. I could imagine any combination of groups would also be great, but that's could be tough, especially given the limitation we encountered with #2223. I imagine your more thorough overhaul of the comm panel would/could implement this. For now though, #2223 is sufficient for Stanford's needs.

**Comment by willgearty** [comment]
Fixed by https://github.com/learning-unlimited/ESP-Website/pull/3168
