### ISSUE TITLE
No Line Graph on BigBoard

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2208]
I was looking through the big board [handler](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/modules/handlers/bigboardmodule.py) and [template](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/templates/program/modules/bigboardmodule/bigboard.html), and noticed that there is supposed to be a line graph with registrations over time.
However, on our site's big board, we don't see a line graph. We have the large counts, the load averages, and the most popular classes, but no line graph.
(We're currently in the class lottery phase, but we don't have a line graph for any of the big boards for our previous programs either)

There's no console errors, so my best guess is that the `times_classes` method isn't working correctly? But really, I have no idea.

**Comment by benjaminjkraft** [comment]
Looks like the issue is that we show two timeseries -- the medical form and studentregs -- and hide the entire graph if either of them has no data.  I'll put in a fix to only hide if both are missing.
