### ISSUE TITLE
ui-widget-overlay blocks ui-dialog in Student Reg

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2209]
When a student wants to remove a class from their schedule, they click "remove" and it causes a dialog box to popup.
It also creates a ui-widget-overlay, which is supposed to gray out the page to highlight the dialog box.
However, the overlay is in front of the dialog box, which prevents the student from actually confirming the removal of the class from their schedule.

The code for the [student schedule](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/templates/users/student_schedule.html) hasn't changed since 2014, so I'm guessing a dependency changed or something?

I've made a quick fix for the moment that just hides the overlay using some CSS, but I'm worried this might be a wider problem.
For example, I've noticed similar bugs on the dashboard which uses similar overlays and dialogs to show class status infos.

**Comment by mgersh** [comment]
I haven't heard any reports of this from MIT, so it might be specific to Stanford's theme or template overrides? Either that or MIT just hasn't said anything.

**Comment by willgearty** [comment]
I tried switching to the default template and it didn't fix the problem.
It's possible it's a theme problem (I don't know much about our overall theme).
I might check it out on a dev server at some point if I get a chance.

**Comment by willgearty** [comment]
Just tested this on a dev server (at least on the dashboard) and the overlay behaves as it is supposed to.
@mgersh , looks like you might be right about it being a theme problem. I'll investigate further when I get a chance.

**Comment by willgearty** [comment]
Still not really sure why Stanford is encountering this problem (there aren't any theme problems that I can find), but I've implemented a quick-fix for us, so I'll close this for now.
