### ISSUE TITLE
Teacher checkin page is slow

### ISSUE THREAD

**Issue by betaveros** [learning-unlimited/ESP-Website#2217]
Loading the class details asynchronously on demand would probably make a big difference. The resource queries hit the database a lot.

Even if we did that, though, it looks like there's a separate SQL query for every room and phone number because they go through different tables. I dug through the code a little bit and tried some things and couldn't find any way to eliminate this. Perhaps somebody who knows the backend or Django queries can figure something out?

**Comment by betaveros** [comment]
I figured some things out, I guess. Not the room numbers, but I think I'd be satisfied with the speed of the page after these optimizations

**Comment by benjaminjkraft** [comment]
Fixed in #2218.

**Comment by betaveros** [comment]
I want #2219 to be merged before closing this, I think it's just as much of a slowdown (it makes a zillion queries for the resources of every class)...
