### ISSUE TITLE
jQuery version is old

### ISSUE THREAD

**Issue by betaveros** [learning-unlimited/ESP-Website#2221]
1.7.2 is dated March 2012, so four and a half years, it looks like... jQuery even has major version 3 now...

**Comment by benjaminjkraft** [comment]
I thought we were on 1.11 or something, because the new scheduler required it?

**Comment by betaveros** [comment]
I think this is at least the most commonly included jQuery:
https://github.com/learning-unlimited/ESP-Website/blob/45d903466a9d85b32bf35b65bbe24dea459cff3f/esp/templates/elements/html#L34
```django
{% block jquery_version %}
    <script type="text/javascript" src="{{ settings.CDN_ADDRESS }}/jquery/jquery-1.7.2.js"> </script>
{% endblock jquery_version %}
```

**Comment by benjaminjkraft** [comment]
:cry: looks like we have several versions at once.  Maybe we should fix that too.

**Comment by mgersh** [comment]
I looked up the thing with the scheduler and that was jquery-ui, not jquery. At least I think those are different things? We do seem to also have multiple versions of jquery at once, though.

**Comment by betaveros** [comment]
How would we actually go about upgrading this? Can somebody upload newer jQuery versions to the CDN we use? I think I would be satisfied with staying with 1.x, so upgrading to 1.12.4.

**Comment by benjaminjkraft** [comment]
I think the CDN just involves somebody with access to LU's AWS account syncing some files?  But I'm not entirely sure as I haven't done it before.  @jmoldow probably knows.

**Comment by jmoldow** [comment]
I've never uploaded to the CDN. I might have the credentials from @pricem . I'll check when I get home if I have them.

Is there a reason we still need to maintain our own CDN? We don't even upload most of the site's javascript there, just jQuery. And can't we use an existing jQuery CDN? e.g.

https://code.jquery.com/
http://jquery.com/download/#using-jquery-with-a-cdn
https://cdnjs.com/libraries/jquery/
https://developers.google.com/speed/libraries/#jquery

**Comment by jmoldow** [comment]
Looks like I misspoke. Seems like there's a bunch of files on the CDN. But nothing new has been uploaded there since 2012, according to https://dfwb7shzx5j05.cloudfront.net/ .

**Comment by benjaminjkraft** [comment]
Ok.  I think I have all the necessary credentials too then, since it's just
some AWS bucket.  But I am definitely not opposed to switching to cdnjs or
google.  We may want to add subresource integrity and
crossOrigin="anonymous" to be extra paranoid.
