### ISSUE TITLE
View Class/Teacher Survey Results by Class

### ISSUE THREAD

**Issue by mariolsen0112358** [learning-unlimited/ESP-Website#2266]
I'd like a way to view class/teacher survey results by class/teacher without having to morph into each teacher to access the surveys separately. Thanks :)

**Comment by benjaminjkraft** [comment]
Does downloading all the surveys as XLS work for you?  There should be a link in the manage version of surveys to do that.

**Comment by mariolsen0112358** [comment]
Yay thanks for interacting with the problem :) but I don't see any such link. I couldn't find anything in the general manage page for Splash, and you don't mean [](https://esp.mit.edu/manage/Splash/2016/surveys/review), do you?

**Comment by benjaminjkraft** [comment]
Looks like I mean https://esp.mit.edu/manage/Splash/2016/surveys, which might or might not be linked from the complete list of modules on the manage main page.

**Comment by mgersh** [comment]
It's not, we still haven't fixed #2008.

**Comment by mariolsen0112358** [comment]
Perfect, thanks!
