### ISSUE TITLE
fruitsalad top-left contact info missing on login page

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2282]
e.g. https://esp.mit.edu/accounts/login/?next=/manage/programs/, the program name and contact info normally in the top-left corner is missing.

**Comment by willgearty** [comment]
This seems fixed?

**Comment by willgearty** [comment]
It looks like `theme` isn't in the context, which results in some things not displaying.

**Comment by willgearty** [comment]
Closed by #2699.
