### ISSUE TITLE
Add "Make Sure to Hit Save" to "modify co-teachers" page

### ISSUE THREAD

**Issue by jerrywu64** [learning-unlimited/ESP-Website#2296]
People seem to be forgetting to hit it.

I made a template override for MIT's website at https://esp.mit.edu/admin/utils/templateoverride/412/ but this should become code instead.

**Comment by benjaminjkraft** [comment]
If this is just a template change, mind making a pull request for the same change?

**Comment by willgearty** [comment]
Looks like this is all set.
