### ISSUE TITLE
Way to modify menu of available teacher shirt sizes

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2298]
I think the easiest way to make this happen would be a tag, though it seems that no such tag exists, for teachers or students, if a program does not want to or is unable to offer (for instance) XXL or XXS shirt sizes. If such a way to modify the pulldown menu does exist, there appears to be no documentation of it. I'm imagining something along the lines of a tag with key `teacher_shirtsize_options` and value `["XS", "S", "M", "L", "XL"]` to change what appears in the pulldown menu for a given program or the profile editor, perhaps leaving blank anyone who had a now-unavailable size.

**Comment by benjaminjkraft** [comment]
Yeah, this probably wants to be a tag.  My suspicion is that allowing it to be program-specific will end up complicating things significantly since we do a lot of copying between programs, but I could be wrong.

**Comment by milescalabresi** [comment]
After much investigation, since tags hit the db, making this a scrmi field would be nice. Just a note to future self/developers

**Comment by willgearty** [comment]
What's the status on this @milescalabresi ?

**Comment by milescalabresi** [comment]
The status is I need to learn how to make it a scrmi field. Are you familiar with that process?

**Comment by willgearty** [comment]
Ah, I see the problem. We've already specified the choices for the `shirt_size` (and `shirt_type` for that matter) in the `StudentInfo` model:
https://github.com/learning-unlimited/ESP-Website/blob/89b7fcd1fddf8680440c1b746e8cc445f2e9522c/esp/esp/users/models/__init__.py#L1240-L1241

What I would suggest is to remove the choices here in the model definition, then just use a tag to specify the choices in the form itself (this is very similar to how the `graduation_year` field is handled in the `user_profile` form and how the `class_style` field is handled in the `teacherclassregform` form.
