### ISSUE TITLE
NEU teacher profiles not displaying

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2308]
Many teacher profiles (ones with `mask_email`) cannot be accessed from the user search sidebar because `mask email` isn't a tag library.

**Comment by mgersh** [comment]
I haven't looked at this for real, but: is this specific to NEU? If so, could it be caused by their weird template overrides? They have a bunch left over from when they were briefly on Chicago's custom theme.

**Comment by milescalabresi** [comment]
It looks that way. No one else has reported it, and I've tried searching for teachers on a random smattering of sites on other themes without problems. Any harm in deleting some of the uncommon template overrides and restoring them?

**Comment by mgersh** [comment]
You could probably find it without doing that by looking for something related to the page that's broken that has "mask_email" in it. But yeah, those template overrides could use cleanup anyway.

**Comment by milescalabresi** [comment]
That did the trick. For future records, `users/userview.html` was the template causing the trouble.
