### ISSUE TITLE
Status button lists class durations one minute shorter than expected

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2318]
When using the status button on the dashboard (and possibly elsewhere), class' durations are listed as :49 and 1:49 instead of the expected 0:50 and 1:50.
![image](https://cloud.githubusercontent.com/assets/5506191/22865658/cf1e3946-f136-11e6-95c3-50d179d377a2.png)

**Comment by willgearty** [comment]
Is this still an issue? Stanford's site doesn't have this problem. Neither does Yale's.

**Comment by willgearty** [comment]
Whoops, just noticed this bug on Northwestern's dashboard!

**Comment by willgearty** [comment]
Now that we are rounding things consistently, I'm seeing this on lots of sites. I've also noticed it on the /manageclass page.
