### ISSUE TITLE
Add some kind of confirmation to the lottery frontend

### ISSUE THREAD

**Issue by jerrywu64** [learning-unlimited/ESP-Website#2320]
It looks like Spring HSSP 2017 accidentally ran the lottery a second time when someone was playing with the lottery frontend, although we're not really sure how (the person who was playing with it at the time didn't realize they ran the lottery, we only discovered it (or rather, conclude that it happened) after the fact because a lot of StudentRegistrations were expired and created at the same time). So barring a bug in the code that saves when it shouldn't, we should probably make it harder to accidentally run and save the lottery.

(Also disclaimer, I looked at the lottery frontend on my devserver but haven't really managed to run anything.)

I think ideally "save" would take us to a confirmation page with more detailed lottery information (e.g. x user was assigned to y class, keeping in mind there will be a ton of these so either randomize them and truncate or make it scrollable), but even a confirmation dialog might help.

**Comment by benjaminjkraft** [comment]
Fixed by #2335.
