### ISSUE TITLE
Floaty theme problems

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2336]
> UMBC reported getting 404 instead of the "however, you do have the ability to change that if you would like" page when trying to add a new page to the site. One relevant file seems to be https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/qsd/views.py#L94, but I don't see any dependence on themes or site, so it's not clear why it doesn't affect other sites.

> Looking into it further, UMBC also has two copies of main.html and index.html after switching themes, so it looks like the switch to floaty didn't go through correctly.

> Perhaps independently, switching to a custom logo pushes the "Supported by Learning Unlimited" text over the login box. If this is not a problem and just requires a rectangular image, it's not obvious.
![image](https://cloud.githubusercontent.com/assets/5506191/23272162/3b1266f6-f9c8-11e6-8000-7019052cb606.png)

**Comment by benjaminjkraft** [comment]
For the 404, are they logged in?  This definitely doesn't seem theme-specific unless the theme is overriding QSD templates.

For the two copies, that sounds like the old theme didn't get cleared out correctly, not necessarily a general bug.

For the logo, they should make the logo smaller.  Most of the sites are designed around a roughly fixed-size logo.  We should probably document this.

For whichever parts of this are staying as issues, can you split them into separate issues?

**Comment by milescalabresi** [comment]
Oh, I see what the 404 was -- they were trying to make a page without the trailing `.html`, which does give a 404 to admins. I guess that's resolved.

Just to make sure I understand, you mean hitting the "clear theme" button before choosing a new theme, or something else? (If so, I can expand on the steps mentioned in [themes.rst](https://github.com/learning-unlimited/ESP-Website/blob/main/docs/admin/themes.rst)).

Yes, I think the last one is a documentation thing. I'll open a separate issue for that or try to include it in a short addition to themes.rst with the previous point about templates.

**Comment by mgersh** [comment]
The two copies of index.html and main.html could also be #2002.

**Comment by benjaminjkraft** [comment]
> Just to make sure I understand, you mean hitting the "clear theme" button before choosing a new theme, or something else?

Hitting "clear theme" may be insufficient for removing a custom theme.  We need to remove any template overrides that are a part of the old custom theme; this generally needs to be done manually as it may not be clear which ones are theme-related.

**Comment by milescalabresi** [comment]
Yeah, the only TOs they had wre main, index, and student schedules. I'll add a note about clearing old templates and elaborate on logo sizes (and other images) in themes.rst and call this one closed? Sorry for the scattered presentation.
