### ISSUE TITLE
Fix pluralizations of models on admin page

### ISSUE THREAD

**Issue by betaveros** [learning-unlimited/ESP-Website#2354]
Kind of related to #1321, but at least we should tell Django that (for example) the plural of "category" is "categories". I don't think Meta class changes would require database migrations or anything of that sort? Basically just do this: https://docs.djangoproject.com/en/1.8/ref/models/options/#verbose-name-plural

**Comment by betaveros** [comment]
Oh I guess I should link #2357 to this.

(I wouldn't mind leaving these pluralizations as tiny changes for people to learn how to contribute with, but I think I can find more minor issues eventually.)

**Comment by Nickatak** [comment]
Hello! Is this still an existing issue?

**Comment by milescalabresi** [comment]
Yes, please feel free to address it if you'd like. I dropped the ball

**Comment by Nickatak** [comment]
Ofcourse.  I'm stuck on something else at the moment, so I will start this tomorrow when I have time (I also need time to read through the docs/readme's to make sure I'm doing this right, as I'm pretty new). :D

**Comment by Nickatak** [comment]
@milescalabresi Do you happen to have a list of which ones are/are not completed?  Or would you prefer me to just go through each one and check?

**Comment by milescalabresi** [comment]
I don't, sorry. I remember them being pretty easy to notice, though.

**Comment by Nickatak** [comment]
Erm, I understand what must be done here, but I have no good way to test this (I have a win box only right now).  I think I'm going to have to decline this, sorry :C
