### ISSUE TITLE
Confirm class cancellation email to teachers

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2360]
Clark Splash has requested a checkbox so that when an admin (or teacher) cancels a class, the website should email all teachers (including co-teachers) of the class. The logic is that if a teacher cancels their own class, the email can serve as a confirmation receipt, and if an admin cancels the class (if teacher emails in with an emergency or if too few students register) it can notify the teacher that the class has been cancelled. Ideally this checkbox would allow an optional message explaining why the class has been cancelled.

**Comment by willgearty** [comment]
Huh, for some reason I already thought the website did this.

**Comment by milescalabresi** [comment]
I did too, but apparently not unless the reportees missed it in their spam folder or something. If it doesn't, perhaps it's because teachers usually cancel their own classes, so it's rare that an admin actually cancels a class without a teacher's prior knowledge.

**Comment by willgearty** [comment]
I just tested this and the website definitely doesn't send an email to the teachers when a class is cancelled.

**Comment by willgearty** [comment]
Just coming back to this, and I feel like this should just be default behavior. Do we really want a checkbox so it is an option to email the teachers, or should it just email the teachers when it is emailing the admin email?

**Comment by milescalabresi** [comment]
I'm not opposed to making it the default behavior
