### ISSUE TITLE
Change colors for visibility on AJAX Scheduler

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2361]
UCLA requested on the feature request spreadsheet:

>Scheduler currently lists section ID (eg. A9s2) in black font and on a dark grey background. Very hard to see.
Recommend changing background color. If possible, also allocate one color to each subject (eg. light blue for math classes) to give variety to a timeslot.
If possible, allow user to customise colors as well.

**Comment by willgearty** [comment]
From my testing, this occurs for Berkeley, Harvard, UMBC, UCSD, NEU, NJIT, JHU, UC Merced (and my dev server).

This does not occur for Stanford, Yale, BC, or Duke.

There does not seem to be any association by theme, timeslot duration, number of days/blocks, whether classes start on the hour, or whether there is a gap for a lunch break.

**Comment by milescalabresi** [comment]
This seems to depend on the program. For example, as you said, Yale's [upcoming Splash](https://yale.learningu.org/manage/Splash/2019_Spring/ajax_scheduling) does not have this problem at all, but their [Spring 2014 program](https://yale.learningu.org/manage/Splash/2014_Spring/ajax_scheduling) has some (though not all) of the classes displaying with this black-on-gray. What dictates the color/where in the code is that assigned? Could it have something to do with class size or availability as in the onsite scheduler?

**Comment by willgearty** [comment]
Oh, I guess I never updated this issue, but I did figure out the problem, and I wrote a fix for it. The coloring logic is hard coded to require a 4 digit class ID, so it fails for any classes with fewer digits.  We just need to pad the class IDs do they have enough digits to work with.

**Comment by willgearty** [comment]
Based on the wording of the request from UCLA (rip?), It sounds like they weren't aware that there was supposed to be coloring logic in the first place. My PR fixes the logic so the original intent now applies to all programs, but perhaps we should move the other more specific requests to another issue for the future? (@kkbrum?)
