### ISSUE TITLE
Discoverability for make admin page

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2363]

**Comment by benjaminjkraft** [comment]
It's hard to find, and the admin panel is easier to find but you have to do several things for it to work right.

**Comment by willgearty** [comment]
I would suggest putting on the program /main page, but really it should be on a page that isn't program-specific.
What about adding it to the /manage/index.html page (which I only just realized was a thing)?

**Comment by benjaminjkraft** [comment]
I think several chapters have it linked from the editable text at the top of /manage/programs, so that's definitely an option, although it doesn't work if people have already edited it.

**Comment by willgearty** [comment]
Oh yeah, just realized /manage/index.html is a static page on our site, so that wouldn't work for everyone.
Could we have a list of permanent links at the top of /manage/programs (as opposed to including it in the QSD), one of which would be this?

**Comment by willgearty** [comment]
Fixed by #2534.
