### ISSUE TITLE
Error in renaming classrooms

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2385]
Reported by Princeton: when they change the name of a classroom in which a class is already scheduled, the room number is not recognized as part of the classroom name, and the AJAX scheduler will not load because of an uncaught TypeError. It is not clear if this error is restricted to their site or this program instance.

**Comment by willgearty** [comment]
Maybe related to #1130 and/or #1391?

**Comment by benjaminjkraft** [comment]
Unclear if it's related to #1391.  #1130 was a similar issue with the old scheduler which presumably is gone now and replaced by this one.

@milescalabresi what do you mean by "the room number"?  Are they making a specific type of change here?

**Comment by benjaminjkraft** [comment]
Actually, I realize, it may be this is because of the same underlying caching issue as the old scheduler.  But in any case let's keep this one to be clearer that it's for the new scheduler.

**Comment by milescalabresi** [comment]
Yeah, they were changing the room number from "buildingname 3" to "buildingname 03" to test without confusing anyone as to the location. That seemed to break the scheduler. Here's a screenshot
![image](https://cloud.githubusercontent.com/assets/5506191/26026611/751a2040-37cc-11e7-962c-749173107455.png)

**Comment by willgearty** [comment]
I know this was a long time ago, but was the problem fixed by flushing the cache?

**Comment by willgearty** [comment]
I remember someone at SplashCon mentioning that changing a class name caused a bunch of problems with the scheduler. Maybe @milescalabresi or @bhorowitz was there and remembers who it was/more details?
