### ISSUE TITLE
bigpicture dashboard "status" button malfunctions

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2386]
Reported by Clark:  Admin Dashboard page becomes grayed out when I click the "status" button for any class. The status box appears behind the gray barrier instead of in front of it, as intended. Note this report comes after adjustments to the clark-sr9 branch.

**Comment by milescalabresi** [comment]
This issue has resurfaced when a student tried to cancel the confirmation and remove a class from her schedule.

**Comment by willgearty** [comment]
I feel like I made a template override for Stanford that fixed something like this...

**Comment by benjaminjkraft** [comment]
This seems to have been fixed by z-index changes in some other styling change, maybe #2222.
