### ISSUE TITLE
Grade range increment is screwed up

### ISSUE THREAD

**Issue by AhaanRungta** [learning-unlimited/ESP-Website#2392]
It seems like grades increment on July 31 (i.e. that's the graduation date). For this reason, we need to keep adding a increment_default_grade_levels tag for every Summer HSSP. We should just change this to like June 1 or something so that we don't have to deal with the rising 7th graders with this tag every single time.

**Comment by willgearty** [comment]
Perhaps it would make more sense to have a tag that overrides when the grades increment, with the default being July 31?
