### ISSUE TITLE
Display or sort by last program or similar information in user search

### ISSUE THREAD

**Issue by betaveros** [learning-unlimited/ESP-Website#2395]
Sometimes when we want to look up a person by their first or last name (e.g. if we only know their parent's name), we get a long list of users. Usually we're looking them up because they are attending or have attended our current or most recent program, so displaying or sorting by this information somehow might help us disambiguate.

**Comment by willgearty** [comment]
I think it would make a lot of sense to have a dynamic table on the user search page that could be sorted by any of the columns (and the last program would be one of them)
