### ISSUE TITLE
Student name not in cancellation emails

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2409]
Looks like this has been a problem for a while, at least at Stanford.
Whenever a student replies to class cancellation emails, I notice that the beginning of the email says:
`Dear {{ user.first_name }},`
meaning that, for some reason, the template is not properly accessing the data.
However, the rest of the email is always properly filled in with the context data.

**Comment by milescalabresi** [comment]
I was not able to reproduce the issue on my dev server. It correctly filled in the name of the student.

**Comment by willgearty** [comment]
Looking through the Stanford emails, it looks like this was fixed sometime mid-2018. I don't see any changes around that time in the template or the class cancellation code, so my best guess is that Stanford was using an old template override. Thanks for checking @milescalabresi!
