### ISSUE TITLE
teacherreg_label_purchase_requests edits "Planned Purchases" not text under box

### ISSUE THREAD

**Issue by bhorowitz** [learning-unlimited/ESP-Website#2446]
I changes around the "teacherreg_label_purchase_requests" tag on UC Merced's website, but as you can see in the image the behavior isn't the intended usage (should change around part about $30).

<img width="1010" alt="screen shot 2017-10-05 at 1 07 00 am" src="https://user-images.githubusercontent.com/6059772/31216777-9c3f8f98-a969-11e7-8c84-b28126b95300.png">

**Comment by benjaminjkraft** [comment]
You want to edit `teacherreg_help_text_purchase_requests` -- the text underneath is the "help text" whereas the text to the left is the "label", thus the two tags.

**Comment by bhorowitz** [comment]
Ah, the text here is inaccurate; I'll edit it!

https://github.com/learning-unlimited/ESP-Website/blob/3409e25feea12405487353800e35571b111d7380/docs/admin/program_modules.rst
