### ISSUE TITLE
Make "Cancel Class" Button Smaller/Disappear

### ISSUE THREAD

**Issue by mariolsen0112358** [learning-unlimited/ESP-Website#2447]
The new "Cancel Class" button (#2418) is cool, but is sadly being overused by MIT Splash teachers :( Is there anyway to make the button smaller so it doesn't overshadow all of the other buttons on the page? Or can there be a deadline associated with it so that it disappears once their classes have been scheduled and they're committed to teaching?

@willgearty

**Comment by willgearty** [comment]
@mariolsen0112358 for a temporary fix, you could just make a template override, but I can definitely work on adding a deadline for the button when I get a chance!

**Comment by willgearty** [comment]
Alternatively, I could add a tag that determines whether it shows up or not if a class is scheduled?

**Comment by mariolsen0112358** [comment]
Ooh a tag would be cool, but we'd probably prefer a deadline so we can close it arbitrarily early if needed :) Thanks for looking at it!
