### ISSUE TITLE
Import a subset of classrooms from previous program

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2457]
Right now you can import the entirety of a previous program's classrooms, but it would also be helpful to import just a subset of classrooms from a previous program.

Requested by Stanford.

**Comment by jerrywu64** [comment]
What's the difference between this and useful_scripts/csv_classroom_import.py?

**Comment by willgearty** [comment]
This would be on the front-end since most admins don't have command line access.
