### ISSUE TITLE
logical "groups" of time blocks

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#246]
Currently, the schedule is broken into "groups" of time blocks if two adjacent time blocks are separated by more than 15 minutes (or maybe it's a different number, I don't recall). There should be a setting to allow you to manually group the timeblocks, so that you can get two groups (e.g., morning and afternoon) without having to separate two time blocks by more than 15 minutes.

**Comment by willgearty** [comment]
I think the best first step would be to make the "15 minutes separation" part tag-based. Then, if we really want to be fancy, we could add a "group" field to time blocks and use those if they aren't NULL (and you would probably want that to be integrated with the time block resource page.
