### ISSUE TITLE
Clearly indicate if a user is deactivated on userview page

### ISSUE THREAD

**Issue by betaveros** [learning-unlimited/ESP-Website#2462]
Right now it appears that the only way you can tell if a user is activated from their userview page is by looking at the link that says either "Deactivate user" or "Activate user". Most of the information on a userview page is not useful or possibly misleading if the user has been deactivated, so deactivated users should be more clearly labeled as such.

**Comment by bhorowitz** [comment]
How does this look? 

<img width="450" alt="screen shot 2018-01-14 at 7 13 36 pm" src="https://user-images.githubusercontent.com/6059772/34925581-1be5f116-f95f-11e7-9544-eaf93f7ed6f2.png">

**Comment by bhorowitz** [comment]
Or maybe this?

<img width="358" alt="screen shot 2018-01-14 at 7 15 42 pm" src="https://user-images.githubusercontent.com/6059772/34925722-eeb6fcf2-f95f-11e7-9b08-e6df50de1817.png">

**Comment by benjaminjkraft** [comment]
Looks great to me!  I'd skip the "NOTE", personally, but I don't super care.

**Comment by bhorowitz** [comment]
Fixed by #2492
