### ISSUE TITLE
Nametags include deactivated users

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2469]
When generating nametags, deactivated users are included.
This conflicts with the generation of schedules which appears to exclude deactivated users.

**Comment by benjaminjkraft** [comment]
We should probably make nametags work like other printables and use the comm panel interface to get the exact same query easily.

**Comment by willgearty** [comment]
Would there be an easy way to integrate the custom options, though?

**Comment by willgearty** [comment]
Hmm...we probably want a first page that is similar to the current page, and that will give the options to make custom nametags or nametags based on db users. If the user selects the db users option, that would then take them to a new page where they could use the comm panel interface to choose users.
