### ISSUE TITLE
Wrong password error is unhelpful

### ISSUE THREAD

**Issue by emannes** [learning-unlimited/ESP-Website#2474]
> You need to log in before you can access /myesp/login/.

is not a user-friendly error message for when you enter an incorrect password.

![image](https://user-images.githubusercontent.com/3751025/32712208-543ac692-c811-11e7-9be5-c2004371a4cc.png)

**Comment by willgearty** [comment]
The only time we don't want to show the message is if we clicked the login button ourselves, right? So we would tell the handler if the user initiated the login by adding a little hidden field in the login form. Then, if that hidden field is included in the form data, tell the template not to show that field with a context variable.
