### ISSUE TITLE
Remove SAT-related modules

### ISSUE THREAD

**Issue by bhorowitz** [learning-unlimited/ESP-Website#2476]
Perhaps more of a matter of discussion, but I think we can safely remove all SAT-related modules and references in the website. For example, there are many invocations in the email panel that reference students diagnostic scores.

**Comment by benjaminjkraft** [comment]
Fine with me!  The only question is if MIT ESP still wants to keep that data around.  Might also be good to look at other modules not currently used by any programs.

**Comment by mariolsen0112358** [comment]
AFAIK, MIT ESP doesn't foresee wanting or needing that capability now that everything SAT has been spun off to ATI. It's also been so long since SATPrep that I don't see why we would want or use any SAT data

**Comment by willgearty** [comment]
Fixed by #2534.
