### ISSUE TITLE
check_availability styling like teacher availability

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2496]
See #2419.

**Comment by benjaminjkraft** [comment]
We could probably still do it!  But it would be a little more complicated to add the class codes (or maybe a hover-box for class details).

**Comment by willgearty** [comment]
Just like I did with volunteer availability? That would definitely work! I was just worried it might make potentially important information harder to find, but I think it would be fine.

**Comment by willgearty** [comment]
The new edit_availability page (#2583) now covers most of the functionality of check_availability, except for maybe the searching feature and unscheduled classes feature (both of which could be incorporated). So at this point perhaps it makes more sense to just phase one of the two out and merge the remaining features into whichever we choose to keep?

**Comment by willgearty** [comment]
Fixed by #2583.
