### ISSUE TITLE
Events and attendance tracking

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#25]
This has been requested.  I'm not exactly sure what it is; could someone comment further?  (I assume a UI to do attendance tracking?)

**Comment by milescalabresi** [comment]
Student attendance from various events is now available on arbitrary user lists, right? Permission to close?

**Comment by mgersh** [comment]
@pricem's comment sounds to me like it's talking about per-day attendance tracking for multi-week programs (HSSP, Sprout, etc.), which we don't support right now, but I'm not entirely sure, and also not sure whether anyone still cares.

**Comment by kkbrum** [comment]
- @willgearty recently created and attendance module for attendance within classes (with interfaces for both teachers & admins). PR #2868.

- Per day attendance is now more feasible given a new system of checking out students @willgearty created (PR #2903, #2935). This hasn't been implented yet, but I'm closing this issue in favor of the newer issue #2894.
