### ISSUE TITLE
Section indices are nondeterministic

### ISSUE THREAD

**Issue by betaveros** [learning-unlimited/ESP-Website#2505]
As far as I can tell, the index of ClassSection objects is determined by the order in which they appear in a reverse `all` query through the `AjaxForeignKey` with no sort key, and Django doesn't specify what order this is in. So a section code like `X12345s1` can refer to different ClassSections depending on how many times you restart the server or which shell you're using...?

**Comment by benjaminjkraft** [comment]
Yeah, I bet the same postgres unspecified behavior that in the past was more or less deterministic but now is not that caused #2510 is at play here.  We should make sure to sort by ID or timestamp or something else consistent when fetching section IDs.
