### ISSUE TITLE
Use device's camera to scan barcodes

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2506]
Right now, you can request barcode scanners from LU, but it would also be great if a user could just use their phone to scan barcodes to check students in.

Could use a JS library like this one: https://serratus.github.io/quaggaJS/
Good example (with source) here: https://serratus.github.io/quaggaJS/v1.0.0-beta.1/examples/scan-to-input/

**Comment by bhorowitz** [comment]
I think those would be potentially very hard to integrate into the latex-generating templates... I would maybe use QR code based?  https://tex.stackexchange.com/questions/1429/latex-package-to-generate-qr-codes

**Comment by willgearty** [comment]
Stanford uses the makebarcode latex package to make Code39 barcodes. Is this not commonplace?

**Comment by willgearty** [comment]
Yep, the idea is to cut out the middle man (barcode scanners) and just use people's phones to scan student barcodes to check them in.

**Comment by bhorowitz** [comment]
Sorry, is the suggestion that we should make a barcode-scanning app for smartphones? or that we should print qr codes on schedules?

**Comment by willgearty** [comment]
My understanding was that many chapters already use LaTeX barcodes on their student schedules, although I suppose it would be nice to standardize it? However, this issue is to start a discussion about the way we then scan those barcodes. In particular, I'm suggesting we add a feature to the checkin module that allows the user to use their device's camera to scan the barcodes.
