### ISSUE TITLE
Lunch constraint generator doesn't set the right seqs

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2510]
The lunch constraint generator generates a set of `ScheduleConstraint` based on the selections in the interface and the program's timeblocks; each consists of two `BooleanExpression`s, a condition and a requirement, which consist of an RPN-style stack of `BooleanToken`s, so for example `[ScheduleTestOccupied(timeblock_1), ScheduleTestOccupied(timeblock_2), '||']` would be true if the user has a class in `timeblock_1` or `timeblock_2`.  The ordering of the stack is stored in the `seq` field of the `BooleanToken`.

For some reason, the lunch constraint generator hasn't always been setting distinct `seq` objects on each of its `BooleanToken`s, such that their ordering is not well-defined.  In the past, they seem to somehow have always come out in the right order, I'm guessing because the database broke ties by `id`, which happened to be the intended ordering.  But for MIT ESP Spark 2018, possibly because of a postgres upgrade, they didn't, which caused an expression like the above to always evaluate to False, which as the requirement meant the constraint not satisfied when it should have been.

The fix will be to correctly set the `seq` on each token.  I'm not totally sure why it's not getting set correctly, but it seems that a simple OR like the above consistently results in all three `seq`s being 0, whereas really the OR should have a strictly higher `seq`.

**Comment by benjaminjkraft** [comment]
cc @betaveros I think you were interested in hearing about this.

**Comment by betaveros** [comment]
Do we really need the flexibility of storing a DSL that can express arbitrarily complicated boolean conditions in terms of its atoms in the database?

**Comment by benjaminjkraft** [comment]
Certainly not the way they're used now!  Replacing lunch constraints with something a lot less general would also be a valid solution to this problem, and definitely a worthwhile undertaking.  Or even something almost as general but less Clever -- e.g. a simple text or JSON DSL for the conditions rather than storing them as database structures would have avoided this issue as well as making them much easier to read.  But probably if you're replacing them wholesale, just do it right and don't make it general at all.
