### ISSUE TITLE
Teacher big board incorrectly calculates hours

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2511]
The hours on the teacher big board (tbb) do not match the hours on the dashboard. I think this is because the tbb only uses the duration associated with the class subjects, rather than summing the duration over the sections of the class subjects.

For reference: [TBB code](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/modules/handlers/teacherbigboardmodule.py#L141) and [Dashboard code](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/modules/handlers/jsondatamodule.py#L769)

**Comment by benjaminjkraft** [comment]
Fixed by #2519.
