### ISSUE TITLE
Move to sendgrid or another commercial email sender

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2514]
This, along with perhaps some changes to how we set the various from-fields on the emails we send, could help us get marked as spam a lot less.  Copying what I wrote to web-team:

> Email sending is a dark art, and there are a whole lot of things one has to do right, not to mention just not get people to mark one's email as spam.  We could probably improve some things if folks want to spend the time to mess around with the headers the comm panel sets and set up DKIM/SPF/DMARC properly, but it's an unending mess and there are some things it's harder to do well.  If we really want to improve this, we should move to sending via some commercial provider like Sendgrid who will manage all this crap for us.  (If cost is an issue, we could have it as an option that Splashes can reimburse LU for.)  I think MIT ESP may be interested in this sort of thing as well.

Sendgrid is the provider I'm most familiar with, but there are a lot of others, depending on what features we want.  For example, some providers might provide a much nicer interface we could directly give chapters access to send email to simple lists like "all teachers".

**Comment by benjaminjkraft** [comment]
If somebody's interested in this, you can start taking a look at some of the providers and costs, and see how easy they would be to integrate.  My guess is it wouldn't be hard -- they probably even have django email backends for major providers so it may be nearly drop-in code-wise, once we figure out all the right settings and such.

**Comment by willgearty** [comment]
e.g. https://sendgrid.com/docs/Integrate/Frameworks/django.html

**Comment by willgearty** [comment]
Sendgrid has been implemented since SR11
