### ISSUE TITLE
Update Stripe library

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2520]
We got this from Stripe:

---

Hello,

My name is Chris and I'm writing from Stripe. In June of 2018, Stripe, and the payments industry as a whole, will be dropping support for some older protocols used to make connections to our API. I'm reaching out because your Stripe account might be impacted.

We've noticed that in the last 30 days, you've made requests with an older version of our Python library (stripe-python 1.11.0-1.19.0). To ensure that your integration continues working after June 13, 2018, you will need to update stripe-python to at least 1.19.1, which contains no breaking changes.

You can use this sample code you can use to determine if you are impacted:

import stripe
if stripe.VERSION in ("1.11.0", "1.12.0", "1.12.1", "1.12.2","1.13.0", "1.14.0", "1.14.1", "1.15.1", "1.16.0", "1.17.0", "1.18.0", "1.19.0"):
print "Bindings update required."

https://support.stripe.com/questions/how-do-i-upgrade-my-openssl-to-support-tls-1-2#python

If our test script returns "Bindings update required" you will need to download and install a new version of stripe-python. If you use pip to manage your packages you can install this with pip install --upgrade stripe==1.19.1 Or you can find our library on Github, https://github.com/stripe/stripe-python/tree/v1.19.1

If you have any questions or need help, please reply to this email!

All the best,
Chris

**Comment by benjaminjkraft** [comment]
The changelog claims there are no backwards-incompatible changes: https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md

**Comment by bhorowitz** [comment]
Solved in #2527

**Comment by benjaminjkraft** [comment]
(In the future, we normally leave the issue open until the PR is merged -- if you say "Fixes #xxxx" in the commit, github will do it automatically.)
