### ISSUE TITLE
Combination list formatting messed up

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2550]
![image](https://user-images.githubusercontent.com/25392075/38775280-5d1fb25a-404c-11e8-8561-15051daa3510.png)

The "and" "or" "not" checkboxes are... not where they should be... If you click on the word, it works, but is not pretty.

**Comment by hwatheod** [comment]
Interesting, I've noticed a problem like this on Stanford's site for a while but I always assumed it was because of Stanford's custom theme.

**Comment by kkbrum** [comment]
@milescalabresi could you have done something during the Yale site update with our customization that caused this?  It was fine before the update. Is this a problem on other sites as well or just Stanford and now Yale?

**Comment by milescalabresi** [comment]
It's not your customization... I checked a few other sites, and they're having the same problem when you use combination lists :(

**Comment by benjaminjkraft** [comment]
Comparing to MIT ESP's site, which is not on SR10 yet I believe and where this looks fine, it looks like some of the jquery-ui styles that we used to have are gone.  I would guess this is due to jquery-ui upgrades (#2450), cc @betaveros.  Probably they changed the classes we need to apply or something.

**Comment by kkbrum** [comment]
@willgearty @benjaminjkraft  i know this is a lot to ask, but this comm panel bug is super super annoying and I would be forever happy if someone took a look at this. I dont know anything about jquery-ui but i can also try a bit.

**Comment by willgearty** [comment]
Not sure of a more permanent solution, but I figured out that the `ui-helper-hidden-accessible` class is what is ultimately causing the checkboxes to disappear (at least on the Stanford site). Removing the class doesn't seem to have any negative effects that I can see.

So the easiest thing at this point would be to just make a template override where the checkboxes don't have that class. Adding this template override for `program/modules/commmodule/commpanel_new.html` worked, although it's far from gorgeous:

```r
{% extends "users/usersearch/support.html" %}

{% block title %}Communications Portal{% endblock %}

{% block content %}

<h2>E-mail a list of users</h2>
<p>This page will help you e-mail a set of users in your database, with filtering options specific to {{ program.niceName }}.  Choose from three different approaches to select your users:
    <ul>
        <li><b>Basic list</b>: A set of users that all have something in common.</li>
        <li><b>Combination list</b>: A Boolean combination of basic lists.</li>
        <li><b>Previous e-mails</b>: Start from the settings that were used for a previous e-mail message.</li>
    </ul>
</p>

{% with include_prev_list="True" include_checklist="True" %}
{% include "users/usersearch/list_selector.html" %}
{% endwith %}

<script>
$j( document ).ready(function() {
    $j(".ui-checkboxradio").removeClass("ui-helper-hidden-accessible");
});
</script>

{% endblock %}
```

**Comment by kkbrum** [comment]
Hmm the checkboxes appear now, but for example the "or" checkbox is next to the word "and"... any ideas why the or/and/not arent all on the same line like they were before SR10?

![image](https://user-images.githubusercontent.com/25392075/44960152-2c9d5200-aec8-11e8-99e0-8cd3131c5ccb.png)

**Comment by willgearty** [comment]
This template override for `program/modules/commmodule/commpanel_new.html` seems to bring it close to its original styling:

```html
{% extends "users/usersearch/support.html" %}

{% block title %}Communications Portal{% endblock %}

{% block content %}

<h2>E-mail a list of users</h2>
<p>This page will help you e-mail a set of users in your database, with filtering options specific to {{ program.niceName }}.  Choose from three different approaches to select your users:
    <ul>
        <li><b>Basic list</b>: A set of users that all have something in common.</li>
        <li><b>Combination list</b>: A Boolean combination of basic lists.</li>
        <li><b>Previous e-mails</b>: Start from the settings that were used for a previous e-mail message.</li>
    </ul>
</p>

{% with include_prev_list="True" include_checklist="True" %}
{% include "users/usersearch/list_selector.html" %}
{% endwith %}

<script>
$j( document ).ready(function() {
    $j(".ui-checkboxradio").removeClass("ui-helper-hidden-accessible");
    $j(".ui-checkboxradio-icon").removeClass("ui-icon");
    $j(".ui-checkboxradio-label").removeClass("ui-button");
});
</script>

{% endblock %}
```html

**Comment by kkbrum** [comment]
It's beautiful! Thanks Will!

**Comment by willgearty** [comment]
Perhaps @benjaminjkraft or @betaveros have an idea of how to make a more permanent solution to the jQuery UI changes?

**Comment by willgearty** [comment]
I was going to try to make a more permanent solution for this, but, unfortunately, I'm not able to reproduce the behavior reported by @kkbrum on my dev server (I tried circles and fruitsalad).

**Comment by willgearty** [comment]
However, I am able to reproduce similar behavior on the Stanford site:
![image](https://user-images.githubusercontent.com/7232514/53700685-bb245a80-3da9-11e9-9667-41b98dd44402.png)

**Comment by willgearty** [comment]
OK, after some digging, this is once again an instance of #1841. The changes from #2450 didn't get applied to older sites, so Stanford and Yale were still on jQuery UI 1.8. Updating `jquery-ui.css`, the jquery-ui `images/` folder, and `commpanel.css` files on Stanford's site fixed this.
