### ISSUE TITLE
Ranking order in step 2 of two-phase lottery does not match that of /rank_classes

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2552]
It's unclear what's going on here, but it looks like the ordering of priorities that is used for the mainpage of the two-phase registration does not match the ordering of priorities on the /rank_classes pages. I didn't change the sorting in #2425, so perhaps this is a problem that has been around but was never identified?

It appears that the ordering on /rank_classes is the correct ordering, since it stays the same based on the students' actual rankings.

Reported by Stanford.

**Comment by benjaminjkraft** [comment]
Sorry, can you clarify: what ordering of priorities?  Maybe a screenshot of the two pages would help here?

**Comment by willgearty** [comment]
Ah, yes, that would probably help:

/rank_classes (the priorities set by the student):
![image](https://user-images.githubusercontent.com/7232514/38849942-e2059782-41c3-11e8-9cd1-96e337fab440.png)

/studentreg (random order):
![image](https://user-images.githubusercontent.com/7232514/38849954-f3570be2-41c3-11e8-8283-8fa046f790d7.png)

**Comment by willgearty** [comment]
I could see why this might have a different order because of some incorrect sorting, but the sorting is completely random each time the /studentreg page is refreshed. I believe the priorities are sorted [here](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/modules/handlers/studentregtwophase.py#L152), which seems like the correct sorting to me? And even if it isn't the correct sorting, shouldn't it be deterministic?

**Comment by benjaminjkraft** [comment]
Huh, yeah, this looks like a regression in SR10, presumably from https://github.com/learning-unlimited/ESP-Website/commit/86e9601cf59a373cd2ecca03e62bb7afd8918804 or some other commit in #2425.  I don't see anything wrong with the code either, but maybe if you test it on your dev server and put in a few `print`s in the right places you can find what's wrong.
