### ISSUE TITLE
Upgrade to django 1.11

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2554]
1.8 is about to hit end of support; we should upgrade.  This probably means:
- [ ] fix all the warnings we can find in logs
- [ ] read the changelog
- [ ] do some testing
- [ ] cross fingers

**Comment by milescalabresi** [comment]
I think I'm most helpful with the fourth task, but would it help to accumulate a list of warnings/errors that I encounter during testing for other things, or would all of those show up in a grep of the logs?

**Comment by benjaminjkraft** [comment]
I think grepping will be enough!
