### ISSUE TITLE
User page formatting is off

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2559]
![image](https://user-images.githubusercontent.com/25392075/38898774-fdbf8dac-4263-11e8-8c5c-f38b2baffec6.png)

All of this used to be at the right of the page, with the actual information to the left. Now you need to scroll down to see the information (like name, etc).

**Comment by kkbrum** [comment]
Trying to replicate it on my server and it seems to be fine, so I guess it's a Yale thing? The difference is just that the "View: <program>" is to the right of the photo instead of beneath it.

**Comment by kkbrum** [comment]
I launched my server from the yale-sr10 branch and still cant replicate it, and i dont think we have a template override set for that page...

**Comment by benjaminjkraft** [comment]
Could be custom CSS, or a part of your template override of main.html?  You can probably find out where the CSS is coming from by comparing the yale one to your local one using "inspect element" -- just find what css they have that differs.

**Comment by willgearty** [comment]
We've had this problem for years at Stanford. If you can figure out what is causing it, that would be awesome. I've noticed that it's fine for some users and for others it is all wonky like this.

**Comment by willgearty** [comment]
Now that I've looked into this, I think we just need to limit the width of the `div#user-sidebar` in userview.css. While we're at it, I think we should add a right border to the links. At least at Stanford we don't have the blue border on the right which fills it in in this theme.
