### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2576]
I realized we don't have an issue to track this!  Python 2 hits end of support on Jan 1, 2020, and Django 1.11 will be the last series to support it.  Also, python 3 is great and has lots of nice things in it.  This issue is to track our upgrade path.

**Comment by hwatheod** [comment]
Running `[caniusepython3](https://pypi.org/project/caniusepython3/) -r requirements.txt` gives the following output

[WARNING] Skipping u'git+https://github.com/luac/django-argcache.git@0.1 ': could not parse requirement
Finding and checking dependencies ...

You need 2 projects to transition to Python 3.
Of those 2 projects, 2 have no direct dependencies blocking their transition:

  django-selenium
  pydns

**Comment by hwatheod** [comment]
The `argcache` dependency was specified in a different format so the tool couldn't parse it. But it looks like it was written by LU people so we should be able to find out if it's Python 3 ready.  Of the other two blocking dependencies mentioned above,

django-selenium: The requirements file says "Runs selenium tests which probably don't work anymore". Are they working? Can we get rid of it?

pydns: This is used for validating email addresses entered by users. While a nice feature, it's not absolutely critical.

**Comment by milescalabresi** [comment]
Doing some reading, we'll want to use the `six` and `modernize`/`futurize` packages. Some useful checklists:
- https://www.stxnext.com/blog/python-3-migration-guide/
- https://blog.couchbase.com/tips-and-tricks-for-upgrading-from-python-2-to-python-3/
- https://www.techrepublic.com/article/migrating-from-python-2-to-python-3-a-guide-to-preparing-for-the-2020-deadline/
- https://docs.python.org/3/howto/pyporting.html

**Comment by willgearty** [comment]
> pydns: This is used for validating email addresses entered by users. While a nice feature, it's not absolutely critical.

Looks like there is a python 3 version: [py3DNS](https://launchpad.net/py3dns)

**Comment by willgearty** [comment]
There's also the 2to3 tool: https://docs.python.org/2/library/2to3.html

**Comment by willgearty** [comment]
> django-selenium: The requirements file says "Runs selenium tests which probably don't work anymore". Are they working? Can we get rid of it?

Looks like you don't even need this package anymore as of Django > 1.5 ([source](https://github.com/dragoon/django-selenium)):

> This library is not needed for Django > 1.5, please use built-in functionality

**Comment by milescalabresi** [comment]
Fixed by #3616
