### ISSUE TITLE
Missing teachers page overlaps instructions with class search and administration links in fruitsalad theme

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2605]
There are a useful set of instructions/ keyboard shortcuts on the onsite checkin teachers page, but they overlap the class search and the links to the backend, so I can't press the link to the admin pages from here.

![image](https://user-images.githubusercontent.com/25392075/44175227-8540b280-a0b3-11e8-8fce-df4f7a8153d8.png)

**Comment by willgearty** [comment]
Would a reasonable fix be to move one of them to the other side of the screen? Alternatively, we could put the missing teachers thing at the middle or bottom of the left side?

**Comment by kkbrum** [comment]
I think either one of those would be fine!
