### ISSUE TITLE
Broken teacher check-in

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2633]
Reported by Yale.

Getting the following error (in the django logs) when trying to load any teacher check-in pages:
```py
Traceback (most recent call last):
  File "/lu/sites/yale/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/lu/sites/yale/esp/esp/web/views/main.py", line 101, in program
    newResponse = ProgramModuleObj.findModule(request, tl, one, two, module, extra, prog)
  File "/lu/sites/yale/esp/esp/program/modules/base.py", line 208, in findModule
    return getattr(moduleobj, call_txt)(request, tl, one, two, call_txt, extra, prog)
  File "/lu/sites/yale/esp/esp/program/modules/base.py", line 482, in _checkAdmin
    return method(moduleObj, request, *args, **kwargs)
  File "/lu/sites/yale/esp/esp/program/modules/handlers/teachercheckinmodule.py", line 379, in missingteachers
    prog, date, starttime, when, show_flags)
  File "/lu/sites/yale/esp/esp/program/modules/handlers/teachercheckinmodule.py", line 331, in getMissingTeachers
    teacher.phone = teacher_phones[teacher.id]
TypeError: <lambda>() takes exactly 1 argument (0 given)
```

Not seeing this same error on Stanford's teacher check-in pages.

**Comment by willgearty** [comment]
Not a problem for Yale's Sprout Fall 2018, so must have something to do with a specific teacher for Splash Fall 2018.

**Comment by milescalabresi** [comment]
This came up today at NEU's Splash. The problem is [here](https://github.com/learning-unlimited/ESP-Website/blob/main/esp/esp/program/modules/handlers/teachercheckinmodule.py#L196), and I think Hari is right. When a co-teacher is added later in the game with an incomplete profile (missing phone number), the function I linked to doesn't know how to handle having no information. I think the fix is to add error handling to the function so that it will pass a blank instead of assuming there's an entry in the dict.

**Comment by willgearty** [comment]
That function should be able to handle missing phone numbers:
https://github.com/learning-unlimited/ESP-Website/blob/77dbf1a95d3d02de9813be93c614d9140bcfdf7b/esp/esp/program/modules/handlers/teachercheckinmodule.py#L217
I think what might be the problem is if teachers are missing entire Registration Profiles, they aren't included in the return from the get_phones function. Then we error when we can't find the user here:
https://github.com/learning-unlimited/ESP-Website/blob/77dbf1a95d3d02de9813be93c614d9140bcfdf7b/esp/esp/program/modules/handlers/teachercheckinmodule.py#L313

**Comment by willgearty** [comment]
We should just use `get` instead of `[]`.
