### ISSUE TITLE
GUI for QSD/Editible text creation

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2652]
The average admin is not overly familiar with HTML or Markdown, and the code-like syntax can be intimidating. It would be neat if we could have a more GUI-like interface (such as the one GitHub uses) for basic text formatting, link insertion, and graphics addition. Not a high priority, but probably a useful tool for many users

**Comment by willgearty** [comment]
Is there a particular package that would be easy to implement?

**Comment by willgearty** [comment]
This one seems good, flexible, and free: https://github.com/quilljs/quill/

**Comment by willgearty** [comment]
As an update, that one wasn't actually that great. It didn't support a lot of HTML tags, and it was really hard to just edit the HTML itself. Currently looking into alternatives, but a lot of them require more recent versions of jQuery or Bootstrap.

**Comment by willgearty** [comment]
I've also realized that we already have one integrated on the .edit.html pages, but it's pretty ugly and limited IMHO.

**Comment by willgearty** [comment]
Currently working on implementing [this one](https://xdsoft.net/jodit/play.html?enter=BR&defaultMode=1&toolbarSticky=false&height=500).
