### ISSUE TITLE
Generating Student Schedules says there are no students when there are, in Basic List

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#2658]
Duke Splash is observing this bug:

Go to their Fall 2018 program
Generate Printables -> Student Schedules
Basic List
Unselect "email all students" -> Continue
Select "students who are enrolled in at least one class" -> Continue

There is an error that LaTeX generated no output because there were no students.  But there are students.

But it works with "Combination List".

**Comment by hwatheod** [comment]
Discovered that the user's browser auto-filling her username as a filter for some reason. It was hidden in the dropdowns so it wasn't apparent until you opened the dropdown. After removing the auto-fill, got an Internal Server Error instead.

**Comment by willgearty** [comment]
I just followed the steps above and got the expected schedules for 337 students (correct according to the dashboard as of this post). Worked for the "Student Schedules", "PDF", and "TEX" links. I also opened a separate issue for the autofill issue (#2680).
