### ISSUE TITLE
UI for program settings

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2659]
Consensus from SplashCon 2019 is that very important program settings should not be hidden in the admin panel. We need a UI for altering these settings so admins don't need to worry about sifting through the admin pages. Such settings include:

- Capacity options
- Open reg
- Cancellation
- Class capacity multiplier/offset
- Cancel button/message

**Comment by benjaminjkraft** [comment]
Yeah, it would probably be a good idea to have an overall program settings page that abstracts over the various messy implementations of:
- settings that live on the program itself
- choosing and configuring program modules
- CRMI and SCRMI
- choosing class categories
