### ISSUE TITLE
Blank spaces in catalog

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2697]
There are a bunch of weird blank spaces in our catalog for some reason.

![image](https://user-images.githubusercontent.com/25392075/54093786-ac254580-4371-11e9-9bd2-b7557f5f59ba.png)

**Comment by willgearty** [comment]
When did you first notice these blank spaces?

**Comment by kkbrum** [comment]
This program-- Splash Spring 2019!

**Comment by willgearty** [comment]
Do you notice the problem for previous programs?

**Comment by kkbrum** [comment]
The past Splash programs seem to have some weird gaps as well, but not as large as for this program

**Comment by willgearty** [comment]
Hmm...I don't see this in the Splash Spring 2019 catalog anymore? I've tried being signed out and signed in.

**Comment by kkbrum** [comment]
I am signed in and looking around class 3772 (https://yale.learningu.org/learn/Splash/2019_Spring/catalog#class_3772) and still see spaces :(
