### ISSUE TITLE
Some userview links should depend on user type, not profile infos

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2720]
@kkbrum reported that the following lines didn't work on her dev server when she looked at an account that was a Teacher, Admin, and Student. This is probably due to the fact that we're pulling this from the profile associated with a specific program. So, for example, if a student becomes a teacher, they shouldn't have `teacher_info`s for programs in which they were a student (because they weren't a teacher yet and they wouldn't have been prompted to fill out that profile info), so if you selected one of those programs, these if statements would fail. Ultimately, that's probably the correct behavior for some of the userview links (e.g. we don't want to show a teacher schedule link for a program in which a user was not a teacher), but other links should probably be displayed just based on the user types of the user (like the teacher biography link). Someone should go through all of the userview links and figure out which links should have which behavior. For things that should depend on user type instead of profile infos, we could just do something like `{% if "Teacher" in user.getUserTypes %}`.

https://github.com/learning-unlimited/ESP-Website/blob/09ff26dcce8042b829d012c07bbd36fa0f7aa95a/esp/templates/users/userview.html#L33-L35

https://github.com/learning-unlimited/ESP-Website/blob/09ff26dcce8042b829d012c07bbd36fa0f7aa95a/esp/templates/users/userview.html#L97-L109

**Comment by kkbrum** [comment]
Even though the "Update profile" in teacherreg was checked off before, I went to it again and updated it and now the correct items show up for my account.

**Comment by willgearty** [comment]
OK, I still think we should be treating some of these links differently. Some of them are program dependent, so we only want to show them if a user is definitely involved in that program. Some of them are not program dependent, so we just want to show them if a user is a particular user type.
