### ISSUE TITLE
Profile form doesn't prioritize infos correctly

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2721]
This definitely needs to be looked into, but I'm pretty sure the profile form isn't showing all of the necessary infos. My hunch is that you can never see both the student and teacher infos, but the student info has priority, even if you are now a teacher?

**Comment by kkbrum** [comment]
AH sorry my bad, I checked this and it looks like all the correct infos do show up depending on if its studentreg or teacherreg.

**Comment by willgearty** [comment]
What about in the normal profile form at `/myesp/profile` @kkbrum?

**Comment by kkbrum** [comment]
Oh. Yes, that page only gives me the student infos sections even though I am both a student and a teacher. We should fix that.

**Comment by willgearty** [comment]
Ah, yeah, that's a problem. I think we can make the assumption that in normal cases (i.e. not admins or dummy accounts), if a user has both the student AND the teacher usertypes, they probably were a student before and are now a teacher, so we probably want to check if they are a teacher BEFORE we check if they are a student? Or should we just show both?

**Comment by kkbrum** [comment]
Hm. Maybe for an admin we would show the infos for all their account types, but for teacher/student accounts, just show the teacher part.

**Comment by willgearty** [comment]
OK, I fixed the main concern here in #2749, and I moved @kkbrum's request regarding admins, etc. to #2748.
