### ISSUE TITLE
Class search shows in fruitsalad admin toolbar even if class search module is not enabled

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2751]
While testing for SR11, I noticed that the class search part of the admin toolbar was being shown even though that specific program did not have the class search module enabled. Using the search box results in an error page (understandably). We should double check the module exists for the program before adding that search bar to the admin toolbar.

**Comment by kkbrum** [comment]
@willgearty  helllppppp 

I added an if statement to check for the module in the only relevant code I could find, but it a) didnt fix the problem and b) didnt break anything. Commit is located [here](https://github.com/learning-unlimited/ESP-Website/commit/3372cf07a49e2931c0d39ede16844d5a846632b5). I tried fab refreshing since I'm not sure how to make the scripts take effect but it didn't do anything. Am I even looking at the right file?

**Comment by willgearty** [comment]
It's a theme file, so you'll need to update the theme for the changes to take effect.

**Comment by willgearty** [comment]
Also, `currentPrograms` is just a list with info about the program `niceName` and program `urlBase` that is assembled here:
https://github.com/learning-unlimited/ESP-Website/blob/184d49243f0c66d0c0d29f4ade97f1b23d7484c3/esp/esp/themes/theme_data/fruitsalad/templates/main.html#L77-L84
You'll probably just want to add another dictionary entry there for each list item (each program) that says whether the program has the class search module (also, keep in mind you use | to specify a parameter to a function when using the django variables in a template, e.g. {{current_program.hasModule|"Class Search"}} or whatever).

**Comment by willgearty** [comment]
Sorry, I lied, that's only for built-in template tags. You'll either need to

1. Write a [new template tag](https://docs.djangoproject.com/en/1.8/howto/custom-template-tags/) that accepts the module name and returns True/False, or
2. Add a field to the program db objects before they are sent to the template: 
https://github.com/learning-unlimited/ESP-Website/blob/184d49243f0c66d0c0d29f4ade97f1b23d7484c3/esp/esp/utils/web.py#L75

**Comment by willgearty** [comment]
I did the former in https://github.com/learning-unlimited/ESP-Website/pull/2712 if you need an example.

**Comment by kkbrum** [comment]
Okay but the filter already exists [here](https://github.com/learning-unlimited/ESP-Website/blob/9147b7912921642812fa3fc4bfdbca35eaac9665/esp/esp/program/templatetags/modules.py) and has been used [here](https://github.com/learning-unlimited/ESP-Website/blob/29afaae743e228f42b82f1f67d2b9d7b85e2103d/esp/templates/users/userview.html) so I don't think I need to remake it? But I get an invalid filter error so clearly somethings not right. Do I have to load in the template tag filter library somehow?
