### ISSUE TITLE
Add scrollbar to template tags list in comms panel

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2763]
The email WYSIWYG editor's pulldown menu extends below the bottom of the window so that some entries are almost impossible to reach. It should have a maximum height that keeps it in the window and use a scrollbar to reach lower-down entries.
![image](https://user-images.githubusercontent.com/5506191/59728528-76151e80-9208-11e9-88d5-84e43dd895ac.png)

**Comment by willgearty** [comment]
I'm not sure this is "Easy", but I'll take a look when I get a chance.

**Comment by willgearty** [comment]
Looking at your picture, it looks like you can actually scroll down on the page to reveal the other options?

**Comment by milescalabresi** [comment]
The page doesn’t have focus so if you scroll, it doesn’t go down, and if
you click to return focus, the pulldown goes away

**Comment by willgearty** [comment]
Hmm, I don't have that issue, the page seems to scroll fine even when focused on the dropdown.
Anywho, I've come up with two possible solutions:

1. Set a minimum height for the text box such that the page is always long enough to show the entire dropdown.
2. Set a static maximum height for the dropdown (as you suggested).

**Comment by willgearty** [comment]
Actually, 150px looks pretty good, so I'm just gonna go with that.

**Comment by willgearty** [comment]
And it did end up being pretty easy :P
