### ISSUE TITLE
Reformat/prettify scheduling diagnostics

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2764]
The scheduling diagnostics page is dense and difficult to read.
![image](https://user-images.githubusercontent.com/5506191/59729069-bd9caa00-920a-11e9-8060-0624a8704220.png)

In particular, I propose

- adding more obvious expand/collapse button
- adding more space between each diagnostic
- sorting them into categories
- making more use of the horizontal space to avoid having the long single column
- changing the list of users (e.g. for the "Admins teaching per timeslot" check) to use names in addition to usernames and not list them with quotes and brackets

**Comment by willgearty** [comment]
It looks a lot better on the Stanford site (and the Yale site looks the same, too). I don't think it's a template override, so maybe this is a problem with the bigpicture theme?

![image](https://user-images.githubusercontent.com/7232514/59969841-aa405600-950c-11e9-9e02-9da356121a4d.png)

**Comment by willgearty** [comment]
(but I still think we can do better with the things you suggest)

**Comment by milescalabresi** [comment]
Oh, you're right. I hadn't seen that version. But yes some of the bullet points are still valid but lower priority asks

**Comment by willgearty** [comment]
@nrjean, first priority here is to fix this page on bigpicture, but @milescalabresi has also suggested some broader changes that could be nice for this page.

**Comment by willgearty** [comment]
Never mind, looks like a file was missing on STING's site. So there is NOT a bug with bigpicture.
