### ISSUE TITLE
Check for availability checker module before linking to conflicting teacher's edit availability

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2786]
On the setting teachers admin page, if a user has a conflicting availability, I made it link to their edit availability page a while ago, but if the availability checker module is not enabled we should remove that link (otherwise you get a nice broken link oops)

**Comment by kkbrum** [comment]
I think (?) the module needs to be checked before linking in all of the following files:
- https://github.com/learning-unlimited/ESP-Website/blob/8ddfac673e5d082c72b9ff42f0fb4fe2bd02ad61/esp/templates/program/modules/adminclass/classavailability.html#L45
- https://github.com/learning-unlimited/ESP-Website/blob/8ec53744eecfc9b74b11521938b63ea2aaa2a679/esp/templates/program/modules/adminclass/coteachers.html#L29
- https://github.com/learning-unlimited/ESP-Website/blob/9e1a7418ea89164921466b4970448b2d4fa5d090/esp/templates/program/modules/availabilitymodule/availability_form.html#L106

Also, @willgearty  would it be possible to instead of landing on a 404 error page, to land on a page saying "please enable ____ module for the program to access this page"?

**Comment by willgearty** [comment]
I'm not actually sure if the website _knows_ which module you need to enable if it isn't enabled.

**Comment by willgearty** [comment]
Maybe @benjaminjkraft or @hwatheod knows?

**Comment by hwatheod** [comment]
Unfortunately, I don't know how the website can figure out which module needs to be enabled, or even how you figure out if a specific module is enabled (the latter would be enough to hide the link).  @benjaminjkraft  ?

Incidentally, the whole idea of having to enable modules is a little bit weird, since most features ought to be enabled by default, or even if they are experimental right now, there should be some way for them to eventually become default if they turn out ok. Even if not used, enabling doesn't cause any harm, as far as I can tell, and avoids issues like this one. Maybe a few things like credit card or texting should be disabled so they are not accidentally used but that does not apply to the vast majority of features.

**Comment by willgearty** [comment]
Well, I know we can use `prog.hasModule("moduleName")` to check if a program has a particular module enabled, which I believe @kkbrum is alluding to in the first and second posts here, but yeah, I'm not aware of a way to figure out which module a view comes from if that module isn't enabled.

In terms of enabling all modules, I'd be worried that that could theoretically cause confusion among admins (especially at newer chapters). It's usually easiest to work with the fewest options possible when they are starting up. Also, personally, if I'm never going to use an option, I don't see the point in having it available (if I can disable it). However, I can think of a few modules that should probably be enabled by default for all programs, especially if they are dependencies of other modules. This has been discussed a couple times before, and @mgersh even mentioned she was working on this: https://github.com/learning-unlimited/ESP-Website/issues/608#issuecomment-168598701.

**Comment by benjaminjkraft** [comment]
> which module needs to be enabled
I don't remember offhand, but I think it's common to just hardcode the name in a case like this.  There may not be an easy way to do it if the module is not enabled; in fact there may not even be a unique module providing a view!

> how you figure out if a specific module is enabled
Yeah, this is `prog.hasModule` as @willgearty says.

> the whole idea of having to enable modules
I thought about this a bunch a couple years back -- I think I have a WIP branch (#2125) starting to attack the problem.  The current setup accomplishes several effects which are certainly necessary, at least:
1. constructing the studentreg/teacherreg checklist, and the list of manage pages; and allowing program- or module-level configuration of the same
2. enabling and disabling certain pages, and other functionality (like the link referenced in this issue)
3. auto-routing certain views with standard URL parameters
4. a way of organizing code (handlers, templates, etc.)
The current setup accomplishes all of these by dynamically importing code based on configuration, which is definitely not the best way to do it.  And certainly the current configuration process is garbage UX.  But I think many of the individual things that it causes are necessary or useful.

I think to fix this up, the way to go is
1. fix up some of the incidental or historical quirks of the current system, like the fact that the class on which the handlers live is the same as the config model in the db, the "double modules", the dynamic imports, and others (this is what my #2125 was working on)
2. separate auto-routing out of the rest of the system -- many of the modules don't need to be disableable or have any of that stuff and so they should just have some decorator which wires up the view parameters and call it a day (this requires a ton of refactoring, which will be much easier after (1) is complete)
3. refactor the enable/disable system to simplify what's left after (2) is separated
There's a parallel issue of making a better UI around either the current program modules system and/or whatever might replace it; this could probably be done at any time although it would be simpler after.

To be clear, I'm not gonna work on any of this -- anyone who wants to should feel free to steal my branch and/or bug me (preferably on slack/gchat, I'm hit-or-miss at replying to github these days) for thoughts on how to do it.
