### ISSUE TITLE
Generic registration links

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2793]
It would be cool to have a link like `[site].learningu.org/Splash/studentreg` that would take you to the student registration page for the most "current" program (a la #2234 and #2504). It could even use the "Splash" bit to determine which type of program you want (in case there are multiple programs at the same time like at MIT or Yale), such that you could have e.g. `[site].learningu.org/Splash/studentreg` and `[site].learningu.org/Sprout/studentreg` and they would always link to the most current "Splash" and "Sprout" programs, respectively. This would hopefully also work for teacher and volunteer registration.

I'm not really sure how this would work, but it'd be really cool and a great way to make sure links stay current.

**Comment by willgearty** [comment]
Hmm...maybe an easier way would be to have the link be something like `[site].learningu.org/Splash/current/studentreg` so the link still has the same number of components?

**Comment by willgearty** [comment]
@kkbrum suggested that we could use redirects for this and just create/update 3 redirects (learn/studentreg, teach/teacherreg, volunteer/signup) each time a new program is created. We could use the "Program Type" field of the new program form to customize the redirects to accommodate programs that are co-occurring. This would be a fairly simple thing to implement, but I'm worried about the "hacky" nature of it. I suppose this way it does allow the chapter to alter the links if they'd like, rather than being hardcoded in the urls code or something. And it'd be no more "hacky" than tags, which we use all the time for customizing things.

**Comment by hwatheod** [comment]
I like the idea of "Splash/current". Even better would be for "Splash/current" to generalize beyond registrations to the entire site, e.g., for the link to the admin dashboard. This would solve the problem of having to update a whole bunch of links for each new iteration of a program.

**Comment by willgearty** [comment]
Yeah, I think a more general system of `[site].learningu.org/[tl]/[one]/current/[view]` could be really useful, but that would really require something outside of just redirects (it wouldn't be tractable to create redirects for every single view). However, given that it follows the same URL format, I feel like it shouldn't be super hard?

**Comment by willgearty** [comment]
Actually, this should be super simple. We just need to catch the "current" (which is `two` here) before we look for the program here:
https://github.com/learning-unlimited/ESP-Website/blob/4e5b5b9a3cb1af2f5f0d641e5086be7a68346e51/esp/esp/web/views/main.py#L84-L91

If `two` is "current", then we just use similar code as in #2234 to pick the most current program.
