### ISSUE TITLE
Double program charge

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2838]
Reported by Yale: Students being charged for program twice. This time stamp isn't even in the mad rush at the opening of student registration which surprises me. Is there a way we can keep this from happening?

![image](https://user-images.githubusercontent.com/25392075/69009333-463a8600-0922-11ea-9211-305f8ce91c38.png)

**Comment by hwatheod** [comment]
On the Stripe side, this shows up as a single $40 payment. I will refund this student $20.

**Comment by hwatheod** [comment]
In all, I found 8 students for Yale Fall Splash 2019 that had duplicate accounting transfer entries for 'Program admission'. Of these, only the student above actually paid by credit card via Stripe, so there were no other credit card refunds issued.

**Comment by kkbrum** [comment]
Thanks for checking! 8 is quite a few; it would be great if we put some sort of check in place to either prevent duplicate program admission entries or automatically delete them when they happen.

**Comment by hwatheod** [comment]
Some other schools also had duplicate payments. I will find them all and refund the ones that paid through Stripe.

**Comment by willgearty** [comment]
This looks like another instance of https://github.com/learning-unlimited/ESP-Website/issues/2737

**Comment by willgearty** [comment]
I'm guessing this is due to people clicking some button again before the server has processed the first click (when do we assign a program admission charge to a student?), very similar to the duplicate program bug.

**Comment by hwatheod** [comment]
If a button was clicked twice, I would expect it to show up as 2 separate payments in Stripe, but instead it's showing up one payment in Stripe with double the amount.

I'm not totally unclear on the admission charge but I think it's coming from the `ensure_required_transfers` function in the `IndividualAccountingController` class (in `esp/esp/accounting/controllers.py`).  It seems like there is logic there to check for each required item (like program admission), and we only add it if it doesn't already exist. So I'm not sure how duplicates happen.

**Comment by willgearty** [comment]
I think the one payment in Stripe is just a result of the site collapsing all receivable to one charge. In the original post by @kkbrum there are clearly two program admission charges, so that's why I'm thinking the student clicked the button twice, but if it's checking that program admission doesn't already exit, the second click shouldn't have done anything?
