### ISSUE TITLE
Discuss: onsite classchange grid shouldn't mark as attended

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2839]
NEU brought up the fact that the onsite grid is a simple and useful interface for making changes to student class registrations (much faster than morphing, using /admin/, or other pre-event alternatives). Should we be using it more and remove the quirk where it checks in students as attended if you use it to change their schedule? Or should we make it more powerful and add a checkbox to turn on/off the "mark as attended" feature so that it can still have that benefit on the day of the program

Keywords: class change changes grid onsite classchangegrid

**Comment by willgearty** [comment]
Fixed by https://github.com/learning-unlimited/ESP-Website/pull/3476.
