### ISSUE TITLE
Clarify student phone number field

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2863]
For information like the phone number in the student profile, often the parent phone will get put in. I think it might make sense to make it more clear that the cell phone we are asking for is the student phone. Maybe we could add a yellow box like there is above the email address field and have it say "Students: Please put in your cell phone information, if you have one. If not, please leave this field blank. There will be a field for parent phone numbers in the parent section." Also I think we could rename the whole section from "Contact information" to "Student contact information" since often parents will put in their names instead of the student names as well.

This is useful for Yale splash who needs student cell phone numbers.

**Comment by willgearty** [comment]
I think those fields are used for all user types, so you wouldn't want those things hard coded. Maybe inject the user type into the template?
