### ISSUE TITLE
Take Onsite Program Class Attendance 

### ISSUE THREAD

**Issue by jacklat** [learning-unlimited/ESP-Website#2864]
This is a request from Yale Splash for the ability to more easily gather student attendance information within classes. Subject to a conversation with our Risk Management office, we will be required to do this beginning with our Sprout program on February 15th. As such, we need the ability to collect attendance by the beginning of February in order to comply with their requirements. 

We were asked to come up with an ideal solution and a workable one and have done so in this [document ](https://docs.google.com/document/d/1AjjBSdi0r8YcS-XiL3ibwZUmcLVMLLtE30iotsW-D_o/edit?folder=1fYqaQl5F1bAlsXQ2LB6-84DAXDI1RX1x) (it's long so we are linking it rather than copying and pasting directly into GitHub). We know that both solutions are somewhat convoluted and, as such, are also open to other ideas that people might have as long as they have the same functionality of identifying missing students and students who have class-changed themselves. The most important thing is that we have a system that functions and is usable by both us and teachers in advance of our next program on February 15th. 

Another related issue that we thought would be very helpful is generating barcodes on the back of student nametags (as any system would likely involve scanning students, and it may be more convenient to scan nametags rather than student schedules and would also be helpful in case students lose their schedules). I can also turn this part into a separate request if that would be more convenient (it's also possible that this is something we could do ourselves with template overrides--I am not entirely sure whether that's within its capabilities, and, if so, we would appreciate guidance in creating that override). 

Thanks so much in advance for your help!

**Comment by willgearty** [comment]
Please move the second request to a separate GitHub issue @jacklat.
