### ISSUE TITLE
Barcodes on the Back of Student Nametags

### ISSUE THREAD

**Issue by jacklat** [learning-unlimited/ESP-Website#2873]
It would be helpful to us (Yale program) to have barcodes on the back of student nametags. This would be paired with the new attendance system (https://github.com/learning-unlimited/ESP-Website/pull/2868) as if the new attendance app allows for scanning into the website (which, again, ideally it would for us if it's possible to put that in), it may be more convenient to scan nametags rather than student schedules and would also be helpful in case students lose their schedules. It's also possible that this is something we could do ourselves with template overrides--I am not entirely sure whether that's within its capabilities or not (if it is, we would appreciate guidance in creating that override).

**Comment by willgearty** [comment]
First of all, yes, the attendance page for teachers does allow for barcodes to be scanned using phones (or barcode scanners) (see details in https://github.com/learning-unlimited/ESP-Website/pull/2868). Second, modifying the nametags as you are describing should be moderately easy to do as a template override:

1. Make a template for the backs of the nametags. You'll want to model it after the fronts: https://github.com/learning-unlimited/ESP-Website/blob/main/esp/templates/program/modules/nametagmodule/singleid.html. The nametags are in HTML, so you'll need to find a way to make a barcode in HTML (this looks useful: https://www.codeproject.com/Articles/146336/Creating-a-Code-39-Barcode-using-HTML-CSS-and-Java). Name the template override "program/modules/nametagmodule/singleidback.html". Proceed to step 3.
2. Alternatively, you could override the front template and insert the barcode in there if there's space, then proceed to step 4.
3. If you want to have backs for your nametags, you'll need to make an override for the overall nametags template (https://github.com/learning-unlimited/ESP-Website/blob/main/esp/templates/program/modules/nametagmodule/ids.html). In this template, we loop through the users in groups of 6 (then make a page break). The tricky thing here will be to figure out how to then loop through the same six users for the backs. It might make sense to have some JavaScript inline that builds an array with the user IDs as you go through the first time. Then loop through the array when you are building the backs (you'll want to use {% include "program/modules/nametagmodule/singleidback.html" %} to include the template override you just made in step 1). Then clear the array and move to a new page to make the next fronts. A hacker alternative method would be to make all of the backs after making all of the fronts. Then either a) use some software to interleave them or b) split the file and send them to your printer as separate files and ask them to print them as front and back. Proceed to step 4.
4. Use the nametags module as usual.

**Comment by jacklat** [comment]
Hi @willgearty , thanks so much for all of your comments/thoughts. Those are really helpful! I'll do some work on this over the semester and then Avi (another admin and co-president) and I will likely finish it over the summer if I don't complete it before then. However, I did have a few initial questions (and I apologize if these are really obvious as I've never made my own template override before): 

1) Is there any way to preview the code output for the single ID/single ID back? (so I can check whether it's working as I code it and make changes accordingly). Or do I need to integrate this code with the overall nametags template first in order to see the changes? 

2) Is there documentation for the website somewhere that lists out some of the attributes that can be included in the code? For instance, the singleid template you linked included attributes such as "user.title","user.username", and "user.id". I was just wondering whether there's a comprehensive list of these elements and/or other website documentation somewhere. 

I think those are my main questions for now although more might arise as I start coding. Thanks so much!
