### ISSUE TITLE
Email blocklist

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2883]
Allow users to add their email addresses to a blocklist that will be used to filter emails before sending any comm panel emails. Admins at SplashCon suggested that a link be added to all comm panel emails that takes users to a page where they can enter their email address. A confirmation email would be sent to them with a specific link (with some sort of key) that they would use to confirm the addition of their email address to the blocklist.

**Comment by kkbrum** [comment]
Does the recent overhaul of unsubscribe links in emails make this issue obsolete? (Or am I misinterpreting what a "blocklist" is?)

**Comment by willgearty** [comment]
Yes, I believe so!
