### ISSUE TITLE
Onsite class changes: Allow hiding walk-in seminars

### ISSUE THREAD

**Issue by dehnert** [learning-unlimited/ESP-Website#289]
At the moment, since walk-in seminars (at least for Spark 2012) don't show up as categories associated with the program, they also don't show up as a category filter for the class changes grid (ie, https://esp.mit.edu/onsite/Spark/2012/classchange_grid), which means walk-ins always show up. There should be a way to hide them, possibly defaulting to hidden.

**Comment by benjaminjkraft** [comment]
This appears to be an issue again.
