### ISSUE TITLE
Self check-in

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2892]
Theoretically, a student might have already completed all check-in tasks before arriving at a program, for example:

1. Paid online
2. Filled out waiver online (formstack/DocuSign module yet to be implemented)
3. Using webapp for schedule/map (don't need printed schedule/map)

In this case, these students should be able to check themselves in (maybe scan a qr code or use a code on a site or something), probably through the webapp

**Comment by willgearty** [comment]
After chatting with @milescalabresi and @kkbrum, here's what we need:

1. A tag that specifies whether self checkin requires a unique code or not
2. If a unique code is NOT required, then students just need to go to a page with a checklist. If the whole checklist is done, they can click a button and they are checked-in and are taken to the webapp
3. If a unique code is REQUIRED, then students will need a code for the same page. This code could be provided with a short hash code that they need to enter or via a QR code that they scan that adds a GET parameter to the URL.
4. There would then be an option to include such hash codes/QR codes on the backs of student nametags.

**Comment by willgearty** [comment]
test

**Comment by marciatorresg** [comment]
Hii, I am a future applicant to the GSoC 2026, @willgearty if you allow can I get this assigned ? Or is already assigned to someone else?

**Comment by willgearty** [comment]
@marciatorresg this issue is already closed.
