### ISSUE TITLE
Automated text-message-sending UI

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#29]
We have a Comm Panel.  We also have a mechanism (a Program Module, I think?) to gather students' numbers to receive text messages.  It'd be nice if you could use an interface like the Comm Panel to send text messages to people.

Or, possibly, some other interface; I think the initial set of sets of people who'd want to be able to receive text messages is comparable to the set of Mailman lists?

**Comment by milescalabresi** [comment]
Closing, as #812 is finished.
