### ISSUE TITLE
Can't move classes vertically in scheduler

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2902]
I'm not sure when this bug was introduced, but it seems to be a regression since SR11. On my dev server I have a class with a single teacher. I scheduled one of the sections in a classroom. However, now I can't move that section to another classroom in that timeslot, with the error "Error: The teacher Will Gearty has not indicated availability during Mon 2:00pm--2:45pm." I can move the section to another timeslot no problem, then move it back no problem, so I'm not entirely sure what's going on here (you used to be able to do this). This might need some reproduction on the main branch.

**Comment by hwatheod** [comment]
This sounds like perhaps the availability checker thinks that because there's already a class scheduled for 2-2:45pm for that teacher, that time slot this not available and hence you can't move it to another room for that time slot.

**Comment by willgearty** [comment]
Probably related to changes made in https://github.com/learning-unlimited/ESP-Website/pull/2859?

**Comment by willgearty** [comment]
I've tracked down the problem to this commit: https://github.com/learning-unlimited/ESP-Website/commit/09b4805f21e843a98f19f6ff27f074f565b109c7
