### ISSUE TITLE
Ban Changes into Certain Classes on Web App

### ISSUE THREAD

**Issue by jacklat** [learning-unlimited/ESP-Website#2908]
Another request from Yale Splash--We would like to be able to prevent students from class changing themselves into certain classes on the web app (some classes contain sensitive material and require a waiver while others move locations). If that feature could be added so admins could prevent changes into certain classes, that would be great (we don't necessarily need it for Sprout/can just not have the web app for Sprout, but it would be great to have it by Splash on April 11th if possible).

**Comment by willgearty** [comment]
This should already be possible @jacklat. On the manage page for a class, at the very bottom you should be able to change the "Reg status" of a section. If you set this to "Closed", it should prevent students from enrolling from within the webapp (or anywhere else for that matter). Let me know if this is not the case.
