### ISSUE TITLE
Feature Request: Multiprogram Stats

### ISSUE THREAD

**Issue by nrjean** [learning-unlimited/ESP-Website#2922]
Page that would allow admins to pull basic statistics from multiple program and output them.
This would allow admins to generate graphs of trends over multiple program without having to go to each program and run the statistics individually. Example output of this could look as follows: 

![image](https://user-images.githubusercontent.com/60372830/74598603-1b0b2400-5042-11ea-95a3-8eaf7e8edd0c.png)

**Comment by willgearty** [comment]
Maybe we should just broaden `/manage/statistics` to have other statistics (like teacher and class statistics)?

**Comment by willgearty** [comment]
And the output on the statistics page could be put in a nice table layout if applicable (or have a csv export option)

**Comment by willgearty** [comment]
Also, from a data science standpoint, the columns and rows in your example should probably be switched (columns should be variables, rows should be observations)
