### ISSUE TITLE
Per class survey results view for administrators

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2938]
I feel like admins should be able to see the per class survey results in some nice format!

**Comment by willgearty** [comment]
After discussing with @kkbrum, I think we probably want two additions (@kkbrum feel free to add or correct me):

1. A way to pick a specific teacher to see the results for their classes (this is already available with a GET parameter, so we just need to add a form to add the GET/POST parameter). It may also be useful to have a similar form to select an individual class or section, but that's possibly less useful.
2. A separate section in the survey review that aggregates per class survey results across all classes. I don't believe something like this is already implemented, so this would require new code.
