### ISSUE TITLE
Reload class changes grid when boxes checked that delete lots of classes

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2946]
The new class changes grid #2945 looks great on dev3, but when there are a lot of classes and you uncheck one of the categories or showing full classes, there ends up being a lot of white space:

![image](https://user-images.githubusercontent.com/25392075/79074652-9ba17600-7cbb-11ea-8928-4484f268986c.png)

In these instances, I think the grid should get redrawn so that the white space goes away. This isn't necessary for the checkboxes that just display different information, just the major removers of classes:
- show full classes
- show outside student's grade range
- categories

**Comment by willgearty** [comment]
So, now that I think about it, when those boxes are checked or unchecked, it just hides the boxes that are relevant (with `visibility: hidden`). So it would be a little more than just redrawing the grid, we'd also want to skip drawing those boxes when it is redrawn.

**Comment by willgearty** [comment]
After thinking about this for a little bit, I think the easiest way to do this would be to just sort the classes based on the checkboxes, then redraw the table, that way the visible ones should be at the top, and all of the rows with invisible classes would be below and collapse properly.
