### ISSUE TITLE
Search bar missing for adding modules through admin pages

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2948]
The new admin pages (#2923) does not have a search bar for adding program modules on the program/programs/___ page, and the box for the list of modules is also very small and not expandable at all, making it pretty difficult to add modules. A search bar like before would make adding program modules much friendlier.

![image](https://user-images.githubusercontent.com/25392075/79172910-0d64e700-7dc4-11ea-9c44-6bfbcdd9852e.png)
 vs old version:
![image](https://user-images.githubusercontent.com/25392075/79173044-72204180-7dc4-11ea-9bbb-0c4e1ad7082b.png)

**Comment by willgearty** [comment]
This is actually fine and looks like the old version on my dev server, so must be a problem with the setup on dev3 (missing dependency or css/javascript files maybe?).

**Comment by willgearty** [comment]
Yep, looks like there's a combination of files missing and maybe javascript errors:
![image](https://user-images.githubusercontent.com/7232514/79692927-913c2a80-822d-11ea-89b2-68db6396aee2.png)

**Comment by nrjean** [comment]
This does seem to be isolated to the actual server. I can confirm that my dev server looks fine for both this and #2955 

Looking at the js dependencies it looks like there are some missing from cloud that arn't missing in dev. Specifically files located at \esp\public\static\admin\js

Here are two screenshots that compare the dev to cloud:
![image](https://user-images.githubusercontent.com/60372830/81026107-fce5e080-8e46-11ea-8881-79839029eed5.png)
 
versus

![image](https://user-images.githubusercontent.com/60372830/81026125-1424ce00-8e47-11ea-9272-b875d2617683.png)

**Comment by willgearty** [comment]
This was due to old grapelli static files overriding the new admin/admin_tools static files. By default when we run `manage update` it only runs `collectstatic` but we actually need `collectstatic --clear` to get rid of the old files that are not needed anymore. The stable release script for SR12 now has this command included, and I've tested this on cloud and dev3 with success on both.
