### ISSUE TITLE
Check outs not updating grid based class changes/ AUL 

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2949]
Checking out students isn't immediately updating the relevant AUL/grid based class changes as it should from PR #2935 (tested on dev3). It does update after some time, but not within say ~10 minutes and not from flushing the cache.

**Comment by willgearty** [comment]
I just tested this again on my dev server, and it's definitely working as intended...

**Comment by willgearty** [comment]
Just tested this on dev3 and it works! I'm not sure what did it, but I ran `sudo -u www-data python esp/manage.py update`, `sudo service memcached restart`, and `sudo apachectl -k graceful`, and now the class changes grid updates with the correct attendance numbers!

**Comment by willgearty** [comment]
Maybe @kkbrum can double check just to confirm I'm not crazy.

**Comment by kkbrum** [comment]
If I run those commands on the dev3 folder in the server, I get updated results. But if I afterwards check out a new student (that was previously checked in), I still don't get the desired updates within a short time.

**Comment by willgearty** [comment]
Maybe @hwatheod or @benjaminjkraft has an idea of what's going on here?

**Comment by hwatheod** [comment]
What does the abbreviation AUL mean?

**Comment by hwatheod** [comment]
I created an account hwatheod on dev3, can somone make me an admin?

**Comment by kkbrum** [comment]
AUL = arbitrary user list, and I made you an admin!

**Comment by willgearty** [comment]
That's very strange. That page works for me. I just used the makeadmin page again to ensure you are have the proper permissions. Can you try again @hwatheod ?

**Comment by hwatheod** [comment]
1. How do I check a student out?  The only way I found was to go to "Checkin" -> "Advanced CheckIn" and then uncheck for "Attending" box.  Is that it?

2. What is expected to change in the AUL / grid based class changes when a student is checked out?

**Comment by kkbrum** [comment]
1. Sure, that works. Another option is to enable the module called "On-Site User Check-Out" and then under the on-site links, you'll see an option to check students out using a new interface Will created.

2. When you look at grid based class changes, the first number for a class is the "currently checked in" number, so if you then check out one of the students checked in to program & enrolled in that class, that first number should decrease by one.
For the AUL, there's a new list "students currently checked out of program", and that should include the student you just checked out.
