### ISSUE TITLE
"Work in progress" banner

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#297]
We could make a template that can be included in a main.html override (or something) that places a banner over the top of every page telling people that the code has been upgraded and to notify the appropriate parties in case bugs are found.

Suggested by Mike Shaw:
- develop a generic "Work in Progress" banner to put up after we massively upgrade a site
- it would let users know that we've just deployed new code, and instruct them to email the relevant -websupport (or wherever) lists with any bugs
- it would help with website frustration if people realize that there's active development going on when they see a bug

**Comment by bhorowitz** [comment]
Is this still relevant with the current testing going on before each stable release?
