### ISSUE TITLE
Automatically pull default values for tags

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#2990]
Right now, the `Tag.getTag` function requires you to specify the default value each time you call it.  But we have a catalog of tags with default values in the `tagdict/__init__.py` so there should be a way to pull it automatically in `Tag.getTag` without having the caller specify it each time (and possibly make a mistake).

**Comment by willgearty** [comment]
I think there might be one or two tags that might have different defaults based on the context (e.g. `catalog_sort_fields`), so we would still want a way to specify a default, but otherwise fall back to the default in the `tagdict` catalog.
