### ISSUE TITLE
"Accepted but hidden" sections show as "Rejected" in teacher registration

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#2992]
In the "Manage Your Classes" section of the teacher registration page, if a section has been marked as "Accepted but hidden" by an admin, the section will be listed as "Rejected" for the teacher (not the class, just the section).

![image](https://user-images.githubusercontent.com/7232514/81574941-110c6f00-936c-11ea-842f-810d5711ab01.png)

**Comment by hwatheod** [comment]
What is the desired behavior?  I've never understood what "Accepted but hidden" is meant to be used for.

**Comment by willgearty** [comment]
My understanding is you use "Accepted but hidden" if you want the class to be "Accepted" but don't want it to show up in the catalog/student registration? This seems most useful for testing, I suppose, although I guess you might want to have a class that only some students can attend or something?
