### ISSUE TITLE
Posting terms of service

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#2995]
We need to add terms of service to all sites ideally in a way that chapters will not be able to override. 

Katherine and Miles have the terms of service that the LU board approved (can share with whoever is working on this).

**Comment by willgearty** [comment]
For SR12, easiest way would probably just be an external link to the LU site. For farther down the line, sounds like you want something like this: https://github.com/learning-unlimited/ESP-Website/issues/2545.

**Comment by willgearty** [comment]
Where were you thinking of including the link for the moment, @kkbrum?

**Comment by kkbrum** [comment]
hm im not sure. 4 ideas:
1) bottom of the page next to:
![image](https://user-images.githubusercontent.com/25392075/83581774-be0e7d80-a50d-11ea-906a-946678aacb37.png)

2) Top right near the need help? 
![image](https://user-images.githubusercontent.com/25392075/83581815-d8485b80-a50d-11ea-868a-85100ada3243.png)

3) top left near contact info? 
![image](https://user-images.githubusercontent.com/25392075/83581838-e72f0e00-a50d-11ea-9a30-76ef698a8bd9.png)

4) in addition to whichever of the first 3 we think is appropriate, i think it should also be added to the text on the top of the create account page like "by creating an account, you agree to these terms and conditions" with the terms linked.

I think option 1 + 4 seems the most standard to me? @bhorowitz do you have thoughts?

**Comment by willgearty** [comment]
1-3 are all completely theme specific (for example, I don't think bigpicture has a copyright footer or the contact info section). I like #4 since that page should be uniform across all themes. The only issue is that users won't be able to find it once they make an account. Perhaps the page suggested by #352 would be a good place to also include it?

**Comment by milescalabresi** [comment]
I like option 1
