### ISSUE TITLE
Add UI for line item types

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#3023]
It would make extra costs (a.k.a. line items) such as lunch, shirts, photos, etc. more accessible if there were a UI where admins could add/remove select them. I think it'd be possible to recycle the code used for the resources module

**Comment by willgearty** [comment]
I think @kkbrum volunteered to make a mockup for this. I'd be happy to implement after that.

**Comment by kkbrum** [comment]
I agree with Miles that this could have the same layout as resources. Here's a mockup of the fields it would have, with some notes about line items in italics!

**Import line items from a previous program**
Program dropdown
_(I would exclude the auto-generated line items from those that get imported. Those are sibling discount, program admission, financial aid grant, and student payment. These all should not be modified via this page (sibling discount can be modified through program settings or tag settings pages currently, and the rest should not be changed))_

**Add/modify a line item** 
Name:
Cost:
Required checkbox (help text: Should this line item be automatically added for every student?)
Max quantity:
_(I would not include the “for payments” or “for finaid” checkboxes from the backend, as they are not meant to be checked for user-added line items.)_
Options: _(Same remove/ add option framework as with resources)_
	For each option you want to add:
		Description: 
		Cost: (help text: If blank, takes overall cost)
		Custom cost checkbox (help text: Should the student be allowed to specify a custom amount for this option?)
