### ISSUE TITLE
Prevent duplicate Resources from being created

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#303]
Stanford ESP had a problem with Ajax scheduling that turned out to be caused by multiple Resource objects existing for a given (room name, timeslot ID) combination.  This should be prevented, and also probably enforced by a unique_together constraint.

**Comment by btidor** [comment]
Per #2036, name and event (?) should also be unique_together

**Comment by luac** [comment]
Yeah, event and timeslot ID are the same thing.

**Comment by willgearty** [comment]
For future reference: https://docs.djangoproject.com/en/1.11/ref/models/options/#unique-together

**Comment by willgearty** [comment]
Making these fields "unique_together" would break the current implementation of floating resources (#2840):
https://github.com/learning-unlimited/ESP-Website/blame/76a45d230e7fa210d61143790adae20efbbacaf1/esp/esp/resources/models.py#L220-L222

**Comment by willgearty** [comment]
It is not currently possible to create two classrooms with the same name. When trying to add a new classroom with the same name, the code below uses the existing classroom and updates it instead:
https://github.com/learning-unlimited/ESP-Website/blame/c292a39ff70e1e2066cea6fb071c59638f3a7a8a/esp/esp/program/modules/forms/resources.py#L202-L215
