### ISSUE TITLE
Make "override teacher availability" option scarier to use

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3034]
From @kkbrum:

> I think the override teacher availability button should be in a different place (where its more specific to one class after being selected and doesn’t continue the override until you uncheck it). I also think that while you should be able to schedule into the yellow or gray boxes with this checked, they shouldnt magically turn green-- there should still be some signifier that they are bad times for the teacher but allow you to override.

**Comment by willgearty** [comment]
I'm pushing this off to SR 13 because I think it needs more discussion, and because I believe the current implementation works fine as is (making this is a feature request, not a bug report).

**Comment by willgearty** [comment]
Specifically, I think leaving the styling as-is is not a good idea if we are going to change the behavior the way that @kkbrum suggested. Then there's no way for a user to know which ones are impossible (e.g. because they are trying to fit a two-block class in one available block) and which ones are just bad/able to be overriden. Basically, you could could two completely conflicting sets of information (info for without override and info with override) for a bunch of spots and you would need to somehow visualize both of those to the user at the same time? So we'd probably want at least some additional way to indicate spots that are bad but ok given the overriding (spots that are ok in both cases don't need to be distinguished). Right now we're already using color and slanted lines, so it's hard to think of something else that would work (and adding more layers of color/hatching may make the interface confusing for admins). My first instinct is slanted lines in the other direction, but I'm not really sure.

**Comment by willgearty** [comment]
I think disabling the option after scheduling an individual class is probably fine. One thing that comes to mind is that right now the override doesn't take effect until _after_ you select a class (or unselect and reselect a class), so it might also be good to change that such that if you already have a class selected, it refreshes the availability for that class when the override option is selected.

**Comment by kkbrum** [comment]
This all makes sense. I think what I would do (but you can do otherwise) is:
1. uncheck the "override availability" box after a class is scheduled/unselected (your refreshing the availability idea sounds good)
2. don't turn the yellow (teacher teaching another class that block) boxes green. Leave them yellow but allow the admin to schedule into the block. I think this is important so that the admin is aware that the teacher will be teaching two classes at once, and proceeds knowing this, instead of having the boxes magically turn green.
