### ISSUE TITLE
Text message number shouldn't be required to confirm student registration

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#3119]
At the bottom of the student registration confirmation page, there is a box that says "Enter your cell phone number in the box below if you would like to receive a text message reminder in the week before Splash."  This suggests that you don't have to enter a phone number.  However, if you click "Confirm Registration" without entering a phone number, it doesn't allow you to confirm, and prompts you to "Please fill out this field."

<img width="588" alt="Screen Shot 2020-09-26 at 12 32 47 PM" src="https://user-images.githubusercontent.com/1224184/94349162-ea876180-fff6-11ea-8f34-d1766ab582de.png">

Tested on dev3.learningu.org.

**Comment by willgearty** [comment]
I think that text message module can actually be deprecated, because we now have a text message check box in the profile form.
