### ISSUE TITLE
Upgrade JQuery to highest compatible version

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#3169]

**Comment by willgearty** [comment]
Is there a particular reason for this specific version @milescalabresi?

**Comment by milescalabresi** [comment]
It was the newest when I scribbled down the note to self to upgrade it :p

**Comment by willgearty** [comment]
Right now we're on version 1.7.2:
https://github.com/learning-unlimited/ESP-Website/blob/2b970209c3ef2328e00a233a1574a7c6e4f8b83f/esp/templates/elements/html#L34

Looks like jQuery is now at version 3.5.1: https://code.jquery.com/jquery/

Not sure where you got version 1.6 from? Do we perhaps have a different version used for some specific pages?

**Comment by willgearty** [comment]
Looks like the version we have in /scripts is 1.7.1 that's used on some pages (e.g. grid-based class changes):
https://github.com/learning-unlimited/ESP-Website/blob/main/esp/public/media/scripts/jquery.js

**Comment by milescalabresi** [comment]
Yeah I'm not sure either. I made this issue quickly in sequence with the other "upgrade version of __" issues, so I likely read the wrong thing too quickly. Renaming the issue

**Comment by willgearty** [comment]
For reference:
https://github.com/jquery/jquery-migrate/tree/1.x-stable
https://github.com/jquery/jquery-migrate

**Comment by willgearty** [comment]
https://github.com/learning-unlimited/ESP-Website/pull/2248 does part of this upgrade. We'll probably want to upgrade to jquery 3 at some point in the future, so I'll leave this issue open for now.
