### ISSUE TITLE
UI Improvements to Student Attendance Tables

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#3180]
There a few small improvements that would make it easier to use. Some of these are applicable to other tables as well.
* Alternate shading of rows (light gray and white, e.g.)
* Add some icons that make clear that columns are sortable
* Center column text under header

**Comment by nrjean** [comment]
Have you tried clicking one of the columns header:
![image](https://user-images.githubusercontent.com/60372830/101290614-737a0080-37d1-11eb-8a8b-be5629f625bb.png)

**Comment by milescalabresi** [comment]
Revising :)

**Comment by willgearty** [comment]
Another moderator also suggested the icons being there from the get go. This should be pretty easy: https://www.kryogenix.org/code/browser/sorttable/#symbolsbeforesorting.

Totally agree with the shading, I think that would be a nice addition.

Finally, for centering text, I think it totally depends on the column. Centering the columns with numbers would probably be fine, but I think text columns should usually be left-aligned, especially if you are looking for the beginning of the text, it's best if it is all aligned to the left.

**Comment by willgearty** [comment]
Oh, and another moderator suggested adding a total row to show how many students are marked as checked in and attending, like this: https://www.kryogenix.org/code/browser/sorttable/#totalsrows.

**Comment by milescalabresi** [comment]
Seconded on those two as well! I see what you mean for the left-alignment, but maybe then the headers should be left-aligned as well? Or have lines? Idk we can try it multiple ways and see what works
