### ISSUE TITLE
Phase zero management page breaks if no tag "program_size_by_grade"

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3187]
Phase zero management page breaks if no tag "program_size_by_grade". It would be nice if it instead gave an informative page about how to set up phase zero correctly.

**Comment by willgearty** [comment]
Hmm...that shouldn't be the case...it's specifically designed to tell the user if the tag isn't set and direct them to the tag page:
https://github.com/learning-unlimited/ESP-Website/blob/5fd87e752358e41ba54909d94f780ea9a786096d/esp/templates/program/modules/studentregphasezero/status.html#L108-L110

The phase zero management page calls program.grade_caps() which looks up the tag internally, so there must be something wrong with that if that is actually what is causing the issue.

**Comment by willgearty** [comment]
@kkbrum could this be related to your testing of this tag?

**Comment by willgearty** [comment]
I'm going to close this issue, but feel free to reopen it if you come across this error again @kkbrum.
