### ISSUE TITLE
manage program settings page text cut off

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3199]
In fruitsalad, on the manage program settings page, some of the module questions are cut off:

![image](https://user-images.githubusercontent.com/25392075/106081002-28e87680-60e6-11eb-8898-d73d5e0e1059.png)

**Comment by willgearty** [comment]
This appears to be fixed? I'm not able to reproduce the problem on my dev server nor on Yale's site.
