### ISSUE TITLE
Privacy Policy isn't linked in a few themes

### ISSUE THREAD

**Issue by bhorowitz** [learning-unlimited/ESP-Website#3203]
It looks like the privacy policy isn't linked in the big picture theme, and perhaps some others?

**Comment by willgearty** [comment]
It's linked right here in bigpicture:
![image](https://user-images.githubusercontent.com/7232514/107592842-98c12b80-6bd3-11eb-8af9-bf1224418a6f.png)

**Comment by bhorowitz** [comment]
Hmm, I think it should be at the bottom of the page for clarity? It might be considered not on the "front page" if it is under a drop down menu.

**Comment by willgearty** [comment]
You have to see the link in order to make an account, is that not sufficient?
![image](https://user-images.githubusercontent.com/7232514/108089428-320e9880-703f-11eb-8c13-8fa834d95105.png)

Tagging @kkbrum as well.

**Comment by kkbrum** [comment]
@bhorowitz I put it there since bigpicture doesn't have any sort of footer at the moment (unlike fruitsalad). I suppose someone could add a footer and then put it there, although a footer might look weird with the bigpicture theme in my opinion.

**Comment by bhorowitz** [comment]
Perhaps on the sidebar? Looking around online there isn't really an accepted specific definition of "prominent place" for the privacy policy to be located, but I think if it isn't under a drop down that is "better".
