### ISSUE TITLE
Better text wrapping in webapp

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3211]
It's possible for text to run off the page in the webapp:

![image](https://user-images.githubusercontent.com/25392075/108291878-04ba0b80-7161-11eb-891f-d0f52e1f7c50.png)

And also into other columns:

![image](https://user-images.githubusercontent.com/25392075/108291920-17ccdb80-7161-11eb-8292-af31904bd562.png)

**Comment by willgearty** [comment]
That Katherine LongnameLongname Brumber is always such a trouble maker
