### ISSUE TITLE
Dashboard counting approved classes even if no approved sections left

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3213]
I have an approved class with two sections, both of which have been cancelled. 

The big board & statistics pages skip over this class when counting things such as teachers teaching an approved class, approved classes, etc. However, the dashboard still counts this class for such things. I think it should skip over it like the big board & statistics pages do. 

Perhaps the best solution is that when the last section of a class gets cancelled, the class status should switch to cancelled as well.

**Comment by willgearty** [comment]
I like that proposed solution @kkbrum, but we should probably also fix the dashboard stats calculation to only use classes with at least one approved section.
