### ISSUE TITLE
Message panel hidden on ajax scheduler

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3245]
Looks like at some point the message panel became hidden on the scheduler and doesn't appear even if there is an error message.

**Comment by willgearty** [comment]
Hmm...maybe it's only hidden when a class is selected?

**Comment by willgearty** [comment]
Right, so I _think_ the issue was if you encounter an error trying to schedule a class, the class stays selected, so the error message isn't shown (presumably this also happens for scheduling moderators). If we encounter an error, should we unselect the class/moderator so the message panel is shown? But if the class/moderator is unselected, that seems to imply it was successful? Tagging @kkbrum since she's been testing the scheduler a lot lately.

**Comment by kkbrum** [comment]
Could we put an error message above the class info in the panel?
