### ISSUE TITLE
Round scheduled and enrolled class-student-hours on dashboard

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3274]
![image](https://user-images.githubusercontent.com/25392075/116491731-8ff20480-a868-11eb-9212-1bc7f4877eaa.png)

The other entries of the dashboard are rounded, but these two aren't.

**Comment by michaelvdang** [comment]
I would like to contribute to solving this issue if it is still open.

**Comment by kkbrum** [comment]
Yes, you're welcome to assign yourself and tackle this! Feel free to let me, @willgearty, or @milescalabresi know if you need any direction. Also let us know if you'd like to join the webteam more broadly and we'll get you set up!
