### ISSUE TITLE
Add correct answers to more fields in custom forms

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3294]
See request from @kkbrum here: https://github.com/learning-unlimited/ESP-Website/pull/3273#discussion_r631489832
It's unclear if there aren't more fields with correct answer options due to technical limitations or dev laziness.

**Comment by willgearty** [comment]
Update: it was dev laziness

**Comment by hwatheod** [comment]
Is the purpose of "correct answers" for grading teacher logistics quizzes and the like ?

**Comment by willgearty** [comment]
"Correct answers" are set as field validators, and if a field is required, the form can only be submitted if the correct answer is provided to the field. If you don't require a field, "correct answers" are actually meaningless. They are also not shown (currently) anywhere in the results interface.
