### ISSUE TITLE
Attendance page includes classes with back-filled attendance

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3299]
This table:
![image](https://user-images.githubusercontent.com/7232514/118374993-6f25f080-b584-11eb-81ba-cd66baad8ebf.png)

includes classes that have attendance marked but not during the time block itself. I think we'd want to ~~include~~exclude classes even if the attendance registrations are from later in the day (e.g. if you are back-filling attendance or something).

**Comment by hwatheod** [comment]
I'm having a little trouble understanding this issue. 

Are you saying that, if attendance for some section is later backfilled after the section has ended, then this section should still appear in the "Sections During This Timeslot with No Attendance Recorded" ?

**Comment by willgearty** [comment]
Whoops, I think I meant that we should *exclude* classes with backfilled attendance. They should not show up in the table.

**Comment by willgearty** [comment]
This is how we currently populate this table:
https://github.com/learning-unlimited/ESP-Website/blob/e34d50af937d015e6257923806eaf4cb937b80d6/esp/esp/program/modules/handlers/onsiteattendance.py#L124-L125

We are only looking for valid StudentRegistration objects, and by default the `when` for testing validity is the end of the timeslot, so record created after the timeslot is over won't be counted. I guess we could do the validity testing ourselves and just make sure the **date** of the record matches the **date** of `when`.
