### ISSUE TITLE
MultiValueDictKeyError at /onsite/Rainstorm/2021_Spring/ajaxclassdetail

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#3310]
This is an exception reported in the logs.
It happened 100+ times during the weekend of Rainstorm May 15-16 2021.

Appears to be at esp/program/modules/handlers/teachercheckinmodule.py 
Line 197: `context['class'] = ClassSubject.objects.get(id=request.GET['class'])`

**Comment by hwatheod** [comment]
I'm a bit baffled by how this can happen, considering that the only call I could find to this ajax endpoint is at esp/public/media/scripts/onsite/teacher_checkin.js line 34, and that call always passes a parameter called `class`. The logs show that the `HTTP_X_REQUESTED_WITH` has the value `XMLHttpRequest` which indicates it is an ajax call, as expected.

**Comment by willgearty** [comment]
I believe this is fixed by https://github.com/learning-unlimited/ESP-Website/pull/3305.

**Comment by hwatheod** [comment]
I agree this looks like a duplicate of #3296 but I don't quite see how #3305 fixes it because the only changes in #3305 are in the missingteachers.html template.

**Comment by willgearty** [comment]
The problem stems from us accidentally making the wrong rows in the template have the `section-detail-tr` class, which caused the javascript here to not be able to grab the class ID:
https://github.com/learning-unlimited/ESP-Website/blob/4bba497d00446c650a918e3029562e9aa9ca6c48/esp/public/media/scripts/onsite/teacher_checkin.js#L23-L24
It then passed `undefined` as the class ID in the AJAX call, so `request.GET` was then empty, and apparently trying to access any item of an empty request.GET object returns a MultiValueDictKeyError?

**Comment by hwatheod** [comment]
Got it, thanks for explaining.  Closing this as duplicate.
