### ISSUE TITLE
ValueError at /learn/Rainstorm/2021_Spring/survey

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#3312]
This is an exception from the logs. 

invalid literal for int() with base 10: '1035 Webapp version: https://cloud.learningu.org/learn/Rainstorm/2021_Spring/onsitesurvey?sec=1035'

This is the line of code: esp/esp/survey/views.py line 109
`sections = ClassSection.objects.filter(id=request.GET['sec'], parent_class__parent_program=prog)`

The value of `request.GET['sec']` is literally the string shown above
`1035 Webapp version: https://cloud.learningu.org/learn/Rainstorm/2021_Spring/onsitesurvey?sec=1035`

I can't figure out how such a string would get into the `sec` parameter.

In Spring 2021 Rainstorm, this error only happened 2 times, but in Fall 2020 Rainstorm, it happened 48 times.

**Comment by willgearty** [comment]
That page works for me...

**Comment by hwatheod** [comment]
Did we send out an email to students with survey links? I'm wondering if somehow 

`Webapp version: https://cloud.learningu.org/learn/Rainstorm/2021_Spring/onsitesurvey?sec=1035` 

was meant to be a separate line in the email, but somehow that got mixed into the URL of the previous line, giving

`https://cloud.learningu.org/learn/Rainstorm/2021_Spring/survey?sec=1035%20Webapp%20version:%20https://cloud.learningu.org/learn/Rainstorm/2021_Spring/onsitesurvey?sec=1035`

**Comment by willgearty** [comment]
Oh! I bet one of the moderators copied and pasted from this page into zoom chat: https://cloud.learningu.org/onsite/Rainstorm/2021_Spring/section_attendance/64?secid=1035.
![image](https://user-images.githubusercontent.com/7232514/118904308-36b54800-b8df-11eb-9936-cffb3cd039d7.png)

And then one of the students copied the whole thing and put it into the URL bar.

**Comment by hwatheod** [comment]
Yes, that must be it. Totally explains everything. I searched the whole codebase for "Webapp version" but couldn't find it - I guess it must be in a template override on cloud.  

So this is a user error. Closing.
