### ISSUE TITLE
More expandable sections on program tag settings page

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3333]
There are now a lot of "help text" tags on the manage program tag settings page, particularly for teacher registration settings. I think these could use a new expandable section or cleaned up in some way so as to not have such a long list show up just from opening one section.

**Comment by willgearty** [comment]
So maybe a separate category "Teacher Registration Form Settings"?

**Comment by kkbrum** [comment]
Sounds good to me!
