### ISSUE TITLE
Link to edit deadlines/permissions at top of some pages is broken

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3335]
The little reminder at the top of registration pages that tells you who has access to the page has a link to help you edit deadlines. On some pages the link is correct, and some it is broken. The broken one I have seen is on /teach/one/two/onsitesurvey, linking to manage/deadline_management/index.html instead of /manage/one/two/deadline_management/

**Comment by willgearty** [comment]
Ah, it's probably expecting `one` and `two` to be in the context (which is admittedly a bad assumption).

**Comment by kkbrum** [comment]
(update: now that the /onsitesurvey page is fixed, it doesnt have this link anymore anyways, but perhaps this is still an issue elsewhere so i'm leaving it open until someone checks to confirm)
