### ISSUE TITLE
Include paid optional items on student schedules

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3342]
It looks like in the past some programs would list the optional items that students have paid for on the students' schedules. This doesn't happen anymore, but it looks like an example of the code exists in some capacity in the HTML version (albeit commented out):
https://github.com/learning-unlimited/ESP-Website/blob/98501776a014a01eeba8c8105ee2aca2a7d7bee3/esp/templates/program/modules/programprintables/singleschedule_student.html#L6-L17

I think Yale uses an override to put things like this on their printed (LaTeX/PDF) schedules? Maybe @kkbrum or @milescalabresi have thoughts/ideas.

**Comment by milescalabresi** [comment]
Yes, we put things like different pizza toppings or shirt sizes in the LaTeX schedules. I think it's a useful option to have. I envision a possible future of the schedule printable being a configurable page with checkboxes for what to include

**Comment by willgearty** [comment]
Ongoing list of potential "knobs" (with the default in parentheses):

- Student info block, including username and user ID (True)
- Amount owed (True)
- Barcode (True)
- Extra costs, e.g., meals (True)
- Pre-schedule text (blank?, maybe tag controlled)
- Post-schedule text (see template, maybe tag controlled)
- Class codes (True)
