### ISSUE TITLE
sorttable.js stops working on attendance page in some situations

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#3395]
Under some conditions (still investigating), sorttable.js on the section attendance page stops working. When you click on the arrows in "First Name" or "Last Name", it doesn't sort anything and you see this error in the console log:

<img width="487" alt="sorttable.js error" src="https://user-images.githubusercontent.com/1224184/129487710-42b6a426-95d9-46b6-94c6-e3f111515397.png">

Possibly related to #3394.

**Comment by willgearty** [comment]
Do you know which section this was for @hwatheod?

**Comment by willgearty** [comment]
I've also noticed that sometimes the up/down arrows can appear in the cells of the first row of the table instead of just the header cells.

**Comment by hwatheod** [comment]
Able to reproduce this on dev3 as follows:

1. Go to https://dev3.learningu.org/teach/Sploosh/current/section_attendance?secid=1182
2. Make sure both students (Draco Malfoy and Luna Lovegood) are not marked as attending. If necessary, unmark them and refresh the page.
3. By default, it is sorted by last name. So Luna should be listed first, and Draco second.
4. Click the arrow to sort by first name. Now Draco should be listed first, and Luna second.
5. Mark Luna as attending.
6. Click the arrow to sort by last name. It doesn't sort and you get the error above.

**Comment by hwatheod** [comment]
> Do you know which section this was for @hwatheod?

This wasn't on the production site. I found this on dev3 while investigating #3394. 

On another project I worked on, I had problems with sorttable.js getting out of sync in certain situations if the table gets updated. I am suspecting the cause of #3394 is that sorttable put the check marks in the wrong places after sorting.

**Comment by willgearty** [comment]
Ah, I think this error has something to do with the `<tfoot>` in the table. In the new version of sorttable.js, it makes the headers in the footer clickable for sorting columns:
https://github.com/learning-unlimited/ESP-Website/blob/450099579b87e24496cd74853ff7a77dafafed4a/esp/public/media/scripts/sorttable.js#L81-L83

If I comment out these lines, it seems to fix the issue you outlined above.
