### ISSUE TITLE
Allow bulk downloads from filebrowser

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#3441]
Create a button to download all selected items in the filebrowser. The use case in mind is for downloading all documents (e.g. waivers) uploaded in response to a student or teacher extra form questionnaire

**Comment by willgearty** [comment]
For this specific use case, it might also be useful to be able to bulk download from the custom form results page?

**Comment by milescalabresi** [comment]
Yes, definitely. I wasn't suggesting that the button should necessarily be in the filebrowser interface, just that that's where the files are stored. I think you're right it makes more sense to have this button in the custom forms interface (not that the options are mutually exclusive).
