### ISSUE TITLE
Class list on teacher mainpage is UGLY

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3455]
We've added so many buttons, so there's lots of functionality, but now it just doesn't look very good IMHO. I think we could either make some of the buttons/details hidden with a "expand for options" link or have another page that you need to click to to access some of the functionality. It also probably wouldn't hurt to use bootstrap buttons (that might even be an easy way to clean things up, with a button dropdown or something like the class search/printables pages).

This is pretty gross:
![image](https://user-images.githubusercontent.com/7232514/143055360-189918e2-8992-4ead-9202-bfb8bcf1d7ac.png)

**Comment by willgearty** [comment]
What about a popup like on the dashboard? The mainpage could have a simplified list of the classes, then a popup would show all of the more detailed information and specific links?

**Comment by kkbrum** [comment]
Here's the gist of what I'm thinking:
![ESP Class List Mockup-1 (1)](https://user-images.githubusercontent.com/25392075/163503026-a39abdd7-1e92-4094-8f2a-d45c985f9f32.jpg)
