### ISSUE TITLE
meta: wiki doesn't work

### ISSUE THREAD

**Issue by ajsirota** [learning-unlimited/ESP-Website#3458]
All I see is "This is diogenes, a server managed by Learning Unlimited. There is nothing to see here." Is this on purpose?

**Comment by willgearty** [comment]
Thanks for reporting an issue @ajsirota! Could you provide more information about what you're trying to do? Is this in a development server or for a live site?

**Comment by ajsirota** [comment]
This is just attempting to click a link on the site to `wiki.learningu.org`.

**Comment by willgearty** [comment]
Ah, the wiki is down for the time being (due to some spam issues we were encountering). Are you looking for a particular resource or information about something in particular?

**Comment by ajsirota** [comment]
I was trying to see if there was a dummy database I could start a development site with so I didn't have to make a DB for development testing. 

BTW, to counteract MediaWiki spam, the [ConfirmEdit extension](https://www.mediawiki.org/wiki/Extension:ConfirmEdit) with hCaptcha works well.

**Comment by willgearty** [comment]
@ajsirota if you email me at willgearty@gmail.com, I can help you out!

**Comment by ajsirota** [comment]
Ok, thanks!
