### ISSUE TITLE
Volunteer shift schedule in e-mail

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#348]
From Stanford: The comm panel has the ability to include a user-customized schedule via {{ program.schedule }} in its e-mails.  It would be nice to provide a schedule of volunteer shifts as well when e-mailing volunteers.

**Comment by willgearty** [comment]
Is there a way to print volunteer schedules outside of the comm panel implementation?
I see a generic schedule function in the code in [programprintables.py](https://github.com/learning-unlimited/ESP-Website/blob/e078c36b56c5c8bb584f22926e490dc4912c1851/esp/esp/program/modules/handlers/programprintables.py) that looks like it could make volunteer schedules, but don't see any way to access it through the website.
Thanks,
Will

**Comment by benjaminjkraft** [comment]
I am not aware of one, and the only code I see is for the email version.  You're welcome to open a separate issue to request one.

**Comment by willgearty** [comment]
This is fixed.
