### ISSUE TITLE
Remove front-end references to ESP

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#354]
Most chapters don't call themselves ESP, so we probably don't want to reference ESP by default on any front-ends.

The only thing that immediately comes to mind is the /myesp/ set of pages; we should possibly consider changing this to something else.

There are possibly other references, but I don't know of them off the top of my head (or maybe there isn't anything else!)

**Comment by willgearty** [comment]
Fixed by #2534.
