### ISSUE TITLE
Request cancellation option is broken

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3544]
It looks like https://github.com/learning-unlimited/ESP-Website/pull/3525 broke the "Request Cancellation" option on the teacher reg page. It should activate javascript rather than linking to a page.

**Comment by kkbrum** [comment]
I moved the cancellation button outside of the dropdown menu, but the submit button now gets disabled before the form is truly submitted. This has to do with #3482. It appears the </form> tag is in the wrong spot if you inspect the element, although it's correct in the code. If you comment the line from #3482 that disables the submit button, then the form submits as desired with all the proper post data, however the </form> tag still appears in the wrong spot right up until you hit the submit button, and then it moves! Odd. 

The current progress is in the branch fix-cancel-button.

**Comment by willgearty** [comment]
This is now fixed in the req-cancel-fix branch.
