### ISSUE TITLE
Allow purchasing additional items after paying

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3570]
Now that we can pay via credit card for partial amounts (e.g., after receiving partial financial aid, https://github.com/learning-unlimited/ESP-Website/pull/3157), it is now possible to add items to your "cart" after paying and then paying again. Therefore, we should remove the restrictions that prevent students from going to the donation and extracosts modules after paying. We could even change the /payonline page such that you could increase your donation amount after paying (e.g., after really enjoying the program) (I bet @bhorowitz would really like that).

**Comment by kkbrum** [comment]
This is started in the multiple-payments branch. There are tags for whether students should be able to access extracosts or not after paying and also for the text that should be displayed on the extracosts page if so. Those are both functional. 

The goal was to then disable de-selecting any items that were already paid for, either in the extracosts handler or with javascript after the fact, but I'm not really sure how to make either of those happen
