### ISSUE TITLE
Electronic checklists for operations/logistics

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#36]
We want Etherpad for checklists!

Well, maybe.  We already have some checklisting abilities, a per-class set of checkboxes; but IIRC there's no UI for creating them and they're really only useful for relatively specific things.  We should have something with broader functionality.

**Comment by benjaminjkraft** [comment]
I think at this point there are plenty of external tools that are better than whatever we'd build.  If any chapters want this as a feature, or anyone else thinks otherwise, please reopen!
