### ISSUE TITLE
Allow setting min/max grade by section

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#3622]
Requested by Clark. Could we make a tag (or something) to allow teachers to make one section of a class for middle schoolers and one for high schoolers rather than having to make two separate classes with the same (or very similar) names.

**Comment by willgearty** [comment]
Duplicate of https://github.com/learning-unlimited/ESP-Website/issues/839. I'll ask the same question here: what's wrong with just registering two classes? You can even import the first class and then change the grades and save as a second class.

**Comment by milescalabresi** [comment]
Closing, sorry for the duplicate

**Comment by milescalabresi** [comment]
Closing, sorry for the duplicate
