### ISSUE TITLE
Github Actions dropped support for python 2.7

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3655]
We'll need to update our actions based on some of these comments here: https://github.com/actions/setup-python/issues/672

**Comment by milescalabresi** [comment]
fixed by #3616

**Comment by willgearty** [comment]
While I agree this will be fixed by migrating to python 3, I think we should try to resolve this issue before then so we can continue to use GitHub actions for other pull requests until we've migrated.
