### ISSUE TITLE
7-12 dialog box appears twice when importing class

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3668]
For class import from a previous program, if you select 7-12, the dialog box appears twice. Noticed by @milescalabresi

**Comment by willgearty** [comment]
Hmm...I'm not able to reproduce the duplicate dialog box issue. However, I did notice that if you select "cancel", the form is still submitted.

**Comment by willgearty** [comment]
lol, I fixed that issue and then got the duplicate box issue...fix incoming!
