### ISSUE TITLE
Emails in "from" field must match "learningu.org"

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#3709]
Per [new email rules](https://sendgrid.com/en-us/blog/gmail-yahoo-sender-requirements#5-dont-impersonate-gmail-from-headers), Gmail (and likely Yahoo) will not deliver email that don't match a domain we register (more details [here](https://support.google.com/a/answer/10032169?sjid=6612418846590111173-NA#alignment)). It's fine to use any address in the "reply-to" field, though. This issue is to add a validation check to the comm panel form to check if the "from" field ends in .learningu.org, and if not, throw an error to the admin telling them to use an LU address and maybe suggesting they use the reply-to field.

Note: this request is time-sensitive as Gmail will start enforcing these rules soon:
> If a sender does not meet the requirements by February 2024, they will start to see temporary errors occurring on a small percentage of their non-compliant mail to Google recipients. In April 2024, a small percentage of the mail will be rejected and that percentage will gradually increase over time.

**Comment by willgearty** [comment]
What should we encourage people to put in the "from" field? Should we link to the /manage/redirects/ page so people can make email redirects? Or should we encourage them to just use the default (which is their personal email redirect)? I feel like if we don't provide guidance people may get confused.

**Comment by milescalabresi** [comment]
That's a good question. The redirects don't actually hide your email, just act like a distro list (it'd be cool if we could change that, but that's a separate issue). I think use the default for now and lean on the reply-to feature? It is also possible to put a non-email in the "from" field (such as the name of your program), but I'm not sure how much Google et al will like that
