### ISSUE TITLE
Redirect tables cut off when text is too long

### ISSUE THREAD

**Issue by willgearty** [learning-unlimited/ESP-Website#3728]
![image](https://github.com/learning-unlimited/ESP-Website/assets/7232514/841de016-18f0-43f6-b5e5-98d0bfcbe64f)

**Comment by willgearty** [comment]
I think the tables just need "table-layout: fixed;"

**Comment by willgearty** [comment]
Another example: https://princeton.learningu.org/manage/redirects/

**Comment by MysteryManav** [comment]
@willgearty i would like to fix this issue, can you specify where the table that needs to be modified is ?

**Comment by willgearty** [comment]
@MysteryManav the tables are in this file: https://github.com/learning-unlimited/ESP-Website/blob/main/esp%2Ftemplates%2Fprogram%2Fredirects.html.
