### ISSUE TITLE
Formatting of schedules 

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#373]
We have the ability to include a personalized student/teacher/volunteer schedule in comm panel e-mails by using the smart text tags {{ program.student_schedule }} et al.  However, these schedules are rendered in a tabular plain text format that only looks good if rendered in a fixed-width font and the fields fit within the allotted number of spaces.  We would like an alternative rendering scheme (either rendering with HTML or making more clever use of plain text) so schedules look good in a wider variety of situations.

**Comment by willgearty** [comment]
Stanford would also love to have this enhancement implemented. It is a valuable tool to be able to include these schedules in emails, but the formatting is currently atrocious and unchangeable.
Would there be a way to implement template overrides for each smart text tag so chapters can alter the default text and formatting?
