### ISSUE TITLE
Incorporate line items module into "smart" program settings

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#3745]
Currently, as a ``choosable=1`` module, ``studentlineitems`` shows up in the program modules list even if there are no ``extracosts``. I propose we link it to the [relevant program settings question](https://github.com/learning-unlimited/ESP-Website/blob/stable-release-15/esp/esp/program/forms.py#L80). (Currently, it is simply [relegated to the all modules list](https://github.com/learning-unlimited/ESP-Website/blob/stable-release-15/esp/esp/program/modules/handlers/lineitemsmodule.py#L133) but always loaded). Reported by Clark

**Comment by willgearty** [comment]
Fixed by #3754
