### ISSUE TITLE
"Open" deadlines button doesnt open future deadlines

### ISSUE THREAD

**Issue by kkbrum** [learning-unlimited/ESP-Website#3782]
"Open" deadlines button does not currently open the deadline if the start date is in the future. It should move the start date to "now" if it is in the future. In this case, I would probably not delete the end date (as it currently does), since the end date would also be in the future. The current behavior of deleting the end date makes sense for past deadlines, just not future ones.

**Comment by willgearty** [comment]
@kkbrum let me know what you think about the fix I implemented. I think always opening the end date is good to ensure consistent behavior.

**Comment by kkbrum** [comment]
Looks great!
