### ISSUE TITLE
Fix AJAX caching issues (without removing caching entirely)

### ISSUE THREAD

**Issue by gkanwar** [learning-unlimited/ESP-Website#430]
See the schedule_assignments JSON view in the JSONDataModule. This view was giving problems during Splash scheduling due to caching, so I temporarily removed caching to fix the issue. This should be fixable if the cache dependencies are corrected.

**Comment by luac** [comment]
Not sure what this is referring to, because according to the Git history the schedule_assignments view is and has always been cached.
