### ISSUE TITLE
Classes scheduled in ajax scheduler but not in manage page or teacherreg

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#478]
I have absolutely no clue how this is happening, but it is.  The manage page shows only some failed consistency checks and no scheduling of the class, and the ajax scheduler shows it normally.  Teacher reg shows it as unscheduled, too, and I think it disappears from studentreg.

I don't have existing examples because I don't have a good way of finding them, and fix them when I find them, but on MIT's site, M6786s2 recently had this issue; I think I've had it once or twice before.  The consistency checks said:
> Some checks failed:
> M6786s2 has resource events: Sat Nov 17: 12:05 to 12:55 PM, Sat Nov 17: 11:05 to 11:55 AM, Sat Nov 17: 10:05 to 10:55 AM and meeting_time events:

Anyone have any clue?  (Even any clue how to find these when they do happen?)

**Comment by mgersh** [comment]
I want to blame this on #1378, which is fixed now, but there's no way to be sure.

**Comment by benjaminjkraft** [comment]
I agree.  Let's close this, and we can reopen it if we find more instances.
