### ISSUE TITLE
Disallow gaps in schedules

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#49]
The schedule-constraint system should be able to disallow gaps (periods of times without classes) in schedules

**Comment by benjaminjkraft** [comment]
I haven't heard requests for this from any chapter any time recently, and MIT certainly doesn't want it, so I'm going to close this issue.  If a chapter does suddenly want it, it should be possible to set up a schedule constraint manually without a code change, or to add an interface or tag that automatically does so, and we can reopen that issue at that point.
