### ISSUE TITLE
Scheduling checks display awkwardness

### ISSUE THREAD

**Issue by ruthie** [learning-unlimited/ESP-Website#515]
Some of the tables on the scheduling checks page are wider than the width of the page on MIT's site and sites with similar designs and this looks awkward.

![ajax_awkward](https://f.cloud.github.com/assets/1218629/15168/dedaf484-4706-11e2-9caa-ab62eac59c4f.png)

Proposed solution:  panel with a horizontal scrollbar.

**Comment by willgearty** [comment]
This is fixed by https://github.com/learning-unlimited/ESP-Website/pull/3000.

**Comment by willgearty** [comment]
Whoops, apparently this is still an issue even after https://github.com/learning-unlimited/ESP-Website/pull/3000:
![image](https://user-images.githubusercontent.com/7232514/214894812-831bbd0d-1f92-4608-8930-92470bfcd4c0.png)
