### ISSUE TITLE
Print free periods in schedules

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#566]
Suggestion (paraphrased) from a student: Make the schedule print free periods explicitly, rather than simply as the absence of a class for that period.

Probably makes sense for this to be tag-controlled, since it would be confusing more than useful for some programs.  But I think for full-day Splashes with multiple lunch blocks, it might be more readable to students.  (Or it might make them sad, if there are lots of free blocks, or it might confuse people who register for relatively few classes.  Probably worth discussion before we spend time on it.)

**Comment by willgearty** [comment]
I believe the `studentschedule_show_empty_blocks` tag accomplishes this.
