### ISSUE TITLE
Changing delete --> request delete for teachers

### ISSUE THREAD

**Issue by shulinye** [learning-unlimited/ESP-Website#577]
Currently, under some circumstances, teachers are not allowed to delete their class. Sometimes, they still want to. If they could, say, click a button that says "Request Delete", which emails us with a link that lets us delete, that could be useful.

**Comment by willgearty** [comment]
Could this just be a mailto: button which starts an email for the teacher to complete and send?

**Comment by benjaminjkraft** [comment]
I think the idea of this would be that we could just click a link and not have to go find the class and such.

**Comment by willgearty** [comment]
Presumably we want a way for the teacher to explain why the class should be deleted or cancelled?

Also, would we want to differentiate between cancelling and deleting classes?
At Stanford, we're always hesitant to delete classes unless they are duplicates or mistakes.
Usually when a teacher wants us to "delete" a class, we really want to "cancel" it, but that could be chapter-specific.

**Comment by benjaminjkraft** [comment]
Yeah, presumably it would need to be a form.  And it may make more sense for this to cancel them, yeah.
