### ISSUE TITLE
Support Django 1.5

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#618]
Hopefully this isn't going to be a big deal, but you never know.

**Comment by benjaminjkraft** [comment]
Is anyone taking point on moving us to newer django?  Support for Django 1.4 is expected to end in [October 2015](https://docs.djangoproject.com/en/dev/internals/release-process/#lts-releases) and at the rate we've been putting out stable releases, it's entirely possible we'll only put out a single stable release between now and then, and it would be good to have this well-tested before then.

**Comment by joeleg** [comment]
I am currently investigating the remaining issues with the FormWizard
