### ISSUE TITLE
Ajax scheduling doesn't like classroom names with commas in them

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#624]
We currently don't allow classes to be scheduled into classrooms that contain commas (the user gets an error message "Specified Classrooms not found in the database" which is much nicer than a silent failure, but still wrong).  This.  We can either change the scheduling module code (around ajaxschedulingmodule.py:338) to support commas, or change the resource module form code to prevent people from entering commas in the first place.

**Comment by willgearty** [comment]
This is no longer an issue (probably as of the new ajax scheduler).

**Comment by willgearty** [comment]
Fixed by #2202.
