### ISSUE TITLE
Simple interface to remove student from all classes

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#640]
It would be great to have a single button to remove a student from all of their classes (e.g. if they email us that they can't make it).

**Comment by willgearty** [comment]
Is the cancel registration button sufficient for this, or are you looking for something that wouldn't require morphing?

**Comment by benjaminjkraft** [comment]
Yeah -- also some chapters don't use the cancel reg button as I recall.

**Comment by willgearty** [comment]
Shouldn't be too hard to mimic the cancel registration button through a button on the user view page.
