### ISSUE TITLE
Student Schedules PDF preview

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#66]
Have some way of previewing student-schedules PDF's before we have room numbers

**Comment by bhorowitz** [comment]
What situation would this be used? Don't all classes require classrooms to be scheduled using the AJAX scheduler?

**Comment by benjaminjkraft** [comment]
Yeah, I don't know that this really makes sense to me as such -- we generally have room numbers before there are students with schedules!
