### ISSUE TITLE
Viewing the catalog as a 6th grader renders incorrectly

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#7]
"The catalog shows all class titles/teachers (the title block), but nothing shows up underneath. It doesn't say anything like "you are not in the correct grade for this program". This is a REALLY minor bug." - Gurtej

**Comment by mgersh** [comment]
Either this isn't true anymore, or I'm guessing wrong about what it's referring to. It probably doesn't need to still be open.
