### ISSUE TITLE
Make onsite class changes grid faster

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#75]
Apparently it's somewhat slow/laggy in some scenarios

**Comment by luac** [comment]
For the pauses, I think one issue that might be impacting the responsiveness of the UI is #1547. Should do some profiling to determine if the Javascript itself is slow beyond that.

**Comment by benjaminjkraft** [comment]
This seemed pretty fine to me during Splash, so I'm going to close it; feel free to reopen if people have more problems.
