### ISSUE TITLE
Survey link on student schedules

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#796]
Stanford places a URL for the survey on their student schedules.  This is a fairly good idea except that they do this with a template override and have to update the override every time (often forgetting to do so until a late hour).  It would help if we put something like {{ survey_link }} in the context for this, and potentially make it show up on the default template if the survey module is enabled.

**Comment by kkbrum** [comment]
Nowadays I think QR codes are more relevant, so we could place an automatically generated QR code on the schedule if the survey exists (perhaps with a link as well for wider accessibility)

**Comment by willgearty** [comment]
For the Stanford case, this should now be fixed by https://github.com/learning-unlimited/ESP-Website/pull/2801. Also, programs can just use the student webapp, which has the surveys built right in.
