### ISSUE TITLE
Frontend for running the lottery

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#803]
Another somewhat obvious need of ours that didn't have a ticket yet: The lottery backend (LotteryAssignmentController) is gaining new capabilities and is still fairly fast.  It would be great if there was a user interface for adjusting the configuration, computing assignments, reviewing stats and committing the results; this would make it much easier for other chapters to adopt the lottery if they wanted to.

**Comment by benjaminjkraft** [comment]
Added in #1038.
