### ISSUE TITLE
HTML in student nametags

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#85]
Student nametag generation indicated that you can put HTML in the program name, but HTML doesn't render (it's simply written as text).  We should probably render it as HTML, possibly update the text.

**Comment by bhorowitz** [comment]
I'm confused what sort of HTML you would use in student nametags? Where does it say that you can use HTML in the program name?

**Comment by benjaminjkraft** [comment]
Right here on the nametag options page: https://github.com/learning-unlimited/ESP-Website/blob/main/esp/templates/program/modules/nametagmodule/selectoptions.html#L103.  That said, probably it's better to just remove that text.
