### ISSUE TITLE
Break down account balances

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#874]
The accounting system will tell you the balance of an account (which is the sum of all money that account has received, minus what it has sent).  These numbers don't make much sense without an aggregate of the sources and destinations of the money.  For example:
```
Main account for Splash! 2011 (splash-2011)

    Balance: $14765.00
```
It would be helpful if you could see something like this:
```
Main account for Splash! 2011 (splash-2011)

    Transferred from Accounts Receivable (receivable): +$    X.00
    Transferred to   Financial Aid Grants (grants):    -$    Y.00
    Transferred to   Accounts Payable (payable):       -$    Z.00
    Balance:                                            $14765.00
```
And furthermore, you could look at the summary for Accounts Receivable to see how many payments were received, relative to the amount expected by the program.

**Comment by btidor** [comment]
Fixed in #1025.
