### ISSUE TITLE
Make payment history for individual students more accessible

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#95]
We have this whole fancy double-ledger accounting system (I still only mostly understand the concept of double-ledger accounting and how it's applied to us here, but that's a separate story...) which tracks all kinds of payment information.  It would be really nice to expose that information via a useful UI.

This may or may not actually be easy, depending on how much effort has to be put into understanding the existing interface...

**Comment by joeleg** [comment]
Here is an initial mockup of what this screen could look like:

https://www.evernote.com/shard/s310/sh/c361c327-b95f-42e6-981b-446de42e3e75/a31069b21822ed151be0cc285eb87155

**Comment by benjaminjkraft** [comment]
My guess is that totaling the entire student's ledger is not that meaningful since I don't think it always gets marked if people pay in cash, but the rest of that looks good to me.

**Comment by pricem** [comment]
I think this looks great.  I would just write a reminder message near the top, to the effect of "Reminder: Onsite payments are not always recorded."

**Comment by benjaminjkraft** [comment]
Sounds good to me.

**Comment by willgearty** [comment]
I feel like this is fixed by https://github.com/learning-unlimited/ESP-Website/pull/2400 (although it could probably be better).
