### ISSUE TITLE
Migrate to Django's new test runner

### ISSUE THREAD

**Issue by pricem** [learning-unlimited/ESP-Website#954]
Split from Django 1.6 support issue (#618): Django 1.6 uses a new test runner which uses the discovery feature of Python's unittest module.  This changes the requirements for test importing.  See https://docs.djangoproject.com/en/1.6/releases/1.6/#new-test-runner

Because of the large number of changes required and the potential merge conflicts, this issue has not yet been addressed yet (we are using a legacy test runner), and should be done so in the next few months (after stable release 4).

**Comment by willgearty** [comment]
I believe this was fixed in #1779.
