### ISSUE TITLE
Implement Fabric Deployment Script

### ISSUE THREAD

**Issue by ghost** [learning-unlimited/ESP-Website#965]
A fabric deployment script is needed to replace the existing installation script. This script will provide automated deployment for both production and development configurations

This script will leverage:
- Fabric: http://fabric.readthedocs.org/en/1.8/
- django-fab-deploy: https://django-fab-deploy.readthedocs.org/en/0.7.5/

**Comment by milescalabresi** [comment]
this has been fixed
