### ISSUE TITLE
UserHasPerms() caching

### ISSUE THREAD

**Issue by aseering** [learning-unlimited/ESP-Website#99]
UserHasPerms() is weird in that its return value changes as a function of, among other things, the system clock.  It's also quite expensive, database-intensive, and frequently-called.  However, its dependency on the system clock is known at runtime; it could report when its own value will next change.

We should enhance the caching framework to be able to cache functions whose values change predictably with time, and cache UserHasPerms() accordingly.

**Comment by mgersh** [comment]
This function doesn't seem to exist anymore, although I think I just found some dead code by grepping for it
