### ISSUE TITLE
Survey Dump Sometimes Returns Duplicately-named Worksheets

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#993]
When downloading an Excel dump of survey data, the returned file has multiple worksheets defined, each with a different name for the tab labeling. These worksheets are for different types of data: program-wide teacher data, program-wide student data, class-specific student data, etc. The code attempts to give them all unique names. However, they are not allowed to have names longer than 31 characters, so the code truncates the names if necessary. If the first 28 characters of the survey names are the same (for example, "Stanford Splash! Spring 2013 Teacher Survey" and "Stanford Splash! Spring 2013 Student Survey"), they truncate to the same names, and this causes an error when creating the Excel spreadsheet. There are two independent fixes to this problem in stanford-prod and chicago-prod, which fix the problem by prefixing the name with something unique. I also have a more verbose fix on a local branch. One of these three fixes should be applied to the main branch.

There is a related bug, fixed in stanford-prod, which causes errors because the worksheet names include invalid characters. See See https://github.com/python-excel/xlwt/blob/8f0afdc9b322129600d81e754cabd2944e7064f2/xlwt/Utils.py#L154. This fix also needs to be applied in main.

I should be able to get to this, but I'm creating this issue as a reminder to myself.

**Comment by benjaminjkraft** [comment]
Duke also has a local change for this.  Can one of these make it into main?

**Comment by willgearty** [comment]
The duplicate name bug was finally merged to main in #2798.
